#include "common.h"

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", SetPosition__11CCharacter2FPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", AddOutLine__11CCharacter2FPcP12COutLineDraw);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", CopyOutLine__11CCharacter2FP11CCharacter2);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", Draw__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", SetDeformMesh__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", DrawStep__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", GetCameraDist__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", DrawDirect__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", DrawShadowDirect__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", UpdatePosition__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", ResetDAPosition__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", GetDefaultStep__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", SetStep__11CCharacter2Ff);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", ResetMotion__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", GetChgStepWait__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", CheckMotionEnd__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", SetMotion__11CCharacter2Fii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", SetMotion__11CCharacter2FPci);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", SetNowFrameWeight__11CCharacter2Ff);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", SetMotionPara__11CCharacter2FPcii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", SetDAnimeEnable__11CCharacter2Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", GetSoundInfoCopy__11CCharacter2FP9mgCMemory);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", CheckFootEffect__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", SePlay__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", Step__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", StepDA__11CCharacter2Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", SetWind__11CCharacter2FfPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", ResetWind__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", SetFloor__11CCharacter2Ff);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", ResetFloor__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", NormalDrive__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", ShadowStep__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", GetKeyListIndexPtr__11CCharacter2FiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", GetKeyListPtr__11CCharacter2FPcPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", GetSeqHeaderPtr__11CCharacter2FPcPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", DeleteExtMotion__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", DeleteImage__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", GetEntryObjectPos__11CCharacter2FiPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", GetEntryObjectPos__11CCharacter2FiPA4_f);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", GetEntryObjectPos__11CCharacter2FiiPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", GetWaitToFrame__11CCharacter2FPcf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", LoadSkin__11CCharacter2FPUiPcPcP9mgCMemoryi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", LoadPack__11CCharacter2FPUiPcP9mgCMemoryP9mgCMemoryP9mgCMemoryiP11CCharacter2);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", LoadPackNoLine__11CCharacter2FPUiPcP9mgCMemoryP9mgCMemoryP9mgCMemoryiP11CCharacter2);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", LoadChrFile__11CCharacter2FPUiPcP9mgCMemoryP9mgCMemoryP9mgCMemoryiP11CCharacter2i);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", Initialize__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", ScanInfoFile__FP11CCharacter2PUiPcP9mgCMemoryP9mgCMemoryP9mgCMemoryiP11CCharacter2i);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _V2__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _NAME__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _BODY_SIZE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _SCALE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _MATERIAL_ANIME__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _POLY_NUM__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _IMG__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _IMG_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _OUTLINE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _MODEL__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _SHADOW_MODEL__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _OBJECT_NAME__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _OBJECT_NAME2__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _MOTION__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _SHADOW_MOTION__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _VERTEX_ANIME__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _SHAPE_ANIME__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _KEY_START__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _KEY__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _KEY_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _SEQ_START__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _SEQ__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _SEQ_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _CLOTH_START__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", __ct__13CDynamicAnimeFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _CLOTH__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _CLOTH_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _POSITION__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _ROTATION__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _SE_START__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _SE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _SELP__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _SE_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _MOTION_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _EFFECT_START__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _EFFECT__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _EFFECT_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", InitEffect__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", ExecEntryEffect__11CCharacter2FP15CHRINFO_KEY_SET);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", CtrlEffect__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", StepEffect__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", DrawEffect__11CCharacter2Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", ScanInfoSkinFile__FP11CCharacter2PUiPcPcP9mgCMemoryi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _SKIN_IMG__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _SKIN_IMG_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _SKIN_MODEL__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", CreateChangeFrame__FP10mgLoadDataP8mgCFrame);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _SKIN_MOTION__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _LOD_MODEL_START__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", __ct__9CCharaLODFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _LOD_MODEL__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", _LOD_MODEL_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", ChangeLOD__11CCharacter2Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", Copy__11CCharacter2FR11CCharacter2P9mgCMemory);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/character", __as__7CObjectFRC7CObject);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", tag);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", skin_tag);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_1575);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_281);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_282);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_283);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_284);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_285);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_286);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_287);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_288__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_289);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_290);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_291);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_292);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_293);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_294);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_295);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_296);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_297);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_298__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_299);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_300);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_301);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_302);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_303);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_304);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_305);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_306);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_307__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_308);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_309);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_310);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_311);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_312);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_313);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_314);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_315);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_316);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_317);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_318);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_319);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_1395);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_1522);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_1570);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", at_1571);

// Virtual tables (.vtables)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/character", __vt__11CCharacter2);

// Small uninitialised data (.sbss)
unsigned char root_skin_frame[0x4];
unsigned char skin_frame[0x4];
unsigned char skin_name_ptr[0x4];
unsigned char nowChr[0x4];
unsigned char parent_chr[0x4];
unsigned char outline_flag[0x4];
unsigned char now_motion_id[0x4];
unsigned char now_key_ptr[0x4];
unsigned char now_seqhd_ptr[0x4];
unsigned char now_seq_ptr[0x4];
unsigned char now_cloth_id[0x4];
unsigned char outline_start[0x4];
unsigned char outline_start_tex[0x4];
unsigned char outline_tex_id[0x4];
unsigned char alloc_vertex_num[0x4];
unsigned char alloc_shadow_vertex_num[0x4];
unsigned char base_stack[0x4];
unsigned char ext_stack[0x4];
unsigned char img_stack[0x4];
unsigned char now_stack[0x4];
unsigned char set_imgblock[0x4];
unsigned char pack_file[0x4];
unsigned char outline_num_1499[0x4];
unsigned char init_1500[0x4];
unsigned char now_se_header[0x4];
unsigned char eff_pack_ptr[0x4];
unsigned char eff_pack_size[0x4];
unsigned char load_img_ptr[0x4];
unsigned char load_img_size[0x4];

// Uninitialised data (.bss)
unsigned char alloc_vertex[0x190];
unsigned char img_ptr[0x20];
unsigned char skin_mds_name[0x40];
