#include "common.h"

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", GetWeaponEffect__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", memoryInit__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", InitDungeonMain__F13INIT_LOOP_ARG);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", Initialize__13MoveCheckInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", Initialize__13CRedMarkModelFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", __as__9mgCCameraFRC9mgCCamera);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", __ct__14CActiveMonsterFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", CommonStageClassInit__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", CommonClassInit__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", EntryEventScript__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", FinishDungeonMain__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", LoopDungeonMain__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", DngMainDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", DngStep__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", RunMainEvent__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", DngMainKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", IsEventRun__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", EventScriptSetup__FP18SYSTEM_SCRIPT_INFO);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", IsRunDeadEvent__FP12CActionChara);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", ChangeSetUnit__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", CheckStatusError__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", InitEyeCamera__FP12CActionChara);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", CheckWeaponEnable__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", ResetEyeView__FP12CActionChara);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", EyeCamera__FP9mgCCameraP11CCharacter2i__2);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", DebugMainDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", DBGCMD_RunScript__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", __ct__13CFireAfterHitFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", __ct__14CChillAfterHitFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", __ct__8CThunderFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", __ct__10CAfterWireFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", __ct__12CDamageScoreFv);

// Static initialiser (.init)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dng_main", __sinit_dng_main_cpp);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1081);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1849);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1944);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1997);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1998);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_2004);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_2624);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_2628);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_2646);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_2700);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_2994);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", cam_table_3000);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", cam_table_dist_3001);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", debug_no);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3734);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1016);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1017);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1018__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1019__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1063__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1064__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1065__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1066__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1067__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1068__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1069__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1070__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1071__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1072);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1073__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1074__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1075);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1076);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1077__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1078);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1079__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1080__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1580);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1581);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1582__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1583__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1584__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1585__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1586__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1587__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1588__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1589__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1590__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1591__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1592__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1593__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1594__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1595__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1596__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1597);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1598);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1599);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1600);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1601);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1602);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1603);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1604);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1605);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1606);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1607);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1608);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1609);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1610);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1611);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1612);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1613);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1614);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1615);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1616);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1617);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1618);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1619);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1620);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1621);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1622);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1623__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1624__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1625__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1626__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1627__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1628__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1629__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1630__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1631__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1632__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1633__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1786);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1787);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1788);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1789);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1790);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1842__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1843__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1844__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1845);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1846);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1847);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1848);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_1940);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_2593);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_2594);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_2595);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_2596);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_2597);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_2598);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3336);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3337);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3496);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3589);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3602);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3727);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3728);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3729);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3730);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3731);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3732);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3733);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3791);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3792);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3793);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3794);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3795);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3796);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3797);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3798);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3799);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3800);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3801);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3802);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_3803);

// Static initialiser table (.ctor)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", D_0037B014);

// Virtual tables (.vtables)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", __vt__12CTreasureBox);

// Small initialised data (.sdata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_2044);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dng_main", at_2046);

// Small uninitialised data (.sbss)
unsigned char MainBuffer__2[0x4];
unsigned char BuffReadData[0x4];
unsigned char debag_param[0x4];
unsigned char viewAngleH__2[0x4];
unsigned char viewAngleV__2[0x4];
unsigned char init_camera[0x4];
unsigned char NowFloorInfoPtr[0x8];
unsigned char ActionScriptEnv[0x8];
unsigned char DebugPause[0x4];
unsigned char test_dist[0x4];
unsigned char DngUserData[0x4];
unsigned char DngSaveData[0x4];
unsigned char DngSaveDataDungeon[0x4];
unsigned char DngMainScene[0x4];
unsigned char BattleAreaScene[0x4];
unsigned char DngMainMap[0x4];
unsigned char ActiveMonster[0x4];
unsigned char DngMess[0x4];
unsigned char DngMess2[0x4];
unsigned char EventMess[0x4];
unsigned char MonsterMess[0x4];
unsigned char RedMarkModel[0x4];
unsigned char TreasureBoxModel[0x4];
unsigned char TreasureBoxMan[0x4];
unsigned char MainChara__2[0x4];
unsigned char FxScriptMan[0x4];
unsigned char BTsuboCol[0x8];
unsigned char PullItemMan[0x8];
unsigned char TornadoModel[0x4];
unsigned char wep_effect_cnt[0x4];
unsigned char init_1107[0x4];
unsigned char init_1824[0x4];
unsigned char water_cnt_2619[0x4];
unsigned char init_2620[0x4];
unsigned char water_cnt2_2681[0x4];
unsigned char init_2682[0x4];
unsigned char erate_2867[0x4];
unsigned char init_2868[0x4];
unsigned char camera_default_dist_2991[0x4];
unsigned char init_2992[0x4];
unsigned char reference_3008[0x4];
unsigned char init_3009[0x4];
unsigned char time_step_3092[0x4];
unsigned char init_3093[0x4];
unsigned char npc_heal_cnt_3352[0x4];
unsigned char init_3353[0x4];
unsigned char debug_cursor[0x4];
unsigned char debug_mons_no[0x4];
unsigned char debug_mons_cur[0x4];
unsigned char debug_mons_num[0x4];

// Uninitialised data (.bss)
unsigned char BuffPaketList[0x60];
unsigned char BuffPaketData[0x60];
unsigned char BuffStageMain[0x30];
unsigned char BuffStageChara[0x30];
unsigned char BuffStageSubData[0x30];
unsigned char BuffStageSubChara[0x30];
unsigned char BuffWorkData__2[0x30];
unsigned char BuffCharacter[0x30];
unsigned char BaseCharacter[0x120];
unsigned char BuffTempData[0x30];
unsigned char BuffScriptData[0x30];
unsigned char BuffEffectScriptData[0x30];
unsigned char BuffEventData[0xC0];
unsigned char BuffMDTBuild[0x30];
unsigned char BuffMDTBuild2[0x30];
unsigned char DngStatus[0x20];
unsigned char map_effect[0x20];
unsigned char AccumulateEffect[0x330];
unsigned char DamageScore[0x90];
unsigned char DamageScoreMons[0x480];
unsigned char DamageScore2[0x30];
unsigned char MsgTaskMan[0x370];
unsigned char StartupEpisodeTitle[0x20];
unsigned char BattleFX[0x50];
unsigned char LevelupInfo[0x40];
unsigned char LockOnModel[0xB0];
unsigned char WarningGage2[0x20];
unsigned char AutoMapGen[0x2A0];
unsigned char ColPrimMan[0x4410];
unsigned char RandomCircle[0x6A0];
unsigned char GeoStone[0x670];
unsigned char MainCamera[0x1F0];
unsigned char EventCamera__2[0x1F0];
unsigned char HealingEffectMan[0x330];
unsigned char MiniEffPrimMan[0x940];
unsigned char ItemBaseData[0x7920];
unsigned char afterWire[0x1200];
unsigned char VoiceUnit[0x20];
unsigned char BTsubo[0x80];
unsigned char BTsubo2[0xC50];
unsigned char RocketLauncher[0x2580];
unsigned char MachineGun[0x390];
unsigned char LaserGun[0x1300];
unsigned char LaserGunModel[0x660];
unsigned char PullItem[0x2400];
unsigned char nowload[0x40];
unsigned char at_941__2[0x10];
unsigned char WaveTable__2[0x1208];
unsigned char SparcModel[0x18];
unsigned char SwordLuminous[0x20];
unsigned char wep_effect[0x3E00];
unsigned char Sparc_fx[0x420];
unsigned char thunder[0x5280];
unsigned char tornado[0x1500];
unsigned char chillAfterHit[0x2DC0];
unsigned char fireAfterHit[0x3780];
unsigned char debug_event_stack_1106[0x30];
unsigned char stack_1823[0x30];
unsigned char at_1994[0x10];
unsigned char at_2001[0x10];
unsigned char chk_pos_2870[0x10];
unsigned char backup_pos[0x10];
