#include "common.h"

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", Initialize__11CDngFreeMapFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", InitTexture__11CDngFreeMapFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", SetUserGlid__11CDngFreeMapFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", CalcGlidPutPos__11CDngFreeMapFP9GLID_INFORfRfi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", CheckIsViewMove__11CDngFreeMapFiiRfRf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", SetNextRoomPos__11CDngFreeMapFP9GLID_INFO);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", GetNextGlid__11CDngFreeMapFP9GLID_INFOPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", GetRoomGlid__11CDngFreeMapFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", GetEntranceRoomGlid__11CDngFreeMapFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", SetTextureInfo__11CDngFreeMapFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", ResetDngMapPos__11CDngFreeMapFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", DrawBackPattern__11CDngFreeMapFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", DrawDngName__11CDngFreeMapFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", DrawLast__11CDngFreeMapFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", DrawRoot__11CDngFreeMapF9mgRect_f_P16DNGMAP_ROOT_INFOiUii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", DrawGlidCheck__11CDngFreeMapFP9GLID_INFO);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", DrawRoomOne__11CDngFreeMapF9mgRect_f_P16DNGMAP_ROOM_INFOUiif);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", DrawGlid__11CDngFreeMapF9mgRect_f_);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", CheckGeoramaMateria__FP22TRESURE_BOX_FLOOR_INFOiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", DrawDngRoomInfo__FP16DNGMAP_ROOM_INFO);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", DrawGeoramaMateria__FiPciPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", DrawTreeMap__11CDngFreeMapFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", DrawPlayer__11CDngFreeMapFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", Step__11CDngFreeMapFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", Draw__11CDngFreeMapFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", FadeIn__11CDngFreeMapFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", FadeOut__11CDngFreeMapFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", DeleteTexBlock__11CDngFreeMapFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", SetKomaMove__11CDngFreeMapFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", LoadDngInfo__11CDngFreeMapFP9mgCMemoryiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", CheckDngTreeMapFuncType__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", MakeDngTreeMapJumpNo__FiiPiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", InitEnd__12CMenuTreeMapFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", MsgInit__12CMenuTreeMapFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", Step__12CMenuTreeMapFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", Draw__12CMenuTreeMapFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", FadeInOutMenu__12CMenuTreeMapFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", DngTreeMapInit__FP9mgCMemoryPiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", Init__6ClsMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", DngTreeMapKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", DngTreeMapDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", IsCreateObject__14CBaseMenuClassFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", IsMakeObject__14CBaseMenuClassFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", IsAskExtend__14CBaseMenuClassFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", ItemCmdAfter__14CBaseMenuClassFiP16ITEMCMD_RET_PARA);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", ExitEnd__14CBaseMenuClassFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", Set__9mgRect_f_Fffff);

// Static initialiser (.init)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/dngmenu", __sinit_dngmenu_cpp);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", markOffsetTable_1092);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", root_type_texturecrd_1216);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", get_moji_tbl_1524);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", put_moji_tbl_1525);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", DngInfoMedalNumMsg);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", dngboardbrdtbl);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", dngboardbrdtbl_1);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", dngboardbrdtbl_2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", medal_xytbl_1736);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", RootTable_2119);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", Table_2133);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", bittable_2134);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", RootHokanTable0_2230);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", RootHokanTable1_2231);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", RootHokanTable2_2232);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", RootHokanTable3_2233);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", RootHokanTable4_2234);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", RootHokanTable5_2235);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", RootHokanTable6_2236);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", RootHokanTable7_2237);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", RootHokanTable8_2238);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", RootHokanTable9_2239);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", RootHokanTablePtrTable_2240);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", RoomHokanTable0_2241);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", RoomHokanTable1_2242);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", RoomHokanTable2_2243);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", RoomHokanTable3_2244);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", RoomHokanTablePtrTable_2245);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", is_reverse_tbl_2246);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", name_tbl_2728);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", bitTable_2900);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_3141);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", dng_light_circle);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", dngfreemap_num);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_1018__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_1019__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_1020__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_1021__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_1993);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2120__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2121__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2122__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2123__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2176);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2177);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2178);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2179);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2180);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2181);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2182);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2183__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2184);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2185);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2186);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2187);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2188);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2189);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2681);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2682);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2683);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2684);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2685);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2729);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2730);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2731);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2732);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2733);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2734);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2735);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2739);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2740);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2741);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2742);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2786);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2787__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2788);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2789);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2790);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_2826);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_3342);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_3343);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_3344);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_3345);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_3346);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_3347);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_3348);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_3349);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_3350);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_3451);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_3539);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_3540);

// Static initialiser table (.ctor)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", D_0037B018);

// Virtual tables (.vtables)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", __vt__12CMenuTreeMap);

// Small initialised data (.sdata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", zerumaito_offset_1110);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", stepCntTbl_1501);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", DngInfoStageNo);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", dng_player_pos);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", old_hokantbl_useno_2247);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", is_reverse_tbl_room_2248);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", maxidtable_2752);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_3043);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/dngmenu", at_3164);

// Small uninitialised data (.sbss)
unsigned char MenuDngDebugFlagSelect[0x4];
unsigned char MenuDngMap[0x4];
unsigned char dngfloor_infoview[0x4];
unsigned char dngfloor_backdraw[0x4];
unsigned char dngfloor_backdraw_alpha[0x4];
unsigned char Floor_InfoTex[0x4];
unsigned char DngInfoFishOkFlag[0x4];
unsigned char DngInfoSphidaOkFlag[0x4];
unsigned char DngAskMessageDrawFlag[0x4];
unsigned char DngInfoFloorInfo[0x4];
unsigned char DngInfoRoomInfo[0x4];
unsigned char DngInfoDrawAlpha[0x8];
unsigned char DngInfoMedalMsgPutPos[0x8];
unsigned char AlphaRate_1743[0x4];
unsigned char init_1744[0x4];
unsigned char GeoramaMateriaInfoDrawFlag[0x4];
unsigned char GeoramaMateriaInfoDrawPage[0x4];
unsigned char GeoramaMateriaNum[0x4];
unsigned char DngTreeMapActiveLightRate[0x4];
unsigned char dng_player_blink_cnt[0x4];
unsigned char DngTreeMode[0x4];
unsigned char TreeMapSaveFlag[0x4];
unsigned char TreeMapSaveNum[0x4];
unsigned char TreeMapSaveDispCount[0x4];
unsigned char TreeMapSaveHopCount[0x4];
unsigned char TreeMapSaveDispY[0x4];
unsigned char TreeMapCallDungeonSubMap[0x4];
unsigned char TreeMapCalledWorldMap[0x4];
unsigned char MenuCursorDataBuff[0x4];
unsigned char CMenuTreePt[0x4];
unsigned char old_direction_2830[0x4];
unsigned char init_2831[0x4];
unsigned char old_glid_2833[0x4];
unsigned char init_2834[0x4];
unsigned char NextFloorGlid_2836[0x4];
unsigned char init_2837[0x4];
unsigned char at_3040__2[0x4];
unsigned char at_3145[0x8];
unsigned char at_3199[0x8];
unsigned char at_3478[0x8];

// Uninitialised data (.bss)
unsigned char MenuDngMes[0x20];
unsigned char treemap_root_put[0x10];
unsigned char Floor_Info[0x10];
unsigned char MenuTreeMapStack[0x30];
unsigned char at_3142[0x10];
