#include "common.h"

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", CheckControl__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", EditModeControlLock__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", EditModeControlUnLock__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", SetHelpMes__Fiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", GetUserData__Fv__3);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", ConvColor__Ff);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", ConvColorV__FPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", emSearchColorCode__FPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", emGetPenkiItemNo__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", emGetPenkiItemNo__FPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", IntiSystemMes__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", OpenSystemMes__FP6CSceneii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", SystemMesClose__FP6CScene);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", SystemMesStep__FP6CScene);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", EditStartPlaceEffect__FP10CEditPartsPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", EditEndPlaceEffect__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", EditPreMenuAnime__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", LoadEditCursor__FP9mgCMemoryi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", GetSelPartsInfoID__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", ClearEditStepCnt__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", ClearUndoFlag__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", ClearEditFlag__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", InitEditFlag__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", StartEditMode__FP6CScene);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", EndEditMode__FP6CScenePf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", StartEditModeFromMenu__FP6CSceneiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", GetUndoData__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", UndoEnable__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", UndoPlaceParts__FP6CScene);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", StackUndoData__FP9UNDO_DATA);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", StartEditPutWall__FPQ210CEditParts8WallInfo);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", PlaceEditParts__FP8CEditMapPfPfP13EP_PLACE_INFO);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", PlaceRiverStart__FP8CEditMapPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", PlaceRiverStep__FP8CEditMap);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", NowPlaceRiver__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", RemoveMtnStart__FP8CEditMapPfPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", RemoveMtnStep__FP6CScene);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", RemoveEditParts__FP6CSceneiPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", DeleteKanketuParts__FP6CSceneP8CEditMapPfi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", PaintEditParts__FP8CEditMapiiPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", CheckPlaceAlt__FiP8CEditMapPfiPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", GetGeoMapLimitHeight__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", EditMode__FP6CScene);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", DrawEditCursorParts__FP6CScene);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", DrawEditCursor__FP6CScene);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", DrawEditHelpMes__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", CheckFocusBalanceParts__FP8CEditMapiPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", InitBalanceDraw__FP6CScene);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", GetBalanceHeight__FP6CScenePf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", DrawEditSystem__FiP6CScenePfi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", GetGeoCheckPts__FP4CMap);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", GetGeoCheckCol__FP4CMapR9mgVu0FBOXP6CCPolyi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", GetGeoCheckCamCol__FP4CMapR9mgVu0FBOXP6CCPolyi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", CheckWalkToEdit__FP6CScenePf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", CheckEditToWalk__FP6CScenePf);

// Static initialiser (.init)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmode", __sinit_editmode_cpp);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1268__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1362);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1931__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", space_str);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", place_str);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", rotate_str);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", sw_wall_str);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", magnet_str);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", onoff_str);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", remove_str);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", sel_wall_str);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", paint_str);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", undo_str);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", paint_house_str);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", paint_fence_str);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", paint_num_str);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", repaint_str);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", repaint_house_str);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", repaint_fence_str);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2188__3);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1067__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1068__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1069__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1070__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1071__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1072__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1073__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1074__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1075__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1076__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1254__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1284__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1367);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1377__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1835__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1836__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1961);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1962);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1963);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1964);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1965__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1966);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1967);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1968);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1969);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1970);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1971);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1972);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1973);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1974);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1975);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1976__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1977);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1978);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1979);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1980);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1981__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1982);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1983);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1984);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1985);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1986);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1987);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1988);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1989);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1990);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1991);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1992);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1993__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1994__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1995__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1996__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1997__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1998__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_1999__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2000__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2001__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2002);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2003__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2004__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2005__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2006__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2007__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2008__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2009__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2010__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2011__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2012__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2013__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2014__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2015__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2016__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2017__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2018__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2019__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2020__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2021__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2022__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2023__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2024__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2025__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2026);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2027);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2028);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2029);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2030);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2031__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2032);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2033);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2034);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2035);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2036);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2037);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2038);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2039);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2040);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2041);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2042);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2043);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2044__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2045);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2046__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2047);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2048__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2049);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2050);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2051);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2052);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2053);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2054);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2103);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", at_2213__3);

// Static initialiser table (.ctor)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", D_0037B068);

// Small initialised data (.sdata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmode", SysMesNo);

// Small uninitialised data (.sbss)
unsigned char EditModeNo[0x4];
unsigned char MagnetEnable[0x4];
unsigned char HighSpeedMoveCnt[0x4];
unsigned char PutSideMode[0x4];
unsigned char PuuSideRotCameraFlag[0x4];
unsigned char PlacePartsNo[0x4];
unsigned char PartsInfoID[0x4];
unsigned char RemainPartsNum[0x4];
unsigned char PlacePartsFlag[0x4];
unsigned char PartsHeight[0x4];
unsigned char MagnetPartsFlag[0x4];
unsigned char PaintItemNo[0x4];
unsigned char CursorLockCnt[0x4];
unsigned char PlaceRiverCnt[0x4];
unsigned char RemoveMtnCnt[0x4];
unsigned char eDirCurLen[0x4];
unsigned char NowSelectWallParts[0x4];
unsigned char SelectWallGroup[0x4];
unsigned char PreMenuCount[0x4];
unsigned char PreMenuMaxCount[0x4];
unsigned char CtrlLockFlag[0x4];
unsigned char eCameraDist[0x4];
unsigned char eCurRot[0x4];
unsigned char eSysTexture[0x4];
unsigned char PaintCursor[0x4];
unsigned char PaintCursor2[0x4];
unsigned char PaintCurChr[0x4];
unsigned char RemoveCursor[0x4];
unsigned char ShovelCursor[0x4];
unsigned char ShovelCurChr[0x4];
unsigned char RemoveCurChr[0x4];
unsigned char UnitCursor[0x4];
unsigned char EditHelpMesNo[0x4];
unsigned char EditHelpMesParam[0x4];
unsigned char EditHelpMesParam2[0x4];
unsigned char SysMesCnt[0x4];
unsigned char cnt_1857[0x4];
unsigned char init_1858[0x4];
unsigned char cnt_1939[0x4];
unsigned char init_1940[0x4];

// Uninitialised data (.bss)
unsigned char UndoData[0x30];
unsigned char PaintColor[0x10];
unsigned char eCurPos[0x10];
unsigned char eCurNowPos[0x10];
unsigned char ePartsCurPos[0x10];
unsigned char ePartsCurNowPos[0x10];
unsigned char ePartsCurRot[0x10];
unsigned char ePartsCurNowRot[0x10];
unsigned char PlaceRiverPos[0x10];
unsigned char RemoveMtnPos[0x10];
unsigned char RemoveMtnCurPos[0x10];
unsigned char eDirCurRot[0x10];
unsigned char WallPutPos[0x10];
unsigned char WallInfo[0x40];
unsigned char EditCursor[0x10];
unsigned char Font__2[0xC0];
unsigned char at_1148[0x10];
unsigned char at_1149__2[0x10];
unsigned char at_1445__3[0x10];
unsigned char at_1579__2[0x10];
unsigned char pos_save_1942[0x10];
unsigned char at_2063[0x100];
unsigned char at_2064[0x100];
unsigned char now_balance_h[0x10];
