#include "common.h"

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", GetUserData__Fv__2);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", InitLockCharaCtrl__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", LockCharaCtrl__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", UnLockCharaCtrl__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", IsEditMode__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", InitEditModeChg__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", NowEditModeChg__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", EditModeChg__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", EditModeChgStep__FP6CScene);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", SetDataPacket__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", PreExitLoop__FP6CScene);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", EditInit__F13INIT_LOOP_ARG);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", __as__15CameraCtrlParamFRC15CameraCtrlParam);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", __ct__12CActionCharaFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", EditExit__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", InitSubMapLoadStep__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", SubMapLoadStep__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", EditLoop__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", InitEditEvent__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", ResetEditEvent__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", RestartEditEvent__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", EditStep__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", EditDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", UpdateTrBoxFlag__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", BurnEditParts__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", editLoadSound__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", EditMapJump__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", EditGotoInterior__Fii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", EditExitInterior__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", EditDataSave__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", EditDataLoad__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", KeepEditAnalyze__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", EditAnalyzeChanged__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", LoadComVillaager__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", LoadMap__Fv);

// Static initialiser (.init)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editloop", __sinit_editloop_cpp);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1045);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1053);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1528);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2271);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_3040);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1032__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1033__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1395__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1396);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1397);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1398__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1399);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1400);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1401);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1402);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1403);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1404);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1405);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1406);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1407);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1408__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1409__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1410__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1411__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1412__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1413__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1414__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1415__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1416__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1417__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1418__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1419);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1420);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1421);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_1422);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2125);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2126);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2127);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2128);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2129);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2130);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2131);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2132);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2133);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2134);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2136);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2261);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2262);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2747);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2748);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2749);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2750);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2751);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2752);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2753);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2948);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2949);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2950);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2951);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2952);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2953);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2954);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2955);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2956);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2957);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2958);

// Static initialiser table (.ctor)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", D_0037B00C);

// Small initialised data (.sdata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", MenuInfo);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", DataPktMode);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2346);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editloop", at_2352);

// Small uninitialised data (.sbss)
unsigned char WaterFrame[0x4];
unsigned char RedBicMark[0x4];
unsigned char BlueBicMark[0x4];
unsigned char TreasureBox[0x4];
unsigned char MapNo[0x4];
unsigned char Camera[0x4];
unsigned char EventCamera[0x4];
unsigned char FixCamera[0x4];
unsigned char EditCamera[0x4];
unsigned char ActiveCharaNo[0x4];
unsigned char ControlCharaID[0x4];
unsigned char WalkChara[0x4];
unsigned char LoopCounter[0x4];
unsigned char LoopMode[0x4];
unsigned char ControlMode[0x4];
unsigned char SubMapLoadBG[0x4];
unsigned char now_load_map_no[0x4];
unsigned char EventSquareJump[0x4];
unsigned char EditDrawFlag[0x4];
unsigned char EditDrawCancelFlag[0x4];
unsigned char PauseFlag[0x4];
unsigned char LockChara[0x4];
unsigned char PreEditMenuCnt[0x4];
unsigned char EditModeChgFlag[0x4];
unsigned char EditModeChgCnt[0x4];
unsigned char EditModeChgEvent[0x4];
unsigned char MainScene__2[0x4];
unsigned char main_pkt1[0x4];
unsigned char main_pkt2[0x4];
unsigned char read_buffer_end[0x4];
unsigned char MenuDataBuf[0x4];
unsigned char MenuDataSize[0x4];
unsigned char FixCharaBuffSize[0x4];
unsigned char CrossFadeBuff[0x4];
unsigned char time_step_1481[0x4];
unsigned char init_1482[0x4];
unsigned char show_time_step_1484[0x4];
unsigned char init_1485[0x4];
unsigned char old_cm_1772[0x4];
unsigned char rain_flag_1849[0x4];
unsigned char init_1850[0x4];
unsigned char start_bt_cnt_1865[0x4];
unsigned char init_1866[0x4];
unsigned char encount_flag_1868[0x4];
unsigned char init_1869[0x4];
unsigned char show_encount_cnt_1871[0x4];
unsigned char init_1872[0x4];
unsigned char next_encount_1874[0x4];
unsigned char init_1875[0x4];
unsigned char flag_2408[0x4];
unsigned char init_2409[0x4];
unsigned char DelMainNPCflag[0x4];

// Uninitialised data (.bss)
unsigned char at_949[0x10];
unsigned char WaveTable[0x1210];
unsigned char CharaOldPos[0x10];
unsigned char EventMes1[0x2960];
unsigned char buf0[0x30];
unsigned char buf1[0x30];
unsigned char data_buf__2[0x60];
unsigned char init_dbuf[0x60];
unsigned char WorkBuffer[0x30];
unsigned char MenuBuffer__2[0x30];
unsigned char ChrEffBuffer[0x30];
unsigned char ScriptBuffer__2[0x30];
unsigned char TotalDataBuff[0x30];
unsigned char ControlCharaBuff[0x30];
unsigned char MainDataBuff[0x30];
unsigned char MainCharaBuff[0x30];
unsigned char SubDataBuff[0x30];
unsigned char SubCharaBuff[0x30];
unsigned char EventBuff[0xC0];
unsigned char CharaBufs[0x180];
unsigned char FishingBuff[0x30];
unsigned char SkyBuff[0x30];
unsigned char EditEvent[0x150];
unsigned char EdDebugInfo[0x40];
unsigned char TestVisual[0x50];
unsigned char TestFrame[0x110];
unsigned char at_1077[0x10];
unsigned char at_3041[0x10];
unsigned char beforeAnalyze[0x40];
