#include "common.h"

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", GetPenkiColor__FiPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", ConvGeoramaDataNo__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", CheckMenuLine__FPiPiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", SetEditMenuEnv__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuGeoramaInit__FP9mgCMemoryi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuGeoDebugKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuGeoramaKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuGeoramaDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuGeoramaTitleDraw__FRiPfi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuGeoramaListDraw__FRiPfii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuGeoramaAnalyzeDraw__FRiPfi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", InitDownLoadAnaunce__FP9mgCMemory);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", DrawDownLoadAnaunceSwitch__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", StepDownLoadAnaunce__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", DrawDownLoadAnaunce__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MakeDownLoadAnaunce__FiP9mgCMemoryPiPiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", InitMenuDl3__FP10mgCTexture);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", StepMenuDl3__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuPlacedHouseDraw__FRi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuPlacedHouseMessMake__FP14CEditPartsInfoP10CEditHousei);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuPlacedHousePosLinkMes__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuMapPartsDraw__FRi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuGeoramaMessageMake__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", CheckGekkaViewMode__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", InitEnd__12CMenuGeoramaFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", ExitEnd__12CMenuGeoramaFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", GetPartsIDListNum__12CMenuGeoramaFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", GetNowMakePartsNum__12CMenuGeoramaFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", GetPenkiItemNo__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", ArrangePartsList__12CMenuGeoramaFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", UpdateGeoramaPartsList__12CMenuGeoramaFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", GetNowModeLoadPartsID__12CMenuGeoramaFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", GetNowSelectEditPartsInfo__12CMenuGeoramaFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", LoadGeoramaPart__12CMenuGeoramaFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", UpdateGeoramaPartColor__12CMenuGeoramaFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", AttachFormInfo__12CMenuGeoramaFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", SetGeoListInfo__12CMenuGeoramaFiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", ReturnSelectMode__12CMenuGeoramaFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", GetNowViewModeMax__12CMenuGeoramaFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", LRCheck__12CMenuGeoramaFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MakeMsgPartsItemInfo__FP7CDC2MesP14CEditPartsInfoP21MENUFORM_MAKEBRD_INFO);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", IsMakeObject__12CMenuGeoramaFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", CalcCursorPosition__12CMenuGeoramaFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", CalcTex__12CMenuGeoramaFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", CalcMakeBrd__12CMenuGeoramaFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuGeoramaBasePush__FP12CMenuGeoramaii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", georama_menu_local_key__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuGeoramaPlacePush__FP12CMenuGeoramaii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuGeoramaMakePush__FP12CMenuGeoramaii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuGeoramaCheckPointPush__FP12CMenuGeoramaii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuGeoramaAnalyzeSelect__FP12CMenuGeoramaii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuGeoramaPaintSelect__FP12CMenuGeoramaii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuGeoramaPushKey__Fii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MakeNPCList__12CRemovalMenuFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", KeyStep__12CRemovalMenuFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuRemovalInit__FP9mgCMemoryPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", Initialize__19CCharaFrameMatchingFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuRemovalKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", MenuRemovalDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", InitEnd__14CBaseMenuClassFv);

// Static initialiser (.init)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/editmenu", __sinit_editmenu_cpp);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", old_menuparts_pos);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", old_menuparts_rot);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", now_menu_pos_mapparts);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", georama_adjust_position);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", penki_item_no);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", GeoramaColorList);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", georama_parts_adjust_scaletable);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", georama_parts_adjust_z_table);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", tbl_957);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", brdtbl_active_1314);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", brdtbl_noneactive_1315);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", ScrlBarTable_1320);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", brdtbl_noneactive_1547);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", brdtbl_1550);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", offsettable_1551);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", rectboxtbl_1555);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", postbl_2175);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", offset_2176);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", jyunintbl_2187);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_2326);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", constant_msg_xyoffsettbl_2427);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3361);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3757);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", MenuGeoramaPushFunc);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4101);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_990__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_1014__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_1132__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_1133__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_1134__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_1135__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_1136__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_1137);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_1138);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_1189__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_1277__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_1278__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_1299__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_1300__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_1860);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_2146);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_2370__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_2654);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_2655);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_2656);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_2657);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_2658);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_2659);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_2660);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_2661);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_2662);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_2663);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_2664);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_2665);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_2666);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_2667);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_2668);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_2986);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3158);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3159);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3160);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3161);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3162);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3163);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3164__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3165);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3166);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3167);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3181);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3182);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3229);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3291__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3292);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3293);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3294);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3295);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3296);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3297);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3329);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3330);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3419);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3420);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3421);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3422);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3423);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3562);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3563);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3564);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3565);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3566);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3567);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3568);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3569);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3570);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3724);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3725);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3726);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3727__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3728__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3729__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3774);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3775);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3863);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3864);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3865);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3866);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3867);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3868);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3939);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_3952);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4248);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4249);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4250);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4251);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4252);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4253);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4254);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4255);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4256);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4257);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4258);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4259);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4260);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4261);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4262);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4263);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4264);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4265);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4266);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4267);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4268);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4269);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4270);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4271);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4272);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4293);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4367);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4368);

// Static initialiser table (.ctor)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", D_0037B01C);

// Virtual tables (.vtables)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", __vt__12CRemovalMenu);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", __vt__12CMenuGeorama);

// Small initialised data (.sdata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", DownLoadMesScrlGyouNum);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", analyze_percent);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", GeoramaReqMakeFlag);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", fname_1013);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", viewmode_to_mode_convtable_1310);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", maintopicbtn_1568);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_1828__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", msgtbl_2587);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", DestroyNum_3583);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", DestroyPartsName_3587);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4151);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", at_4152);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/editmenu", fname_4292);

// Small uninitialised data (.sbss)
unsigned char HouseDrawInfo[0x4];
unsigned char HouseInfoFormGrobal[0x4];
unsigned char HousePartsID[0x4];
unsigned char HouseInfoSelectLine[0x4];
unsigned char HouseInfoSelectSelect[0x4];
unsigned char HouseInfoSelectMoveInit[0x4];
unsigned char HouseInfoSelectY[0x4];
unsigned char HouseInfoCursorAlphaOnOff[0x4];
unsigned char HouseInfoCursorAlpha[0x4];
unsigned char HouseInfoCursorY[0x4];
unsigned char PartsMakeOkTableNum[0x4];
unsigned char DownLoadInfo[0x4];
unsigned char DownLoadInfoNext[0x4];
unsigned char DownLoadInfoEndFlag[0x4];
unsigned char DownLoadInfoDrawFlag[0x8];
unsigned char DownLoadWinRect[0x8];
unsigned char DownLoadDispNum[0x4];
unsigned char DownLoadProgress[0x4];
unsigned char DownLoadMesMakeProgress[0x4];
unsigned char DownLoadMesAlpha[0x4];
unsigned char DownLoadMesMakeNo[0x4];
unsigned char DownLoadActiveMes[0x4];
unsigned char DownLoadMesUpY[0x4];
unsigned char old_menuparts_pos_flag[0x4];
unsigned char NowPolyGonFormMoveFlag[0x4];
unsigned char MenuMapPart[0x4];
unsigned char MenuGeoramaSystemData[0x4];
unsigned char MenuGeoramaCursorForceSetFlag[0x4];
unsigned char MenuGeoStoneDonwLoadFlag[0x4];
unsigned char MenuGeoStoneDownLoad_PartsNum[0x4];
unsigned char MenuGeoStoneDownLoad_Request[0x4];
unsigned char MenuGeoStoneDownLoadTime[0x4];
unsigned char MenuGeoStoneDmyCnt[0x4];
unsigned char MenuGeoStoneDmyCnt_Now[0x4];
unsigned char GeoRequestFlag[0x4];
unsigned char MenuPartsDrawStack[0x4];
unsigned char MenuMainMapInfo[0x4];
unsigned char CMenuGeoPt[0x4];
unsigned char MenuGeoramaViewNowPicNo[0x4];
unsigned char MenuGeoramaViewWallPic[0x4];
unsigned char MenuEditAnalyzeSrc[0x4];
unsigned char MenuEditAnalyzeDataSrcNum[0x4];
unsigned char MenuEditAnalyzeDataSrcListH[0x4];
unsigned char MenuEditAnalyzeDataSrcListH_Move[0x4];
unsigned char MenuEditAnalyzeDataSrcListLimmitNum[0x4];
unsigned char MenuAnalyzeData[0x4];
unsigned char GeoRequestBoardCheckPoint_P[0x8];
unsigned char Tex_Georama[0x4];
unsigned char GeoramaParts_DrawWaitCnt[0x4];
unsigned char GeoramaMesPosForceSetFlag[0x8];
unsigned char GeoramaMesMakeManner[0x8];
unsigned char GeoramaReqMakeLine[0x4];
unsigned char GeoramaReqMakeManner[0x4];
unsigned char GeoramaMesForceMakeFlag[0x4];
unsigned char GeoramaMesForceMakeFlag_PaintVer[0x4];
unsigned char GeoAnalyzeCheckPointScrlBarY[0x4];
unsigned char GeoAlpha_1199[0x4];
unsigned char init_1200[0x8];
unsigned char menu_georama_title_pos[0x8];
unsigned char at_1556[0x8];
unsigned char at_1829__2[0x8];
unsigned char cnt_2177[0x4];
unsigned char init_2178[0x4];
unsigned char Dmy_2314[0x4];
unsigned char init_2315[0x4];
unsigned char at_2434[0x8];
unsigned char dmychar_3207[0x4];
unsigned char init_3208[0x4];
unsigned char at_3260[0x4];
unsigned char at_3268[0x4];
unsigned char edparts_info_3580[0x4];
unsigned char init_3581[0x4];
unsigned char DestroyMaxNum_3584[0x4];
unsigned char init_3585[0x4];
unsigned char at_4043[0x8];
unsigned char at_4085[0x8];
unsigned char at_4124[0x8];
unsigned char at_4137[0x8];
unsigned char at_4150[0x8];
unsigned char RemovalMenuPtr[0x4];

// Uninitialised data (.bss)
unsigned char HouseChildPartInfo[0x60];
unsigned char PartsMakeOkTable[0x400];
unsigned char DownLoadMes[0x20];
unsigned char GeoramaPenkiNum[0x20];
unsigned char MenuGeoramaStack[0x30];
unsigned char MenuEditAnalyzeDataSrcListHTable[0x40];
unsigned char MenuEditAnalyzeDataSrc[0x80];
unsigned char GeoBoardListTitleTexRect[0x50];
unsigned char GeoBoardListTitlePutOffset[0x30];
unsigned char GeoRequestBoardCheckPoint[0x10];
unsigned char GeoramaMes[0x18];
unsigned char GeoramaMesMakeLine[0x18];
unsigned char GeoramaReqMsgFont[0xC0];
unsigned char GeoramaReqMsgFontGyouNum[0x30];
unsigned char GeoramaReqMsgTexH[0x60];
unsigned char GeoramaReqMsgFontDrawFlag[0x30];
unsigned char potti0[0x10];
unsigned char potti1[0x10];
unsigned char at_1826__2[0x10];
unsigned char at_1827__2[0x10];
unsigned char at_2443[0x40];
unsigned char at_2444[0x40];
unsigned char at_3303[0x30];
unsigned char at_3304[0x10];
