#include "common.h"

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", UniformityRand__Fff);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", RegularityRand__Fffi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", InitEffectParam__FP12EFFECT_PARAM);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __ct__7CEffectFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", Initialize__7CEffectFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", SetEffect__7CEffectFP12EFFECT_PARAM);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", Step__7CEffectFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", Draw__7CEffectFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __ct__11CEffectCtrlFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __dt__11CEffectCtrlFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", Ctrl__11CEffectCtrlFP7CEffecti);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", Initialize__11CEffectCtrlFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", Run__11CEffectCtrlFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", SetOrigin__11CEffectCtrlFPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __as__11CEffectCtrlFRC11CEffectCtrl);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __BUFFER_SIZE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __EFFECT_START__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __EFFECT_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __WAIT_FRAME__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __IMG_NAME__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __SIZE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __DIR__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __NUM__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __NUM_RAND__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __COUNT__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __CNT_RAND__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __REPEAT__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __REP_RAND__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __POS__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __POS_RAND__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __VELO__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __VELO_RAND__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __VELO_MUL__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __ACC__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __ACC_RAND__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __ACC_MUL__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __MOVE_TYPE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __MOVE_P1__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __MOVE_P1_RAND__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __MOVE_P2__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __MOVE_P2_RAND__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __SCALE_TYPE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __SCALE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __SCALE_RAND__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __SVELO__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __SVELO_RAND__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __SCALE_P1__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __SCALE_P1_RAND__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __SCALE_P2__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __SCALE_P2_RAND__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __ALPHA_BLEND__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __ALPHA_TYPE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __ALPHA__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __ALPHA_RAND__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __ALPHA_P1__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __ALPHA_P1_RAND__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __ALPHA_P2__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __ALPHA_P2_RAND__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __TEX_GET_RECT__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __TEX_GET_TYPE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __TEX_NAME__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __GRAVITY__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", __ct__14CEffectManagerFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", Initialize__14CEffectManagerFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", EntryEffCtrls__14CEffectManagerFP7CEffectiP11CEffectCtrli);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", SetEffectNums__14CEffectManagerFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", Ctrl__14CEffectManagerFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", Step__14CEffectManagerFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", Draw__14CEffectManagerFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", Run__14CEffectManagerFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", Stop__14CEffectManagerFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", EnterEffectCtrl__14CEffectManagerF11CEffectCtrlPc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", GetBufferNums__14CEffectManagerFPciPiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", Load__14CEffectManagerFPci);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/effect", SetOrigin__14CEffectManagerFPf);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", effm_tag);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_383);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_382__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_566__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_567);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_568);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_569);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_570);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_571__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_572);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_573);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_574__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_575);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_576);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_577);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_578);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_579);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_580);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_581);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_582);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_583__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_584);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_585);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_586__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_587__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_588__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_589__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_590);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_591);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_592);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_593);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_594);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_595);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_596);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_597);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_598);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_599);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_600);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_601);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_602);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_603);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_604);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_605);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_606);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_607);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_608);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_609);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_610);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_611__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_612__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/effect", at_848__2);

// Small uninitialised data (.sbss)
unsigned char g_tmp_effm[0x4];
unsigned char g_tmp_effc[0x4];
unsigned char g_eff_entry_flag[0x4];

// Uninitialised data (.bss)
unsigned char g_tmp_eff_name[0x20];
