#include "common.h"

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", GetFishParam__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", EsaInit__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", ReplayPrevBGM__FP6CScene);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", LoadExMotionBG__FP11SubGameInfoP1);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", LoadExMotionStep__FP11SubGameInfoP9mgCMemory);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", SetNextMode__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", ExitFishing__FP6CScene);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", sgInitFishing__FP11SubGameInfo);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", sgRestartFishing__FP11SubGameInfo);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", InitDataLoading__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", switch_thread__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", CreateLoadThread__FP9mgCMemory);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", StepLoadThread__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", DeleteLoadThread__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", StepDataLoading__FPv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", sgBreakFishing__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", sgExitFishing__FP11SubGameInfo);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", sgLoopFishing__FP11SubGameInfo);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", sgLoopFishing2__FP11SubGameInfo);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", sgDrawFishing__FP11SubGameInfo);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", DrawNumber__FP11mgCDrawPrimiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", sgSystemDrawFishing__FP11SubGameInfo);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", CharaControl__FP6CSceneP11CPadControl__2);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", InitSelectCastingPoint__FP6CScene);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", EndSelectCastingPoint__FP6CScene);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", SelectCastingPoint__FP6CSceneP11CPadControl);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", DrawHamon__FPff);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", DrawSplash__FPff);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", GetMotionCount__FP11CCharacter2Pciii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", InitCasting__FP6CScene);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", CastingLoop__FP6CSceneP11CPadControl);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", InitUkiWait__FP6CScene);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", ResetUkiCamera__FP14CCameraControl);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", UkiWaitLoop__FP6CSceneP11CPadControl);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", InitBattle__FP6CScene);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", BattleLoop__FP6CSceneP11CPadControl);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", GetFishDist__FP6CScene);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", DeleteEsa__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", InitFalse__FP6CScene);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", FalseLoop__FP6CSceneP11CPadControl);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", InitSuccess__FP6CScene);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", SuccessLoop__FP6CSceneP11CPadControl);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", CheckFishing__FPfP6CCPolyi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", CheckCasting__FP6CScenePfPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", GetRandamNumber__Ffff);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", GetUkiWaitTime__FP9FISH_DATAP6CScenePfii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", GetUkiPokeTime__FP9FISH_DATA);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", GetUkiPullTime__FP9FISH_DATA);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", FishLoadBG__FP9FISH_DATAP1);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", LineTensionStep__FP9FISH_DATAi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", GetAppearFish__FiPfP10FISH_PLACEi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", SetFishPlace__14FISH_PLACE_MAPFP10FISH_PLACEii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", CheckFishPlace__14FISH_PLACE_MAPFPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", fpFISH_MAP_NUM__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", fpFISH_MAP__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", fpFISH_PLACE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", fpFISH__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", fpFISH_MAP_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", LoadFishPlaceData__FPciP9mgCMemory);

// Static initialiser (.init)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/fishing", __sinit_fishing_cpp);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", lure_file);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", EsaInfo);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", FishParam);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_993__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1430__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1490__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1491__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1536);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1631__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", tag__8);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_832__6);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_833__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_834__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_835__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_845__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_846__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_847__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_848__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_849__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_850__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_851__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_852__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_853__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_854__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_855__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_856__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_857__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_858__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_859__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_860__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_861__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_862__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_863__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_864__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_865__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_866__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_867__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_868__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_869__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_870__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_871__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_872__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_873__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_874__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_875__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_876__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_877__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_878__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_879__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_880__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_881__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_882__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_917__6);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_932__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_979__6);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_980__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1058__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1304__8);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1305__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1306__6);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1307__6);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1308__6);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1309__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1310__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1311__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1312__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1313__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1314__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1315__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1316__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1397__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1399__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1398__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1424__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1442__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1443__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1508__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1509__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1576__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1577);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1683__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1691__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1722);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1723__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1749__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1920);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1921);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1922);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_2057);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_2058);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_2059);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_2060);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_2099);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_2127__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_2197__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_2198__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_2272);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_2461);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_2670);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_2671);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_2672);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_2673);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_2674__2);

// Static initialiser table (.ctor)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", D_0037B074);

// Small initialised data (.sdata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/fishing", at_1444__3);

// Small uninitialised data (.sbss)
unsigned char EffectMan[0x4];
unsigned char FishSnd[0x4];
unsigned char FanSnd[0x4];
unsigned char UkiRod[0x4];
unsigned char LureRod[0x4];
unsigned char Uki[0x4];
unsigned char Lure[0x4];
unsigned char Hari[0x4];
unsigned char FishingTexb[0x4];
unsigned char FishTexb[0x4];
unsigned char SystemTexb[0x4];
unsigned char EsaTexb[0x4];
unsigned char MainChara[0x4];
unsigned char FishChara[0x4];
unsigned char EsaChara[0x4];
unsigned char CursorChara[0x8];
unsigned char RodHand[0x4];
unsigned char UkiFrame[0x4];
unsigned char LureFrame[0x4];
unsigned char HariFrame[0x4];
unsigned char oldPadRx[0x4];
unsigned char oldPadRy[0x4];
unsigned char CastOKFlag[0x4];
unsigned char RunEventNo[0x4];
unsigned char MardanEventMap[0x4];
unsigned char MardanEventPlace[0x4];
unsigned char CharaMode[0x4];
unsigned char NextCharaMode[0x4];
unsigned char fgLoopMode[0x4];
unsigned char fgLoopStep[0x4];
unsigned char fgLoopCnt[0x4];
unsigned char RodNo[0x4];
unsigned char EsaNo[0x4];
unsigned char LocalEsaNo[0x4];
unsigned char FavoredEsa[0x4];
unsigned char LureNo[0x4];
unsigned char CastDist[0x4];
unsigned char CastDistSizeRate[0x4];
unsigned char UkiMode[0x4];
unsigned char UkiModeCnt[0x4];
unsigned char RodActionPoint[0x4];
unsigned char ReadBuffer[0x4];
unsigned char LoadFishFlag[0x4];
unsigned char LoadExMotionFlag[0x4];
unsigned char LineTension[0x4];
unsigned char addLineTension[0x4];
unsigned char MinLineTension[0x4];
unsigned char LineMaxLen[0x4];
unsigned char LineMinLen[0x4];
unsigned char FishMaxLen[0x4];
unsigned char FishMinLen[0x4];
unsigned char BattleCount[0x4];
unsigned char WindReel[0x4];
unsigned char RodStatus[0x4];
unsigned char RodStatusCnt[0x4];
unsigned char ActionCount[0x4];
unsigned char ActionDecCount[0x4];
unsigned char RetCode[0x4];
unsigned char DrawHit[0x4];
unsigned char DrawCongra[0x4];
unsigned char BgmReadFlag[0x4];
unsigned char BattleBgmCnt[0x4];
unsigned char ex_mtn_buff[0x4];
unsigned char stack_size[0x4];
unsigned char ThreadStack__2[0x4];
unsigned char TheadID__2[0x4];
unsigned char ThreadRunning[0x4];
unsigned char step_end_flag[0x4];
unsigned char CastStep[0x4];
unsigned char CastCount[0x4];
unsigned char CastTime[0x4];
unsigned char CastMotionCnt[0x4];
unsigned char RodActFlag[0x4];
unsigned char UkiCameraFlag[0x4];
unsigned char UkiCamOldRot[0x4];
unsigned char hamon_count_1798[0x4];
unsigned char init_1799[0x4];
unsigned char boze_cnt_1801[0x4];
unsigned char pull_uki_cnt_1808[0x4];
unsigned char act_count_1838[0x4];
unsigned char charge_point_1839[0x4];
unsigned char act_interval_1840[0x4];
unsigned char snd_cnt_1960[0x4];
unsigned char init_1961[0x4];
unsigned char FalseStep[0x4];
unsigned char FalseStep2[0x4];
unsigned char FalseMotionCount[0x4];
unsigned char GetItemRet[0x4];
unsigned char FishMesNo[0x4];
unsigned char FishFontH[0x4];
unsigned char font_h_2216[0x4];
unsigned char init_2217[0x4];
unsigned char snd_cnt_2495[0x4];
unsigned char init_2496[0x4];
unsigned char FishPlaceMapNum[0x4];
unsigned char FishPlaceMap[0x4];
unsigned char fpStack[0x4];
unsigned char fpNowFishPlaceMap[0x4];
unsigned char fpNowFishPlaceMapNum[0x4];

// Uninitialised data (.bss)
unsigned char EsaStack[0x30];
unsigned char SndStack[0x30];
unsigned char CameraInfo[0x1F0];
unsigned char UkiCameraInfo[0x1F0];
unsigned char CastPoint[0x10];
unsigned char CastPointCur[0x10];
unsigned char RodData[0x20];
unsigned char FishData[0x30];
unsigned char MotionBuff[0x30];
unsigned char ReadStack[0x30];
unsigned char FishingBuff__2[0x30];
unsigned char FishStack[0x30];
unsigned char BgmStatus[0x20];
unsigned char at_1681__2[0x10];
unsigned char at_1689[0x10];
