#include "common.h"

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetInventUserDataPtr__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", Init_USER_PICTURE_INFO__FP17USER_PICTURE_INFO);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", Copy_USER_PICTURE_INFO__FP17USER_PICTURE_INFOP17USER_PICTURE_INFO);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", PictureSeiton__FP17USER_PICTURE_INFOPci);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", AttachPictTex__FiPP10mgCTextureP17USER_PICTURE_INFOi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", CheckPhotoDataNoNeed__FP17USER_PICTURE_INFOiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", IsTakePhoto__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", Initialize__13CDC2AlbumDataFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", RelateAlbumPicData__13CDC2AlbumDataFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", DeletePhotoData__13CDC2AlbumDataFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetAlbumPhotoInfo__13CDC2AlbumDataFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", Initialize__15CInventUserDataFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", ResetAddress__15CInventUserDataFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", PhotoCheckEnd__15CInventUserDataFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetPhotoInfo__15CInventUserDataFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetPhototWorkAdr__15CInventUserDataFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", IsPhotoSpace__15CInventUserDataFPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", DeletePhotoData__15CInventUserDataFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", CheckNetaFlag__15CInventUserDataFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetNetaID__15CInventUserDataFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", SetNetaFlag__15CInventUserDataFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", CheckNetaFlagHavePhoto__15CInventUserDataFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", CountNeta__15CInventUserDataFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", CountScoop__15CInventUserDataFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", AddShutterNum__15CInventUserDataFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetNowHavePictureNum__15CInventUserDataFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetPictureNum__15CInventUserDataFPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", CalcPhotoExp__15CInventUserDataFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", LevelCheck__15CInventUserDataFP17USER_PICTURE_INFO);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetLevel__15CInventUserDataFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", SetCreateItemFlag__15CInventUserDataFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetCreateItemID__15CInventUserDataFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", IsAlreadyCreatedItem__15CInventUserDataFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetHatsumeiNum__15CInventUserDataFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", TranslateInventUserData__FP15CInventUserDataP15CInventUserData);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetScoopDataTable__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetScoopDataTableIndex__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", InitScoopString__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", _SCOOP_STR__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", AnalyzeScoopString__FP9mgCMemoryPci);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetScoopInfo__17CScoopDataManagerFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", SetViewFlag__17CScoopDataManagerFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", KnowScoop__17CScoopDataManagerFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", CheckScoop__17CScoopDataManagerFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetScoopTotal__17CScoopDataManagerFPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", _PIC_INFO__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", _PIC_NAME__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", LoadFilePictureName__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetPhotoName__FP17USER_PICTURE_INFO);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetPhotoNameStr__FiPc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetPhotoNameCheck__FP17USER_PICTURE_INFO);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", CheckPhotoFlag__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetInventDataInfoByItemID__17CInventDataManageFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", CheckInventEnable__17CInventDataManageFPiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", HowMuchZairyouMakeItem__17CInventDataManageFiiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", DeleteUserUsedItem__17CInventDataManageFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", CheckMakeItem__17CInventDataManageFiiP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", _INVENT_DATATABLESET__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", _INVENT_DATASET__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", LoadAnalyzeInventFile__17CInventDataManageFPci);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", CheckInventItem__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", CheckItemTable__FiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", CheckInventPhoto__Fii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", InitPhotoNetaBoardToAlbum__11CMenuInventFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", CheckRecoverPhotoNum__11CMenuInventFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", AttachFormInfo__11CMenuInventFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", LoadCharaCheck__11CMenuInventFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetNowSelectedPictInfo__11CMenuInventFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetPhotoInfoFromMode__11CMenuInventFPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", InitNetaCircle__11CMenuInventFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", SetNetaCircle__11CMenuInventFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", CancelNetaCircle__11CMenuInventFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetNowSelectNetaID__11CMenuInventFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", SelectedNetaPhotoAlready__11CMenuInventFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", SelectedNetaMemoListAlready__11CMenuInventFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", UpdataRecordBoard__11CMenuInventFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", PrepareNextMode__11CMenuInventFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", SearchNowPosItemExist__11CMenuInventFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", CreateModeSwapForm__11CMenuInventFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GradationSet__11CMenuInventFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GradationStep__11CMenuInventFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", InitEnd__11CMenuInventFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", ExitEnd__11CMenuInventFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", EnterDataMenu__11CMenuInventFPUc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", ItemCmdAfter__11CMenuInventFiP16ITEMCMD_RET_PARA);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", IsCreateObject__11CMenuInventFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", CalcMakeBrd__11CMenuInventFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", EnableSelectMaxCardList__11CMenuInventFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", CalcCursorPosition__11CMenuInventFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", IsMakeObject__11CMenuInventFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", CalcTex__11CMenuInventFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", BootExtendCommand__11CMenuInventFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", IsAskExtend__11CMenuInventFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", PhotoNetaEnter__11CMenuInventFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", __ct__9CStarDustFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", IsAccessAlbum__11CMenuInventFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetNetaBoardCursorPosition__11CMenuInventFiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", GetNetaMemoCursorPosition__11CMenuInventFiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", neta_sort__FiiiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", UpdataNetaMemoStr__11CMenuInventFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", MakeMsgNetaName__FP7CDC2MesP16CMenuPosDataFormP17USER_PICTURE_INFOPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", MenuInventCreateCardDraw__FRiPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", PictureDraw__FP10mgCTextureP17USER_PICTURE_INFOfffiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", PictureMemoOne__Fffi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", PictureDraw__FRi9mgRect_f_ifPUc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", MenuInventPictureBoardDraw__FPfRii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", MenuInventAlbumPictureDraw__FPfRi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", MenuInventNetaMemoDraw__FPfRi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", MenuInventInit__FP9mgCMemoryPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", NextDifferentMode__11CMenuInventFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", MenuInventDebugKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", MenuInventDebugDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", MenuInventPushKey__Fii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", MenuInventKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", MenuInventDraw__Fv);

// Static initialiser (.init)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/inventmn", __sinit_inventmn_cpp);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", scoop_table);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", menu_scoop_str_tag);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", pic_tag);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", addstringtable_1722);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", invent_teigi_func);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2455);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", invent_color_tbl);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2639);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", Tb_2819);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", D_003532DF);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", jp_conv_lentbl_2835);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2913);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", eff_light_2927);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", wavname_2960);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3201);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", wakutype_3203);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3306);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", modecmdtbl_3636);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", gaiji_table_4737);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", tbl_4782);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5173);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", nextmodetbl_5183);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", overcode_album_5225);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", digit_tbl3_5641);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", NewComer_5648);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_1046__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_1537);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_1655__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_1656__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_1664);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_1723);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_1724__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_1725);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_1947);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_1948);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2005);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2124__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2125__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2126__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2127__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2128__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2129__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2130__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2131__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2132__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2133__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2134__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2135);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2136__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2137);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2138);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2139);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2140);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2141);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2142);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2143);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2144);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2145);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2146__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2147);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2148);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2149);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2150);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2151);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2152);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2244);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2245);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2246);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2247);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2248);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2249);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2250);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2251);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2252);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2253);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2313);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2368__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2369__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2395__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2396__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2520);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2521);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2522);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2523);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2524);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2525);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2526);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2527);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2528);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2543__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2544);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2545);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2546);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2712);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2713__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2720__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2732__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2733__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2734__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2735__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2736);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2737);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2820);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2821);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2848);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2849);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2929);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2930);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2952__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2953__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2961);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2962);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2963);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3113);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3114);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3115);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3116);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3117);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3118);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3119);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3120);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3121);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3122);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3123);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3124);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3125);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3126);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3127);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3128);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3129);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3130);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3131);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3132);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3133);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3134);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3135);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3138);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3257);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3258);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3259);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3260__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3261);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3262__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3263__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3264);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3348__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3349__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3350__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3351);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3352);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3353);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3621);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3622);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3623);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3624);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3625);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3626);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3627);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3628);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3629);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3630);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3631);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3632);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3858);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3859);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3860);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3861);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3862);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3863__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3864__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3865__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3866__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3867__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3868__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3869);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3871);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3870);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3932);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3933);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3934);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3935);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_3936);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4354);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4355);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4356);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4357);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4358);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4359);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4360);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4361);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4362);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4363);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4364);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4365);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4366);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4367__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4368__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4369);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4370);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4371);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4372);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4373);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4374);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4375);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4376);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4377);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4378);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4379);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4380);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4775);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5011);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5012);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5013);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5014);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5015);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5016);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5066);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5067);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5068);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5153);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5154);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5155);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5156);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5550);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5551);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5552);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5553);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5554);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5555);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5556);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5557);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5558);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5559);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5562);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5560);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5649);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5650);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5651);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5652);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5653);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5654);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5742);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5743);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5744);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5745);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5746);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_5747);

// Static initialiser table (.ctor)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", D_0037B020);

// Virtual tables (.vtables)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", __vt__11CMenuInvent);

// Small initialised data (.sdata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", invent_grade_fff);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_2562);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", gobitbl_2847);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", sndtimetbl_2868);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", getfilename_2928);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", sndfileName_2951);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", convtbl_3726);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4470);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", at_4494);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", maxtbl_5171);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", viewnum_5172);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", maxtbl_album_5223);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/inventmn", viewnum_album_5224);

// Small uninitialised data (.sbss)
unsigned char debug_invent_successflag[0x4];
unsigned char InventUserDataPtr[0x4];
unsigned char InventAlbumPtr[0x4];
unsigned char InventManagePt[0x4];
unsigned char MCManagerPtr[0x4];
unsigned char pict_seiton_case[0x4];
unsigned char scoop_str_stack[0x4];
unsigned char PicNameStack[0x4];
unsigned char pic_name_info_top[0x4];
unsigned char pic_name_info_num[0x4];
unsigned char pic_name_info_num_count[0x4];
unsigned char at_1788__2[0x4];
unsigned char inventSpiDataTblTop[0x4];
unsigned char invent_num_counter[0x4];
unsigned char at_1965[0x4];
unsigned char NetaMemoStrNum[0x4];
unsigned char Tex_Hatsumei[0x4];
unsigned char InventSubDataReadBGInfo[0x8];
unsigned char at_3202[0x8];
unsigned char at_3317[0x8];
unsigned char at_3363[0x8];
unsigned char at_3379[0x8];
unsigned char at_3509[0x8];
unsigned char menu_invent_command_info_pict_info[0x4];
unsigned char menu_invent_command_info_ptr[0x4];
unsigned char menu_invent_command_info_move_album_Space_info[0x4];
unsigned char menu_invent_command_info_move_album_Space_pos[0x4];
unsigned char at_3739[0x8];
unsigned char at_3765[0x8];
unsigned char InventInNetaEffectFlag[0x4];
unsigned char InventInNetaEffectNum[0x4];
unsigned char InventInNetaEffectNum4[0x4];
unsigned char InventInNetaEffect[0x4];
unsigned char ActiveSlot_3949[0x4];
unsigned char init_3950[0x4];
unsigned char CMenuInventPt[0x8];
unsigned char at_4493[0x8];
unsigned char at_4638[0x8];
unsigned char InventManageMan[0x8];
unsigned char debug_invent_select[0x4];
unsigned char at_5448[0x4];
unsigned char at_5457[0x8];
unsigned char at_5642[0x8];

// Uninitialised data (.bss)
unsigned char MenuInventStack[0x30];
unsigned char MenuInventCharaStack[0x30];
unsigned char MenuInventMCStack[0x30];
unsigned char pic_name_text_buff_1660[0x2480];
unsigned char temp_1728[0x30];
unsigned char InventTeigiStack[0x30];
unsigned char NetaMemoStr[0x800];
unsigned char NetaMemoID[0x400];
unsigned char rec_board_offset_xtbl[0x28];
unsigned char at_2776[0x18];
unsigned char at_5460[0x18];
unsigned char at_5474[0x18];
