#include "common.h"

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetDebugFont__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetCaptureMode__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetSystemSndID__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetMainScene__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetSaveData__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetSubGameSaveData__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", InitSaveData__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetVramTopAddress__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetMainStack__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", NextLoop__Fi13INIT_LOOP_ARG);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetNowLoopNo__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetNowInitArg__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", cat_start__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", cat_end__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", SetTextureTable__FiiP9mgCMemory);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", InitPadTable__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", VSyncCallBack__Fi__3);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", PlayTimeCount__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetPlayTimeCountFlag__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", LanguageChange__FiP1);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", MainLoop__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", MenuInit__F13INIT_LOOP_ARG);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", MenuLoop__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", MenuExit__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", InitEventSelect__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", EventSelect__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetFontTexture__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", LoadFontTexture__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", ReLoadFontTexture__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", demQuit__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", demoQuitTimeOut__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", demoAttractInterrupted__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", demoAttractComplete__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", FadeOutForE3__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", TimeLimitCheck__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", InitPauseMenu__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", PauseMenu__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", LoadGameConfig__FPc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcMAP_NO__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcPROGRESS__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcBIT_FLAG_ON__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcBIT_FLAG_OFF__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcSTART_EVENT__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcGEO_COMPLETE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcGEO_DEBUG__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcITEM_SET__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcGET_ITEM__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcGET_N_ITEM__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcEQUIP__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcDEFENSE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcHP__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcALL_GEO_PARTS__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcPARAM_DRAW__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcOPTION__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcMONICA__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcSTEVE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcMONSTER__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcPARTY__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcACTIVE_CHARA__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", __ct__16CUserDataManagerFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", __ct__9CEditDataFv);

// Static initialiser (.init)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", __sinit_mainloop_cpp);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", LoopInit);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", LoopMain);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", LoopExit);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", pad_table);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", analog_table);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", SelectArg);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", menu_1281);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1305);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1310);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1311);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", menu_sel_1452);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1456);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", menu_1457);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", tag__3);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1212);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1213);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1214);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1215);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1216);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1282__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1283__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1284__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1285);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1286);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1287);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1288);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1289);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1290);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1291);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1292);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1293);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1294);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1295);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1296);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1297);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1298);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1299);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1300);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1301);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1302);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1303);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1304);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1306);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1307);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1308);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1309);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1315);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1316);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1408);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1409);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1410);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1411);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1412);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1413);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1414);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1415);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1416);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1417);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1418);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1453);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1454);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1455);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1458);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1459);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1460);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1461);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1462);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1463);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1464);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1465);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1466);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1467);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1468);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1472);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1473);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1582);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1583);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1584);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1585);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1586);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1587);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1588);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1589);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1590);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1591);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1592);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1593);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1594);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1596);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1595);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1654);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1655);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1656);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1657);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1823);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1824);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1825);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1826);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1827);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1828);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1829);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1830);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1831);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1832);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1833);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1834);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1835);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1836);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1837);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1838);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1839);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1840);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1841);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1842);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1843);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1844);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1856);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_2082);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_2083);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_2084);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_2085);

// Static initialiser table (.ctor)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", D_0037AFF8);

// Small initialised data (.sdata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", MainThreadPriority);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_973);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_974);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1317__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1474);

// Small uninitialised data (.sbss)
unsigned char read_buffer[0x4];
unsigned char SystemSND_ID[0x4];
unsigned char DebugFlag[0x4];
unsigned char DefStartEventNo[0x4];
unsigned char LanguageCode[0x4];
unsigned char OmakeFlag[0x4];
unsigned char MasterDebugCode[0x4];
unsigned char LoopNo[0x4];
unsigned char NextLoopNo[0x4];
unsigned char PrevLoopNo[0x4];
unsigned char CaptureMode[0x4];
unsigned char CaptureScreen[0x4];
unsigned char CSnd[0x4];
unsigned char ActiveSaveData[0x4];
unsigned char SubGameSaveData[0x4];
unsigned char PlayTimeCountFlag[0x4];
unsigned char pmeter_flag_1037[0x4];
unsigned char init_1038[0x4];
unsigned char pause_1108[0x4];
unsigned char init_1109[0x4];
unsigned char menu_mode[0x4];
unsigned char init_1225[0x4];
unsigned char init_1228[0x4];
unsigned char init_1231[0x4];
unsigned char init_1234[0x4];
unsigned char select_1312[0x4];
unsigned char init_1313[0x4];
unsigned char event_view[0x4];
unsigned char future_sel[0x4];
unsigned char hdd_sel[0x4];
unsigned char select_1469[0x4];
unsigned char init_1470[0x4];
unsigned char FontTex[0x4];
unsigned char FontDataAdr[0x4];
unsigned char BlackFade[0x4];
unsigned char BlackFade2[0x4];
unsigned char exit_start[0x4];
unsigned char PauseSel[0x4];
unsigned char PauseMenuMode[0x4];

// Uninitialised data (.bss)
unsigned char GamePad__2[0x480];
unsigned char PadCtrl[0x510];
unsigned char DebugInfo[0x20];
unsigned char Font[0xC0];
unsigned char InitArg[0x50];
unsigned char NextInitArg[0x50];
unsigned char PrevInitArg[0x50];
unsigned char main_buffer[0x1A00000];
unsigned char MainBuffer[0x30];
unsigned char MainScene[0x10550];
unsigned char SystemSeBuff[0x1900];
unsigned char SystemSeStack[0x30];
unsigned char InfoBuff[0x13880];
unsigned char InfoStack[0x30];
unsigned char SaveData[0x65930];
unsigned char vu_prog_1048[0x40];
unsigned char MenuBuffer[0x30];
unsigned char buf0_1224[0x30];
unsigned char buf1_1227[0x30];
unsigned char dbuf0_1230[0x30];
unsigned char dbuf1_1233[0x30];
unsigned char at_1529[0x40];
unsigned char font_buff[0xD000];
unsigned char PauseMes[0x2960];
