#include "common.h"
#include "mainloop.hpp"
#include <cstring>
#include <cstdio>

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetDebugFont__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetCaptureMode__Fv);
s32 GetSystemSndID(void) {
    return SystemSND_ID;
}
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetMainScene__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetSaveData__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetSubGameSaveData__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", InitSaveData__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetVramTopAddress__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetMainStack__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", NextLoop__Fi13INIT_LOOP_ARG);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetNowLoopNo__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetNowInitArg__Fv);
void cat_start() {}
void cat_end() {}
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", SetTextureTable__FiiP9mgCMemory);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", InitPadTable__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", VSyncCallBack__Fi__3);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", PlayTimeCount__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetPlayTimeCountFlag__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", LanguageChange__FiP1);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", MainLoop__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", MenuInit__F13INIT_LOOP_ARG);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", MenuLoop__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", MenuExit__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", InitEventSelect__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", EventSelect__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", GetFontTexture__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", LoadFontTexture__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", ReLoadFontTexture__Fi);
void demQuit() {}
void demoQuitTimeOut() {}
void demoAttractInterrupted() {}
void demoAttractComplete() {}
void FadeOutForE3() {}
int TimeLimitCheck() { return 0; }
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", InitPauseMenu__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", PauseMenu__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", LoadGameConfig__FPc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcMAP_NO__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcPROGRESS__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcBIT_FLAG_ON__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcBIT_FLAG_OFF__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcSTART_EVENT__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcGEO_COMPLETE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcGEO_DEBUG__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcITEM_SET__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcGET_ITEM__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcGET_N_ITEM__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcEQUIP__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcDEFENSE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcHP__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcALL_GEO_PARTS__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcPARAM_DRAW__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcOPTION__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcMONICA__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcSTEVE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcMONSTER__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcPARTY__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", gcACTIVE_CHARA__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", __ct__16CUserDataManagerFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", __ct__9CEditDataFv);

// Static initialiser (.init)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mainloop", __sinit_mainloop_cpp);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", LoopInit__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", LoopMain__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", LoopExit__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", pad_table__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", analog_table__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", SelectArg__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", menu_1281__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1305__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1310__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1311__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", menu_sel_1452__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1456__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", menu_1457__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", tag__3__DATA);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1212__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1213__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1214__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1215__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1216__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1282__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1283__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1284__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1285__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1286__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1287__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1288__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1289__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1290__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1291__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1292__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1293__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1294__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1295__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1296__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1297__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1298__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1299__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1300__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1301__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1302__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1303__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1304__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1306__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1307__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1308__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1309__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1315__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1316__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1408__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1409__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1410__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1411__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1412__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1413__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1414__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1415__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1416__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1417__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1418__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1453__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1454__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1455__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1458__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1459__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1460__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1461__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1462__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1463__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1464__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1465__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1466__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1467__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1468__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1472__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1473__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1582__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1583__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1584__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1585__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1586__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1587__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1588__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1589__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1590__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1591__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1592__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1593__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1594__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1596__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1595__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1654__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1655__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1656__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1657__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1823__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1824__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1825__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1826__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1827__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1828__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1829__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1830__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1831__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1832__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1833__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1834__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1835__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1836__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1837__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1838__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1839__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1840__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1841__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1842__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1843__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1844__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1856__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_2082__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_2083__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_2084__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_2085__DATA);

// Static initialiser table (.ctor)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", D_0037AFF8__DATA);

// Small initialised data (.sdata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", MainThreadPriority__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_973__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_974__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1317__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mainloop", at_1474__DATA);

// Small uninitialised data (.sbss)
INCLUDE_BSS(read_buffer, 0x4);
INCLUDE_BSS(SystemSND_ID, 0x4);
INCLUDE_BSS(DebugFlag, 0x4);
INCLUDE_BSS(DefStartEventNo, 0x4);
INCLUDE_BSS(LanguageCode, 0x4);
INCLUDE_BSS(OmakeFlag, 0x4);
INCLUDE_BSS(MasterDebugCode, 0x4);
INCLUDE_BSS(LoopNo, 0x4);
INCLUDE_BSS(NextLoopNo, 0x4);
INCLUDE_BSS(PrevLoopNo, 0x4);
INCLUDE_BSS(CaptureMode, 0x4);
INCLUDE_BSS(CaptureScreen, 0x4);
INCLUDE_BSS(CSnd, 0x4);
INCLUDE_BSS(ActiveSaveData, 0x4);
INCLUDE_BSS(SubGameSaveData, 0x4);
INCLUDE_BSS(PlayTimeCountFlag, 0x4);
INCLUDE_BSS(pmeter_flag_1037, 0x4);
INCLUDE_BSS(init_1038, 0x4);
INCLUDE_BSS(pause_1108, 0x4);
INCLUDE_BSS(init_1109, 0x4);
INCLUDE_BSS(menu_mode, 0x4);
INCLUDE_BSS(init_1225, 0x4);
INCLUDE_BSS(init_1228, 0x4);
INCLUDE_BSS(init_1231, 0x4);
INCLUDE_BSS(init_1234, 0x4);
INCLUDE_BSS(select_1312, 0x4);
INCLUDE_BSS(init_1313, 0x4);
INCLUDE_BSS(event_view, 0x4);
INCLUDE_BSS(future_sel, 0x4);
INCLUDE_BSS(hdd_sel, 0x4);
INCLUDE_BSS(select_1469, 0x4);
INCLUDE_BSS(init_1470, 0x4);
INCLUDE_BSS(FontTex, 0x4);
INCLUDE_BSS(FontDataAdr, 0x4);
INCLUDE_BSS(BlackFade, 0x4);
INCLUDE_BSS(BlackFade2, 0x4);
INCLUDE_BSS(exit_start, 0x4);
INCLUDE_BSS(PauseSel, 0x4);
INCLUDE_BSS(PauseMenuMode, 0x4);

// Uninitialised data (.bss)
INCLUDE_BSS(GamePad__2, 0x480);
INCLUDE_BSS(PadCtrl, 0x510);
INCLUDE_BSS(DebugInfo, 0x20);
INCLUDE_BSS(Font, 0xC0);
INCLUDE_BSS(InitArg, 0x50);
INCLUDE_BSS(NextInitArg, 0x50);
INCLUDE_BSS(PrevInitArg, 0x50);
INCLUDE_BSS(main_buffer, 0x1A00000);
INCLUDE_BSS(MainBuffer, 0x30);
INCLUDE_BSS(MainScene, 0x10550);
INCLUDE_BSS(SystemSeBuff, 0x1900);
INCLUDE_BSS(SystemSeStack, 0x30);
INCLUDE_BSS(InfoBuff, 0x13880);
INCLUDE_BSS(InfoStack, 0x30);
INCLUDE_BSS(SaveData, 0x65930);
INCLUDE_BSS(vu_prog_1048, 0x40);
INCLUDE_BSS(MenuBuffer, 0x30);
INCLUDE_BSS(buf0_1224, 0x30);
INCLUDE_BSS(buf1_1227, 0x30);
INCLUDE_BSS(dbuf0_1230, 0x30);
INCLUDE_BSS(dbuf1_1233, 0x30);
INCLUDE_BSS(at_1529, 0x40);
INCLUDE_BSS(font_buff, 0xD000);
INCLUDE_BSS(PauseMes, 0x2960);
