#include "common.h"

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", GetTimeBand__Ff);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", GetNowTime__4CMapFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", GetNowTimeBand__4CMapFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", GetNowTimeLightBand__4CMapFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", GetLightingRatio__4CMapFPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", GetLightingFlareRatio__4CMapFPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", GetLightingSunRatio__4CMapFPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", GetTimeLightingRatio__4CMapFPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", GetSunPoint__4CMapFPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", GetLightNoTime__4CMapFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", GetTimeEnable__4CMapFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", GetLightInfo__4CMapFP16CMapLightingInfo);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", __as__16CMapLightingInfoFRC16CMapLightingInfo);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", GetLightingInfo__4CMapFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", GetActiveLightNo__4CMapFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", GetActiveLightNo__8CMapInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", GetLightInfo__4CMapFP16CMapLightingInfoPfi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mgAbs__Ff);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapDummy__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", IsAddMode__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapPARTS__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", pGetData__17CList_9CMapParts_Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", __ct__17CList_9CMapParts_Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", Initialize__17CList_9CMapParts_Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", __ct__7CObjectFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", __ct__9mgCObjectFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", algn16_size__FUi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapFAR_CLIP__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapLIGHT_FLAG__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapMOVE_FLAG__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapLOD_START__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", SetLODDist__9CMapPartsFPfi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapLOD_BLEND__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", SetLODBlend__9CMapPartsFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapLOD_PIECE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", GetLODBlend__9CMapPartsFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapLOD_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapPIECE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", SetName__9CMapPieceFPc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", pGetData__17CList_9CMapPiece_Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", __ct__17CList_9CMapPiece_Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", Initialize__17CList_9CMapPiece_Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", __ct__9CMapPieceFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", __ct__12CObjectFrameFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapPIECE_NAME__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapPIECE_POS__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapPIECE_ROT__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapPIECE_SCALE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapPIECE_MATERIAL_START__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", SetMaterial__9CMapPieceFP13PieceMateriali);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", __ct__13PieceMaterialFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", Initialize__13PieceMaterialFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapPIECE_MATERIAL__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", GetMaterial__8mgCFrameFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", GetFrame__12CObjectFrameFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapPIECE_MATERIAL_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapPIECE_COL_TYPE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapPIECE_TIME__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapPIECE_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapPARTS_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapMAP_PARTS__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapMAP_FAR_CLIP__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapPARTS_NAME__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapPARTS_GROUP__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapPARTS_POS__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapPARTS_ROT__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapPARTS_SCALE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapMAP_PARTS_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", map_MAP_INFO_TOP__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapCAMERA_INFO__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", __ct__11CCameraInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", __ct__15CCameraDrawInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", Initialize__15CCameraDrawInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapFIX_CAMERA__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapFIX_CAMERA_POS__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapFIX_CAMERA_POS2__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapFIX_CAMERA_OFF_GROUP__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapFIX_CAMERA_RECT__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", SetCollision__9CColFrameFP10CCollision);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", __ct__10CCollisionFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapFIX_CAMERA_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapCAMERA_INFO_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapFUNC_POINT__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapFUNC_DATA__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapFUNC_NAME__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapFUNC_FLAG__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapFUNC_FIRE_DATA__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapFUNC_PLIGHT_DATA__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapFUNC_ANIME_DATA__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapFUNC_INVENT_DATA__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapFUNC_EVENT_DATA__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapFUNC_SOUND_DATA__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapFUNC_EFFECT_NAME__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", SetBound__8mgCFrameFPQ28mgCFrame9BoundInfo);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapFUNC_POS__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", SetScale__10CFuncPointFPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", SetRotation__10CFuncPointFPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", SetPosition__10CFuncPointFPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapFUNC_DATA_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", mapFUNC_POINT_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", LoadMapFile__4CMapFPciP9mgCMemoryi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", SetPieceLoadSkip__4CMapFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", cfgDRAW_OFF_RECT__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", cfgOCCLUSION_PLANE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", cfgFUNC_DATA__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", cfgFUNC_EVENT_DATA__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", cfgFUNC_DATA_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", cfgWATER_SURFACE_NUM__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", cfgWATER_SURFACE_START__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", cfgWATER_VERTEX__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", cfgWATER_POS__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", cfgWATER_PARAM__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", cfgWATER_SHAKE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", cfgWATER_SURFACE_END__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", cfgWATER_DRAW_NUM__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", __ct__9CMapWaterFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", cfgWATER_DRAW__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mapload", LoadCfgFile__4CMapFPciP9mgCMemory);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_438__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", map_tag);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", cfg_tag);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_611);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_612);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_613);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_614);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_615);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_616);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_617);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_618__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_619);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_620);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_621);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_622);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_623);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_624);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_625);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_626);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_627);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_628);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_629__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_630);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_631);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_632);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_633);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_634);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_635);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_636);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_637);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_638);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_639);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_640);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_641);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_642);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_643);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_644);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_645);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_646);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_647);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_648);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_649);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_650);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_651);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_652);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_653);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_654);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_655);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_656);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_657);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_658);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_659__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_660__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_661);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_662);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1064);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1128);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1129);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1130);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1131);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1132);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1133);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1134);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1135);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1136);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1278);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1279);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1280);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1281);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1282);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1283);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1284);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1370);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1371);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1372);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1373);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1374);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1375);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1376);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1377);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1378);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1379);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1380);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1436);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1437);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1438);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1439);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", at_1544);

// Virtual tables (.vtables)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", __vt__17CList_9CMapPiece_);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mapload", __vt__17CList_9CMapParts_);

// Small uninitialised data (.sbss)
unsigned char mapMap[0x4];
unsigned char mapNowMapParts[0x4];
unsigned char mapNowMapPiece[0x4];
unsigned char mapStack[0x4];
unsigned char mapFarDist[0x4];
unsigned char mapFarAlpha[0x4];
unsigned char mapShow[0x4];
unsigned char mapLOD_ID[0x4];
unsigned char mapCameraInfoIdx[0x4];
unsigned char mapCameraRectIdx[0x4];
unsigned char mapFuncPointIdx[0x4];
unsigned char mapNowFuncPoint[0x4];
unsigned char mapMatIdx[0x4];
unsigned char mapPtsFunc[0x4];
unsigned char mapAddMode[0x4];
unsigned char ReserveFuncFlag[0x4];
unsigned char WaterIndex[0x4];
unsigned char cfgWater[0x4];

// Uninitialised data (.bss)
unsigned char mapPlacePartsName[0x100];
unsigned char mapMapPartsName[0x100];
unsigned char mapMapPartsGroupName[0x100];
unsigned char mapPos[0x10];
unsigned char mapRot[0x10];
unsigned char mapScale[0x10];
