#include "common.h"

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Get_aquarium_paul_table__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Get_aquarium_paul_table_xz__Fii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", local_aquarium_limmit_check__FPffif);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GetUseableEsaNo__FPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GetEsaInfo__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Generate__7CBubbleFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Generate__7CBubbleFPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", SetTexture__7CBubbleFP10mgCTextureii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Step__7CBubbleFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Draw__7CBubbleFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Initialize__7CBubbleFP9mgCMemoryPfif);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", RunOff__7CBubbleFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GetChildFishNo__Fii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", SetFishAdjustScale__Fiiff);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Initialize__20CAquaFishActionParamFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", __ct__9CAquaFishFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Initialize__9CAquaFishFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", SetLiveParam__9CAquaFishFP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", SetAdjustScale__9CAquaFishFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", AddFatigue__9CAquaFishFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GetPosition2D__9CAquaFishFPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GetDirVect__9CAquaFishFPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", NormalGetNextVelo__9CAquaFishFf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", NormalGetNextRotY__9CAquaFishFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", NormalGetNextRot__9CAquaFishFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", CalcMoveSpeed__9CAquaFishFf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", NextRootNormal__9CAquaFishFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", MoveActionRound__9CAquaFishFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", MoveActionBattle__9CAquaFishFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", NextThink__9CAquaFishFiP16NEXT_THINK_PARAM);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", ParamStep__9CAquaFishFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", FishDraw__9CAquaFishFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Initialize__12CAquaFishEffFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", StartFishEffect__12CAquaFishEffFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Step__12CAquaFishEffFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Draw__12CAquaFishEffFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", __ct__9CFishFoodFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", SetDropPosition__9CFishFoodFPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Drop__9CFishFoodFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Step__9CFishFoodFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", DrawEsaDropRoot__FP9CFishFoodf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", AquaMesDispAdjustPos__FP6ClsMesPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", __ct__8CAquaMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Initialize__8CAquaMesFP9mgCMemory);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", SettingAquaMes__8CAquaMesFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", SetTitleId__8CAquaMesFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", AddMenuCursor__8CAquaMesFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", SetQuestionId__8CAquaMesFiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", AddQuestionCursor__8CAquaMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", SetCtrlHelpId__8CAquaMesFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", SetInfoMsgID__8CAquaMesFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", EatMessage__8CAquaMesFiP9CAquaFish);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", ChangeManMessage__8CAquaMesFP9CAquaFish);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", DeadMessage__8CAquaMesFP9CAquaFish);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Step__8CAquaMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Draw__8CAquaMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", DrawTitleMes__8CAquaMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GetFishPath__FiPc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GetFishImgPath__FPciP14BREEDFISH_USED);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GetFishImageColor__Fii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", FishIMGReplace__FP1P11CCharacter2iP14BREEDFISH_USED);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", DrawFishParam__FiiP10mgCTextureP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", __ct__9CAquariumFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Clear__9CAquariumFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Initialize__9CAquariumFP9mgCMemoryPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", LoadFish__9CAquariumFiP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", SettingAqua__9CAquariumFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", CalcFishParam__FP14BREEDFISH_USED);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", CombineParam__Fii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", CombineFish__9CAquariumFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GetBattleTarget__9CAquariumFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Thinking__9CAquariumFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", ColCheck__9CAquariumFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", InitSelFish__9CAquariumFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", SelectFish__9CAquariumFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", SelFishSetCursor__9CAquariumFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Step__9CAquariumFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", Draw__9CAquariumFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", MenuAquaInit__FP9mgCMemoryPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", MenuAquaKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", MenuAquaDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", MenuGyoraceFishSelInit__FP9mgCMemoryPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", MenuGyoraceFishSelKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", MenuGyoraceFishSelDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GetGyoRaceFish__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", SetGyoRaceAquariumNo__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GetGyoRaceAquariumNo__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", SetGyoRaceClass__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GetGyoRaceClass__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", SetGyoRaceNo__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GetGyoRaceNo__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", SetGyoRaceRanking__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GetGyoRaceRanking__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", _GYORACE_LISTNUM__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", _GYORACE_DATA__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", LoadData__16CGyoraceFishDataFP9mgCMemoryP1);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GetRaceFish__16CGyoraceFishDataFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", _PRIZE_LISTNUM__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", _PRIZE_GROUP__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", _PRIZE__FP9SPI_STACKi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", InitFishPrize__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", LoadFishPrize__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", LoadFishPrize__FiP9mgCMemory);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", RefreshFishPrize__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GetFishPrize__FiiP15FISH_PRIZE_INFO);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", TuriTourCount__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GyoraceCFGAnalyze__FPc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", SearchOmakeGyoracer__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", CheckSameRacerFish__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GetOmakeGyoracer2__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GetOmakeGyoracerTactics__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", SetOmakeGyoracerTactics__Fii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GyoracerListUpdate__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GyoraceSubGameInitData__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GyoraceMenuInit__FP9mgCMemoryPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", OmakeGyoraceSelect__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", ForceSetGyoList__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GyoraceMenuKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", GyoraceMenuDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", DrawSubGameTitle__FP10mgCTextureiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", DrawSubGameListFix__FP10mgCTextureiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", DrawSubGameScrlList__FP10mgCTexturePiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", DrawSubGameUnderLine__FP10mgCTextureiii);

// Static initialiser (.init)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuaqua", __sinit_menuaqua_cpp);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", aquafish_mixTable);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", ambient);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", light_dir);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", light_color);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", ColChkPoint);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", ColChkPoint2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", ColChkPoint3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", esa_info);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", aqua_bubble_generate_pos);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", up_tbl_996);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", amptbl_997);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_1160);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_1241__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", dirtbl_1242);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_1346);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_1471__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", max_tbl_1484);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", aquafish_info);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", u_brdtbl_2493);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", get_paraxtbl_2494);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", ptbl_2495);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", chrtbl_2503);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2742__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2935);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2975);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2976);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3016);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3290);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3291__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3310);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3311);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", langTbl_3630);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", menu_id_tbl_3721);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4306);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4352);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4363__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4364__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4369__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4370__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4371__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4372__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", v1orig_4373);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", v2orig_4374);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", v3orig_4375);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", v4orig_4376);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", t_4408);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4432);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", gyorace_tag);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", gyoprize_tag);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", GyoracerIndexNo);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", GyoracerTacticsNo);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", Mitouroku);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_5229);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_5230);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", vol_5253);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", pl_s_5630);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", pl_b_5631);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", tbl_5644);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", tbl_5669);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", bart_5670);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", pl_s_5699);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_1323);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_1387__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_1388__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2112__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2183__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2184__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2185__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2186__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2361);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2377__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2379__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2380__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2381__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2382__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2383__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2384__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2385__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2386__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2387__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2388__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2389__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2390__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2391__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2392__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2393__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2394__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2395__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2396__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2415);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2871);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2872);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2873);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2874);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2929__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_2930__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3150);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3151);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3152);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3153);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3154);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3155);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3156);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3157);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3158__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3159__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3160__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3161__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3162__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3163__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3164__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3429);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_3430);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4300);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4299);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4420);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4421);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4422);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4423);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4424);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4425);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4426);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4427);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4428);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4429);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4430);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4431);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4519);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4629);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4814);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4815);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4825);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4884);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4885);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4900);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4901);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4975);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4976);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4977);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4978);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4979);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_4980);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_5140);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_5487);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_5488);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_5489);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_5490);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_5491);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_5492);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_5493);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_5494);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_5495);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_5496);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_5497);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_5498);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_5499);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_5500);

// Static initialiser table (.ctor)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", D_0037B024);

// Virtual tables (.vtables)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", __vt__9CFishFood);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", __vt__9CAquaFish);

// Small initialised data (.sdata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", ColChkPointNum);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", AQUA_TITLE_X);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", AQUA_TITLE_Y);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", AQUA_TITLE_W);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", AQUA_TITLE_H);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", xtbl_2468);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", ytbl_2469);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", wtbl_2470);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", htbl_2471);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", coltbl_2472);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", offtbl_2496);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", poffset_2511);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", m_next_aqua_no);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", aqua_frame_sizetbl_2934);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", tbl_3505);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", another_aquarium_Notbl_3642);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", menu_max_tbl_3720);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", filename_4899);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuaqua", at_5309);

// Small uninitialised data (.sbss)
unsigned char AquaScene[0x4];
unsigned char AquaMode[0x4];
unsigned char Aquarium_NameregistBlock[0x4];
unsigned char Aqua_SpSndID[0x4];
unsigned char Aqua_SpSndBattleCount[0x4];
unsigned char AquaCameraCtrlMode[0x4];
unsigned char Camera__2[0x4];
unsigned char aqua_old_env[0x4];
unsigned char Tex_Aqualium[0x4];
unsigned char Tex_FishEffect[0x4];
unsigned char menu_debug_select[0x10];
unsigned char aquarium_xz_table[0x10];
unsigned char aquarium_y_table[0x4];
unsigned char aquarium_paul_table[0x4];
unsigned char AquaBattleBubble[0x4];
unsigned char AquaBattleBubble_Generate_Wait[0x4];
unsigned char AquaBattleBubble_Generate_Counter[0x4];
unsigned char count_1612[0x4];
unsigned char init_1613[0x4];
unsigned char m_aquarium_para[0x4];
unsigned char m_aquarium_limmit_adr[0x4];
unsigned char AquaDeadCheck[0x4];
unsigned char sel_sift_fish_3638[0x4];
unsigned char init_3639[0x4];
unsigned char sel_sift_fish_select_3641[0x4];
unsigned char Auqa_Bgm_Volf[0x4];
unsigned char GyoraceFish[0x4];
unsigned char GyoraceFishSelectMode[0x4];
unsigned char GyoraceFishSelectNo[0x4];
unsigned char GyoraceFishSelTexBk[0x4];
unsigned char GyoraceFishFrameImgTexNo[0x4];
unsigned char GyoraceFishSelNum[0x4];
unsigned char GyoraceFishSel[0x8];
unsigned char GyoRaceFishReadPhase[0x4];
unsigned char GyoRaceAquariumNo[0x4];
unsigned char GyoRaceClass[0x4];
unsigned char GyoRaceProgressNum[0x4];
unsigned char GyoRaceRankingData[0x4];
unsigned char spi_gyorace_stack[0x4];
unsigned char spi_gyorace_data[0x4];
unsigned char spi_nowanalyze_gyorace_data[0x4];
unsigned char spi_nowanalyze_gyorace_limmit[0x4];
unsigned char spi_gyorace_counter[0x4];
unsigned char fish_prize_buildstack[0x4];
unsigned char FishTournamentGoods[0x4];
unsigned char FishTournamentGoodsNum[0x4];
unsigned char FishTournamentGoodsType[0x4];
unsigned char spiFishTournamentGoods[0x4];
unsigned char spi_fish_prize_info[0x4];
unsigned char save_fish_prize_list[0x4];
unsigned char SubSaveData[0x4];
unsigned char GyoraceData[0x4];
unsigned char GyoracerActive[0x4];
unsigned char GyoraceMes[0x4];
unsigned char GyoraceMesDrawFlag[0x4];
unsigned char GyoraceFishInfoDrawFlag[0x4];
unsigned char GyoraceFishMes[0x4];
unsigned char GyoraceFishHave[0x4];
unsigned char GyoraceFishHaveDrawFlag[0x4];
unsigned char GyoraceFishTacMes[0x4];
unsigned char GyoraceFishTacMesDrawFlag[0x4];
unsigned char GyoraceFishHaveListSelect[0x8];
unsigned char GyoraceCursor[0x4];
unsigned char GyoraceFishTex[0x4];
unsigned char GyoraceNowMode[0x4];
unsigned char GyoraceNowPhase[0x4];
unsigned char GyoraceQuestionMsgDrawFlag[0x4];
unsigned char GyoraceHaveFishCursorDrawFlag[0x4];
unsigned char GyoraceHaveFishCursor[0x4];
unsigned char Gyoracemenu_long_hand_count[0x4];
unsigned char Gyoracemenu_CursorXY[0x8];
unsigned char GyoraceExeCfgBuffer[0x4];
unsigned char GyoraceExeCfgBufferSize[0x4];
unsigned char GyoraceHaveFishListMakeLine[0x4];
unsigned char GyoraceHaveFishListTopY[0x4];
unsigned char GyoraceHaveFishListScrlBarY[0x4];
unsigned char GyoraceHaveFishListScrlInit[0x4];
unsigned char MenuLoadFishIsLoad[0x4];
unsigned char MenuLoadFishSelect[0x4];
unsigned char MenuLoadFishTopLine[0x4];
unsigned char MenuLoadFishSelectData[0x4];
unsigned char MenuLoadBoardTex[0x4];
unsigned char MenuLoadFishBoardX[0x4];
unsigned char local_gdata_5177[0x4];
unsigned char init_5178[0x4];
unsigned char save_now_space_racer_no_5180[0x4];
unsigned char init_5181[0x4];

// Uninitialised data (.bss)
unsigned char Aquarium_NameregistStack[0x30];
unsigned char AquaBubble[0x10];
unsigned char AquaFishBubble[0x20];
unsigned char AquaBattleBubble_Pos[0x10];
unsigned char AquaFishEff[0x20];
unsigned char at_2473[0x20];
unsigned char at_2474[0x20];
unsigned char at_2475[0x20];
unsigned char at_4433[0x30];
unsigned char Aquarium[0x3D0];
unsigned char GyoraceFishSelStack[0x30];
unsigned char fish_save_present[0x60];
unsigned char GyoraceStack[0x30];
unsigned char GyoraceTexBlock[0x40];
unsigned char GyoraceMenuOptionBuff[0x40];
unsigned char MenuDCMsg[0x28];
