#include "common.h"

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", InitMenuReturnMsg__FP9mgCMemory);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", SetMenuReturnMsgCtrl__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", DrawMenuReturnMsg__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", CheckOmakeVtuto__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", InitMnOnePictTex__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", MenuManualInit__FP9mgCMemoryPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", MenuManualKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", MenuManualDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", KeyStep__11CManualMenuFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", CalcTex__11CManualMenuFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", CalcCursorPosition__11CManualMenuFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", KeyStep__11CMenuOptionFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", CalcTex__11CMenuOptionFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", DefaultButton__11CMenuOptionFPP18MENUFORMPARTS_TYPE);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", EnableButton__11CMenuOptionFP18MENUFORMPARTS_TYPE);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", UpdateOptionForm__11CMenuOptionFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", MenuOptionInit__FP9mgCMemoryPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", MenuOptionKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", MenuOptionDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", LocalFunc_AdjustScrlBar__FPP18MENUFORMPARTS_TYPEPiPiiffi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", SetDlInfoMsg__14CSaveMenuClassFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", EnvSetSave__14CSaveMenuClassFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", KeyStep__14CSaveMenuClassFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", SaveFileListDraw__FRiPfi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", SetMCIconData__FPUii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", GetDngMapNo__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", SaveMapInfo__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", ResetMapInfo__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", MenuSaveInit__FP9mgCMemoryPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", MenuSaveKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", MenuSaveDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", SubGameCFGAnalyze__FPc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", SubGameSaveInit__FP9mgCMemoryPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", SubGameSaveKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", SubGameSaveDraw__Fv);

// Static initialiser (.init)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuop", __sinit_menuop_cpp);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", manual_boot_event_no);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", submap_table_1022);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", fillw_1125);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1315__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", tp_2083);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", conv_2316);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2609__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", dngmap_2627);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", b_2715);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1023__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1024__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1025__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1026__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1027__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1028__7);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1029__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1030__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1031__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1032__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1033__6);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1034__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1035__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1036__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1037__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1038__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1039__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1040__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1041__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1042__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1043__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1102);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1103__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1104__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1105__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1106__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1107__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1108);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1109__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1237__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1238__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1428__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1429__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1430__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1431__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1432__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1433__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1434__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1435__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1436__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1437__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1438__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1439__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1440__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1441__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1512__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1513__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1514__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1515__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1516__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1517__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1518__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1519__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1648__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1649);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1650__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1651__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1652__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1653__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1654__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1655__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1656__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1900);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1901);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1902);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1903);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1904__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1905__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1906__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2024);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2025);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2084__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2085__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2086);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2498);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2499);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2500);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2501);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2502);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2503);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2504__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2505__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2506__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2507__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2508__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2509__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2510__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2511);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2512__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2513);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2514);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2515);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2518__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2517__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2603);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2604);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2605);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2628__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2629__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2630__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2631__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2632__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2633__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2634__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2764);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2765);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2766);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2767);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2768);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2769);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2770__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2771__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2772__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2773__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2774__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2775__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2821__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2822);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2823);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2824);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2825);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2826__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2827);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2895);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_3198__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_3199__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_3200__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_3201__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_3202__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_3203);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_3204);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_3205);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_3206);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_3207);

// Static initialiser table (.ctor)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", D_0037B060);

// Virtual tables (.vtables)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", __vt__14CSaveMenuClass);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", __vt__11CMenuOption);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", __vt__11CManualMenu);

// Small initialised data (.sdata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", manual_list_mesclstbl);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", config_option_num_i);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", config_option_num_f);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_1616__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", tbl_2023);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2335__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuop", at_2342);

// Small uninitialised data (.sbss)
unsigned char ManualMovie[0x4];
unsigned char ManualMovieTex[0x4];
unsigned char LocalMenuBGForm[0x4];
unsigned char LocalMenuClipForm[0x4];
unsigned char MenuReturnMsg[0x4];
unsigned char MenuReturnMsgDrawFlag[0x4];
unsigned char MovieBattleBGMPhase[0x4];
unsigned char MoviePreBattleBGMVol_Save[0x4];
unsigned char MoviePreBattleBGMVol[0x4];
unsigned char Movie_DungeonFlag[0x4];
unsigned char Movie_BossFlag[0x4];
unsigned char MovieBgmBattleCheckStopFlag[0x4];
unsigned char CManualPtr[0x4];
unsigned char MovieViewFlag[0x4];
unsigned char ManualMovieFadeCount_1253[0x4];
unsigned char init_1254[0x8];
unsigned char at_1306__5[0x8];
unsigned char at_1342__3[0x8];
unsigned char at_1523__2[0x8];
unsigned char OptionButtonForm[0x8];
unsigned char at_1614__2[0x8];
unsigned char at_1615__3[0x8];
unsigned char CMenuOptionPtr[0x4];
unsigned char MemoryCardPtr[0x4];
unsigned char SaveMenuPtr[0x4];
unsigned char FormatCase_1968[0x4];
unsigned char init_1969[0x4];
unsigned char DarkClonicleFileMax_2004[0x4];
unsigned char init_2005[0x4];
unsigned char input_wait_counter_2067[0x4];
unsigned char init_2068[0x8];
unsigned char at_2115__3[0x8];
unsigned char at_2276[0x8];
unsigned char at_2319[0x4];
unsigned char at_2326__2[0x4];
unsigned char at_2327[0x4];
unsigned char at_2328__2[0x4];
unsigned char at_2330__2[0x4];
unsigned char at_2331__2[0x4];
unsigned char Tex_SaveFile[0x4];
unsigned char space_2549[0x4];
unsigned char init_2550[0x4];
unsigned char MenuMapInfoSave_DngNo[0x4];
unsigned char SubGameSaveOrLoad[0x4];
unsigned char SubGameSaveOrLoadPhase[0x4];
unsigned char SubGameSaveLoadStatus[0x4];
unsigned char SubGameMCPort[0x4];
unsigned char SubGameSaveBlock[0x8];
unsigned char SubTrueTotalSaveFileSize[0x4];
unsigned char SubCheckTotalSaveFileSize[0x4];
unsigned char SubSaveTileXY[0x4];
unsigned char SubGameSaveCFGBuffer[0x4];
unsigned char SubGameSaveCFGBufferSize[0x8];
unsigned char at_3070[0x8];
unsigned char at_3091[0x8];

// Uninitialised data (.bss)
unsigned char MnOnePictTex[0x20];
unsigned char StaticMenuLocalStack[0x30];
unsigned char StaticMenuLocalStack2[0x30];
unsigned char SaveMenuStack[0x30];
unsigned char SaveFileList[0x38];
unsigned char MenuMapInfoSave[0x18];
unsigned char SubGameDataBgm[0x20];
