#include "common.h"

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", DrawTrushMenuMessage__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", __ct__14CBaseMenuClassFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetTexBlock__14CBaseMenuClassFPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", DeleteTexBlock__14CBaseMenuClassFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemCommnadSelectPrepare__14CBaseMenuClassFP13CGameDataUsedii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemMoveItemCommand__14CBaseMenuClassFP13CGameDataUsediiP16CMenuPosDataFormi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemCommandSelect__14CBaseMenuClassFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetItemCmdMsgPos__14CBaseMenuClassFPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuHowMuchNumSelect__FiP13CGameDataUsedi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemAskMode_HowMuch__14CBaseMenuClassFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckTrushWeapon__FP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckSpectolFusion__14CBaseMenuClassFP13CGameDataUsediP16CMenuPosDataForm);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", UpdataInfoSpectolBreakItem__FP7CDC2MesP13CGameDataUsedi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckEquipFishRod__FP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", IsSpectolTrans__14CBaseMenuClassFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", IsSpectolFusion__14CBaseMenuClassFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", IsDispTrushCommand__FP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", IsTrush__14CBaseMenuClassFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", IsItemUseNum__14CBaseMenuClassFiiiP13CGameDataUsedP14CItemUseTarget);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SelectInGiftBox__14CBaseMenuClassFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetConditionHowMuchBoard__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetAskHowMuchItemNum__14CBaseMenuClassFP18MENU_SWAPITEM_INFOP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetAskParam__14CBaseMenuClassFP17MENU_ASKMODE_PARA);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", ExeScript__14CBaseMenuClassFPc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", ExtendCommand__14CBaseMenuClassFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SelectMakeObject__14CBaseMenuClassFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", IsAskEnd__14CBaseMenuClassFiP16CMenuPosDataForm);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", FadeInMenu__14CBaseMenuClassFif);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", FadeOutMenu__14CBaseMenuClassFif);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", FadeCheckMenu__14CBaseMenuClassFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetPreCmdTrush__FP14CBaseMenuClassiP13CGameDataUsedP16CMenuPosDataForm);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetPreCmdSpectolBreak__FP14CBaseMenuClassiP16CMenuPosDataFormP13CGameDataUsedP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetPreCmdGiftBoxSelect__FP14CBaseMenuClassP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckFishCondition__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", Initialize__15CMENU_USERPARAMFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", AttachInfo__15CMENU_USERPARAMFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", Initialize__17MENU_ASKMODE_PARAFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", __ct__17MENU_ASKMODE_PARAFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", Set__18MENU_SWAPITEM_INFOFiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", IsEnableChangeRoboParts__FP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetSpectolInfo__FP13CGameDataUsedP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", InitSpectol__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", AfterSpectolFusion__FP13CGameDataUsedP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", FusionColor__FiiPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SpectolFrameCalc__FP12CActionCharai);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", TransSpectolDataSave__FP13CGameDataUsedi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckNowRoboUseCapacity__FPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", ExchangeItemInfoMake__FP18MENU_SWAPITEM_INFOPA4_iii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuCheckLine__FPiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuKeySelectCheck__FiPiPiiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuListKeyCheck__FiPiPiiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuGlidKeyCheck__FiPiPiPiPiPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuListSelectKeyCheck__Fii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemBrdKey__FiPiPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuDataSwap__FP13CGameDataUsedP13CGameDataUsedi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", Initialize__12CMenuKeyFuncFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", AttachFuncData__12CMenuKeyFuncFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetActiveCharaNo__12CMenuKeyFuncFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuPosStep__12CMenuKeyFuncFPiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuSetPos__12CMenuKeyFuncFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuPosStop__12CMenuKeyFuncFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuPosPlay__12CMenuKeyFuncFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetMoveMethod__12CMenuKeyFuncFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetWakuMoveMethod__12CMenuKeyFuncFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetItemPos__12CMenuKeyFuncFPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetWakuType__12CMenuKeyFuncFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetWakuWH__12CMenuKeyFuncFiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetVibeCnt__12CMenuKeyFuncFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetVibeR__12CMenuKeyFuncFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetCursorPos__12CMenuKeyFuncFPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CursorFadeIn__12CMenuKeyFuncFfi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CursorFadeOut__12CMenuKeyFuncFfi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", EnableSwapNowPos__12CMenuKeyFuncFP18MENU_SWAPITEM_INFO);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetItemAll__12CMenuKeyFuncFP13CGameDataUsedP18MENU_SWAPITEM_INFO);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetItemCommandMsg__FP13CGameDataUsedP17MENU_ASKMODE_PARAii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetItemCommandMsg__FP13CGameDataUsedPiPUiPsPsii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SelDataInit__12CMenuKeyFuncFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckSelectKey__12CMenuKeyFuncFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckLRKey__12CMenuKeyFuncFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuCheckPushButton__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", ConvertCheckPushButton__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckPushButton__12CMenuKeyFuncFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckAnalogKey__12CMenuKeyFuncFiPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckKeyInput__12CMenuKeyFuncFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetDebugInputKey__12CMenuKeyFuncFRiRi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuSwapItem__12CMenuKeyFuncFP13CGameDataUsedP18MENU_SWAPITEM_INFOib);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetGameDataUsedForSWAPINFO__FP18MENU_SWAPITEM_INFO);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", ReturnItemMenu__12CMenuKeyFuncFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", InitHaveData__12CMenuKeyFuncFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetHaveItemInfo__12CMenuKeyFuncFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", menu_inputkey_limmit_check_line__12CMenuKeyFuncFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", menu_inputkey_limmit_check_glid__12CMenuKeyFuncFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckMoveSelect__12CMenuKeyFuncFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", FadeOutMenuBGMVol__12CMenuKeyFuncFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", FadeInMenuBGMVol__12CMenuKeyFuncFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", StepMenuBGM__12CMenuKeyFuncFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckEnableHaveItemNum__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuEquipCameraSetEnv__FP12CActionCharaP9mgCCameraii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuPosFormValueSetWeapon__FP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuFormUpdataAttachInfo__FP16CMenuPosDataFormP13CGameDataUsediiPs);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuPosFormValueSetFishingRod__FP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", Initialize__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetEquipListNo__13CMenuItemInfoFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckEquipListNo__13CMenuItemInfoFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckSoundLoad__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SearchNowPosItemExist__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", IsCancelNoneLoadItem__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", IsCancelLoadItem__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SaveViewWeaponStatus__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckViewWeaponStatus__13CMenuItemInfoFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", ReturnActiveCharaViewMode__13CMenuItemInfoFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", NextModeBuildUpInfo__13CMenuItemInfoFP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", EquipDirect__13CMenuItemInfoFiP13CGameDataUsedRi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckLoadInfo__13CMenuItemInfoFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", ItemCmdAfter__13CMenuItemInfoFiP16ITEMCMD_RET_PARA);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", IsAskExtend__13CMenuItemInfoFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuMoveItemPos__FPiPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CommonSetMoveItemClass__FPA4_i);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", EnterDataMenu__13CMenuItemInfoFPUi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetActiveCharaIDForItemCmd__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetActiveCharaNo__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", ExitEnd__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", AttachFormInfo__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuModeMalloc__13CMenuItemInfoFP9mgCMemory);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CalcTex__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CalcCursorPosition__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", EffectDrawCheck__14CBaseMenuClassFP16CMenuPosDataForm);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemInit__FP9mgCMemoryPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemDebugKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemDebugDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", PushKey__13CMenuItemInfoFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", local_item_infoview_set__FP18MENUFORMPARTS_TYPEP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemCharaActWepInfoDraw__FP16CMenuPosDataFormP13CGameDataUsedii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemCharaViewCheck__FP10CHARA_DATAii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuPosFormValueSetCharaRobo__FP9ROBO_DATAi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuPosFormValueSetMonster__FP16MOS_CHANGE_PARAMP10CHARA_DATA);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckBuildUp__FP13CGameDataUsedPiPiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", BuildUpWeaponTrans__FP13CGameDataUsedi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", BuildUpWeaponNameBoardDraw__FP11mgCDrawPrimffi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuWeaponBuildUpDraw__FRi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuWeaponStatusInfoFormSet__FP13CGameDataUsedP11CDataWeapon);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemSelectDiffer__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckLoadItemNo__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", ModelReadStart__13CMenuItemInfoFiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", WeaponBuildCheck__13CMenuItemInfoFP12CActionCharaii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", ModelReadEndCheck__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SearchEffectDisplayPosition__13CMenuItemInfoFPiP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetItemEffect__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", LRCheck__13CMenuItemInfoFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemInfoCursorSet__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuCharaStatusDraw__FRi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemInfoCursorDraw__FRi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", KeyStepLocal__13CMenuItemInfoFiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", KeyStep__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetPtrList__11CItemSelectFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetExistThisPosData__11CItemSelectFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckUse__11CItemSelectFP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", KeyStep__11CItemSelectFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", Draw__11CItemSelectFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemSelectInit__FP9mgCMemoryPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemSelectKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemSelectDraw__Fv);

// Static initialiser (.init)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", __sinit_menusys_cpp);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", WepStatusInfoStrTable);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", WepStatusInfoStatusVolStrTable);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", addtbl_2178);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2328);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", n_2667);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", human_tbl_2871);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", padtbl_3359);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", MenuCheckKey);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", focusnametbl);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3771);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3772);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", item_menu_argtbl);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", exename_4332);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4350);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4369__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4410);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4414);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4485);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4495__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4509);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", ItemMenuFormNameTbl);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", local_over_flow_baseposname);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", tbl_4981);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", plist_4982);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", tbl_5293);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5458);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5531);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5534);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5556__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", waku_infotbl_5836);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", wakutypeTbl_5837);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", dbox_path_6083);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", table_6164);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", attrtable_6472);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6480);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", stchar_6508);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", whptbl_7376);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", backboard_table_x_7625);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", mos_repeat_table_x_7694);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", strtbl_7727);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", argtblno_7927);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", sel_7928);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", conv_7932);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", robo_stand_pos_8151);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", effparamtbl_8275);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", status_table_8427);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", xytable_8428);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", xytable_wep_8429);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", draw_tbl_8453);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", imgtbl_8945);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", menu_item_swap_sndtbl);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_919__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_920__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_921__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_922__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_923__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_924__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_925__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_926__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_927__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_928__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_929__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_930__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_931__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_932__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_933__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_934__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_935__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_936__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_937__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_938__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_1462__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_1493__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2545__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2546__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2547);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2548);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2549);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2550);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2584);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2585);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2651);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3316);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3744);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3745);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3746);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3747);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3748__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3749);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3750);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3751);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3774__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3775__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3822);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3823);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3824);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3825);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3826);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3827);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3828);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3829);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3893);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3894);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3895);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3924);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4333);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4334);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4335);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4659);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4660);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4661);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4662);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4663);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4664);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4665);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4666);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4667);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4668);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4669);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4670);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4671);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4672);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4673);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4674);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4950);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4951);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4952);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4953);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4954);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4955);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4956);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4957);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4958);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4967);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4968);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4969);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4970);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4971);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4972);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4973);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4974);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4975__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4983);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4984);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4985);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5022);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5130);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5131);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5132);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5133);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5134);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5210);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5211);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5259);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5260);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5261);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5262);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5263);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5264);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5265);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5266);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5267);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5268);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5269);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5270);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5271);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5272);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5273);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5274);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5275);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5276);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5277);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5278);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5279);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5280);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5281);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5282);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5283);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5757);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5758);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5759);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5763);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5760);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5879);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5880);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5881);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5882);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5883);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6011);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6012);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6013);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6014);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6015);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6016);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6424);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6473);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6474);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6475);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6476);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6477);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6478);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6479);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6509);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6510);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6511);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6512);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6513);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6514);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6515);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6516);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6517);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6518);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6519);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6520);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6760);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6761);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6762);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6763);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6764);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6765);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6766);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6767);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6768);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6769);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6770);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6771);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6772);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6773);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6774);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6775);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6776);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6777);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6778);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6779);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6780);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6781);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6782);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6783);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6784);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6785);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6786);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6787);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6788);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6789);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6790);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6791);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6792);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6793);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6794);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6795);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6796);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6797);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6798);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6799);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6800);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6801);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6802);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6803);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6804);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6805);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6806);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6807);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6808);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6809);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6810);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6811);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6812);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6813);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6814);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7342);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7343);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7344);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7345);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7346);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7347);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7349);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7348);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7438);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7439);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7440);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7441);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7442);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7443);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7478);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7534);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7535);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7536);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7537);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7538);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7539);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7540);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7541);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7560);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7561);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7562);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7563);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7564);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7728);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7729);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7730);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7731);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7732);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7968);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8083);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8084);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8199);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8201);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8200);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8315);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8421);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8711);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8819);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8820);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8821);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8822);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8823);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8825);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8824);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8869);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8946);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8947);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8948);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_9032);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_9033);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_9179);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_9215);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_9216);

// Static initialiser table (.ctor)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", D_0037B034);

// Virtual tables (.vtables)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", __vt__11CItemSelect);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", __vt__13CMenuItemInfo);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", __vt__14CBaseMenuClass);

// Small initialised data (.sdata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", MenuRoboEquipTable);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", MenuItemBoardTotalNum);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", MenuItemBoardTotalLine);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", MenuWeaponEnvSetListNo);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_1232);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", wakutbl_1411);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", tartbl_1412);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", trans_spectol_pos);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", trans_spectol_posold);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", trans_spectol_rgb);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", SpectolFramePosValue);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", ret_tbl1_2511);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2512);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", menu_camera_reference_id);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", menu_camera_reference_no);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", tbl_4094);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", menuitem_initviewtbl);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", menuitem_initmenumode);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4469);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", OverFlowFormName);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", itemmenu_calcmode_tbl_5410);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5563);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", MenuDebugModel_AdjustFlag);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6438);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", backboard_table_y_7626);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", backboard_table_w_7627);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", backboard_x_repeat_drawnum_7628);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", backboard_y_repeat_drawnum_7629);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7695);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", cnttbl_8130);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", SameviewmodeTable_8406);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_9055);

// Small uninitialised data (.sbss)
unsigned char MainCharaReadStackReadAdr[0x4];
unsigned char MenuRepairMan[0x4];
unsigned char MenuItem_ItemBoardTopLine[0x4];
unsigned char MenuItem_ItemBoardTopSelect[0x4];
unsigned char menu_chara_activeItem_limmit_check[0x8];
unsigned char MenuSpectolSatusCheckForm[0x4];
unsigned char MenuSpectolSatusCheckBGFadeForm[0x4];
unsigned char TrushMesWindowFlag[0x4];
unsigned char ActiveMenuWeaponCharaRange[0x4];
unsigned char MenuWeaponEnvSetChara[0x4];
unsigned char MenuStatusMode[0x4];
unsigned char MenuStatusTex[0x8];
unsigned char MenuItemUseTarget[0x8];
unsigned char CMenuItemInfoPt[0x8];
unsigned char MenuEffect[0x8];
unsigned char MenuItemSpectolTransSoundBuffer[0x8];
unsigned char SpectolInfo[0x8];
unsigned char SpectolFusion_LeftOrRight[0x4];
unsigned char SpectolFusionTargetChara[0x4];
unsigned char save_spectol_fusion_spstatus[0x4];
unsigned char MenuItemCmdArgPos[0x4];
unsigned char MenuItemCommand_RoboPackBreakFlag[0x4];
unsigned char cmd_counter_1048[0x4];
unsigned char init_1049[0x4];
unsigned char MenuItemCommandDir[0x4];
unsigned char at_1385__2[0x8];
unsigned char MenuHowHaveMuchNum[0x4];
unsigned char SpectolBreakNum_Limit[0x4];
unsigned char SpectolBreakNum[0x4];
unsigned char SpectolBreakSpPoint[0x4];
unsigned char at_1545[0x4];
unsigned char trans_spectol_cnt[0x4];
unsigned char spegetflag[0x4];
unsigned char SpectolFrame[0x4];
unsigned char MenuSpectolTransPos[0x4];
unsigned char itemmenu_chr_rotflag[0x4];
unsigned char sndflag_1665[0x4];
unsigned char init_1666[0x4];
unsigned char at_1685[0x8];
unsigned char MenuTrushNum[0x4];
unsigned char fusion_color_val[0x4];
unsigned char SpectolFrameScaleAngle[0x4];
unsigned char SpectolFrameFadeAlpha[0x4];
unsigned char at_2345__2[0x8];
unsigned char at_2346__2[0x8];
unsigned char at_2564[0x8];
unsigned char at_3791__2[0x8];
unsigned char count_time_3839[0x4];
unsigned char init_3840[0x4];
unsigned char FxScriptManPauseFlag[0x4];
unsigned char debug_common_data[0x4];
unsigned char view_weapon_flag[0x4];
unsigned char OldViewWep[0x4];
unsigned char NewViewWep[0x8];
unsigned char MenuRepairTargetWeaponPos[0x8];
unsigned char at_4365__2[0x8];
unsigned char Effect_Counter_4682[0x4];
unsigned char init_4683[0x4];
unsigned char BuildEndFlag_4703[0x4];
unsigned char init_4704[0x4];
unsigned char at_5026[0x8];
unsigned char Tex_BuildUpBoard[0x4];
unsigned char Robo_Sound_ID_Save[0x4];
unsigned char checkmoveFlag_5411[0x4];
unsigned char init_5412[0x4];
unsigned char at_5573[0x4];
unsigned char MenuDebugModelDrawFlag[0x4];
unsigned char at_5769[0x8];
unsigned char at_5782[0x8];
unsigned char at_5829[0x8];
unsigned char MenuDebugSize[0x4];
unsigned char MenuDebugItemModel[0x4];
unsigned char MenuDebugCamera[0x8];
unsigned char at_6133[0x8];
unsigned char cnt_6161[0x4];
unsigned char init_6162[0x4];
unsigned char at_6176[0x8];
unsigned char at_6220[0x8];
unsigned char at_6234[0x8];
unsigned char at_6256[0x8];
unsigned char at_6265[0x8];
unsigned char testcnt_6298[0x4];
unsigned char init_6299[0x4];
unsigned char at_7021[0x4];
unsigned char Save_AskParamInfo_7099[0x4];
unsigned char fusion_blinkcnt_7120[0x4];
unsigned char init_7121[0x4];
unsigned char diffent_weapon_dispflag_7125[0x4];
unsigned char init_7126[0x4];
unsigned char WeaponWarningCounter[0x4];
unsigned char counter_7509[0x4];
unsigned char init_7510[0x4];
unsigned char count_7867[0x4];
unsigned char init_7868[0x4];
unsigned char MonicaRotationFlag[0x4];
unsigned char old_viewmode_8715[0x4];
unsigned char init_8716[0x4];
unsigned char old_chrid_8718[0x4];
unsigned char init_8719[0x4];
unsigned char MenuItemSelectMode[0x8];
unsigned char at_9093[0x8];
unsigned char ItemSelectPtr[0x4];

// Uninitialised data (.bss)
unsigned char MenuItemCmdRet[0x20];
unsigned char MenuAskParam[0xA0];
unsigned char MenuUserParam[0x20];
unsigned char MainCharaReadStack[0x30];
unsigned char MainCharaReadBuffer[0x10];
unsigned char MenuLevelUpMan[0x190];
unsigned char MenuItemCursorInfo[0x10];
unsigned char BuildUpFormInfoIndex[0x30];
unsigned char BuildUpFormInfoStatusVol[0x30];
unsigned char TrushMesCls[0x10];
unsigned char MenuItemMainMemory[0x30];
unsigned char MenuItemBGDataMemory[0x30];
unsigned char MenuItemMemory[0x30];
unsigned char MenuItemMemory2[0x30];
unsigned char MenuCharaLoadStack[0x30];
unsigned char BuildUpWeaponInfo[0x50];
unsigned char SpectolInfoStay[0x70];
unsigned char SepectolFusionBeforeAfterCheck[0x70];
unsigned char save_spectol_fusion_param[0x20];
unsigned char SpectolTransBefore[0x70];
unsigned char at_1557[0x10];
unsigned char fusion_ambient[0x10];
unsigned char fusion_color_ang[0x10];
unsigned char MenuWeaponBasePos[0x10];
unsigned char at_2333__3[0x10];
unsigned char at_3407[0x10];
unsigned char at_3792__2[0x20];
unsigned char MenuMoveTempGameDataUsed[0x70];
unsigned char at_4406[0x20];
unsigned char at_4423__2[0x10];
unsigned char at_4510[0x10];
unsigned char at_5532[0x18];
unsigned char BuildUpNameXY[0x18];
unsigned char at_5774[0x30];
unsigned char class_menu_item_info[0x370];
unsigned char MenuDebugStack[0x30];
unsigned char at_7650[0x10];
unsigned char at_7688[0x10];
unsigned char MonicaRotationData[0x10];
