#include "common.h"
#include "menusys.hpp"
#include <cstring>

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", DrawTrushMenuMessage__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", __ct__14CBaseMenuClassFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetTexBlock__14CBaseMenuClassFPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", DeleteTexBlock__14CBaseMenuClassFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemCommnadSelectPrepare__14CBaseMenuClassFP13CGameDataUsedii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemMoveItemCommand__14CBaseMenuClassFP13CGameDataUsediiP16CMenuPosDataFormi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemCommandSelect__14CBaseMenuClassFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetItemCmdMsgPos__14CBaseMenuClassFPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuHowMuchNumSelect__FiP13CGameDataUsedi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemAskMode_HowMuch__14CBaseMenuClassFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckTrushWeapon__FP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckSpectolFusion__14CBaseMenuClassFP13CGameDataUsediP16CMenuPosDataForm);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", UpdataInfoSpectolBreakItem__FP7CDC2MesP13CGameDataUsedi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckEquipFishRod__FP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", IsSpectolTrans__14CBaseMenuClassFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", IsSpectolFusion__14CBaseMenuClassFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", IsDispTrushCommand__FP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", IsTrush__14CBaseMenuClassFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", IsItemUseNum__14CBaseMenuClassFiiiP13CGameDataUsedP14CItemUseTarget);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SelectInGiftBox__14CBaseMenuClassFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetConditionHowMuchBoard__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetAskHowMuchItemNum__14CBaseMenuClassFP18MENU_SWAPITEM_INFOP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetAskParam__14CBaseMenuClassFP17MENU_ASKMODE_PARA);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", ExeScript__14CBaseMenuClassFPc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", ExtendCommand__14CBaseMenuClassFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SelectMakeObject__14CBaseMenuClassFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", IsAskEnd__14CBaseMenuClassFiP16CMenuPosDataForm);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", FadeInMenu__14CBaseMenuClassFif);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", FadeOutMenu__14CBaseMenuClassFif);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", FadeCheckMenu__14CBaseMenuClassFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetPreCmdTrush__FP14CBaseMenuClassiP13CGameDataUsedP16CMenuPosDataForm);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetPreCmdSpectolBreak__FP14CBaseMenuClassiP16CMenuPosDataFormP13CGameDataUsedP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetPreCmdGiftBoxSelect__FP14CBaseMenuClassP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckFishCondition__Fv);
void CMENU_USERPARAM::Initialize(void) {
    (*(s32 *)((u8 *)this + 0x4)) = 0;
    (*(s32 *)((u8 *)this + 0x0)) = 0;
    (*(s32 *)((u8 *)this + 0x8)) = 0;
    (*(s32 *)((u8 *)this + 0xc)) = 0;
    (*(s32 *)((u8 *)this + 0x10)) = 0;
    (*(s32 *)((u8 *)this + 0x14)) = 0;
}
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", AttachInfo__15CMENU_USERPARAMFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", Initialize__17MENU_ASKMODE_PARAFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", __ct__17MENU_ASKMODE_PARAFv);
void MENU_SWAPITEM_INFO::Set(s32 a, s32 b, s32 c, s32 d) {
    *(s16 *) ((u8 *) this + 2) = a;
    *(s16 *) ((u8 *) this + 4) = b;
    *(s16 *) ((u8 *) this + 6) = c;
    *(s16 *) this = d;
}
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", IsEnableChangeRoboParts__FP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetSpectolInfo__FP13CGameDataUsedP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", InitSpectol__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", AfterSpectolFusion__FP13CGameDataUsedP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", FusionColor__FiiPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SpectolFrameCalc__FP12CActionCharai);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", TransSpectolDataSave__FP13CGameDataUsedi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckNowRoboUseCapacity__FPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", ExchangeItemInfoMake__FP18MENU_SWAPITEM_INFOPA4_iii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuCheckLine__FPiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuKeySelectCheck__FiPiPiiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuListKeyCheck__FiPiPiiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuGlidKeyCheck__FiPiPiPiPiPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuListSelectKeyCheck__Fii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemBrdKey__FiPiPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuDataSwap__FP13CGameDataUsedP13CGameDataUsedi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", Initialize__12CMenuKeyFuncFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", AttachFuncData__12CMenuKeyFuncFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetActiveCharaNo__12CMenuKeyFuncFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuPosStep__12CMenuKeyFuncFPiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuSetPos__12CMenuKeyFuncFii);
void CMenuKeyFunc::MenuPosStop(void) {
    *(u8 *)(*(u8 **)((u8 *)this + 0x138) + 3) = 1;
    *(u8 *)(*(u8 **)((u8 *)this + 0x13C) + 3) = 1;
}
void CMenuKeyFunc::MenuPosPlay(void) {
    *(*(u8 **) ((u8 *) this + 0x138) + 3) = 0;
    *(*(u8 **) ((u8 *) this + 0x13C) + 3) = 0;
}
void CMenuKeyFunc::SetMoveMethod(s32 arg0) {
    *(u8 *) (*(u8 **) ((u8 *) this + 0x138) + 0x20) = arg0;
    this->SetWakuMoveMethod(arg0);
}
void CMenuKeyFunc::SetWakuMoveMethod(s32 arg0) {
    *(u8 *) (*(u8 **) ((u8 *) this + 0x13C) + 0x20) = arg0;
}
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetItemPos__12CMenuKeyFuncFPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetWakuType__12CMenuKeyFuncFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetWakuWH__12CMenuKeyFuncFiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetVibeCnt__12CMenuKeyFuncFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetVibeR__12CMenuKeyFuncFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetCursorPos__12CMenuKeyFuncFPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CursorFadeIn__12CMenuKeyFuncFfi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CursorFadeOut__12CMenuKeyFuncFfi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", EnableSwapNowPos__12CMenuKeyFuncFP18MENU_SWAPITEM_INFO);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetItemAll__12CMenuKeyFuncFP13CGameDataUsedP18MENU_SWAPITEM_INFO);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetItemCommandMsg__FP13CGameDataUsedP17MENU_ASKMODE_PARAii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetItemCommandMsg__FP13CGameDataUsedPiPUiPsPsii);
void CMenuKeyFunc::SelDataInit(void) {
    (*(s32 *)((u8 *)this + 0x4)) = 0;
    (*(s32 *)((u8 *)this + 0x8)) = 0;
    (*(s32 *)((u8 *)this + 0x78)) = (*(s32 *)((u8 *)this + 0x70));
    (*(s32 *)((u8 *)this + 0x7c)) = (*(s32 *)((u8 *)this + 0x74));
    (*(s8 *)((u8 *)this + 0x2)) = 0;
}
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckSelectKey__12CMenuKeyFuncFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckLRKey__12CMenuKeyFuncFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuCheckPushButton__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", ConvertCheckPushButton__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckPushButton__12CMenuKeyFuncFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckAnalogKey__12CMenuKeyFuncFiPf);
u8 CMenuKeyFunc::CheckKeyInput(void) {
    if ((*(u8 *)((u8 *)this + 0x1)) == 0) {
        (*(s32 *)((u8 *)this + 0x4)) = 0;
        (*(s32 *)((u8 *)this + 0x8)) = 0;
    }
    if ((*(s32 *)((u8 *)this + 0x4)) != 0) {
        (*(u8 *)((u8 *)this + 0x2)) = 1;
    }
    return (*(u8 *)((u8 *)this + 0x2));
}
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetDebugInputKey__12CMenuKeyFuncFRiRi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuSwapItem__12CMenuKeyFuncFP13CGameDataUsedP18MENU_SWAPITEM_INFOib);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetGameDataUsedForSWAPINFO__FP18MENU_SWAPITEM_INFO);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", ReturnItemMenu__12CMenuKeyFuncFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", InitHaveData__12CMenuKeyFuncFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetHaveItemInfo__12CMenuKeyFuncFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", menu_inputkey_limmit_check_line__12CMenuKeyFuncFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", menu_inputkey_limmit_check_glid__12CMenuKeyFuncFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckMoveSelect__12CMenuKeyFuncFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", FadeOutMenuBGMVol__12CMenuKeyFuncFii);
void CMenuKeyFunc::FadeInMenuBGMVol(s32 arg0) {
    (*(s32 *)((u8 *)this + 0x154)) = arg0;
    (*(s16 *)((u8 *)this + 0x158)) = (*(s32 *)((u8 *)this + 0x150));
    (*(s16 *)((u8 *)this + 0x15a)) = 1;
}
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", StepMenuBGM__12CMenuKeyFuncFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckEnableHaveItemNum__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuEquipCameraSetEnv__FP12CActionCharaP9mgCCameraii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuPosFormValueSetWeapon__FP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuFormUpdataAttachInfo__FP16CMenuPosDataFormP13CGameDataUsediiPs);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuPosFormValueSetFishingRod__FP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", Initialize__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetEquipListNo__13CMenuItemInfoFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckEquipListNo__13CMenuItemInfoFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckSoundLoad__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SearchNowPosItemExist__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", IsCancelNoneLoadItem__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", IsCancelLoadItem__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SaveViewWeaponStatus__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckViewWeaponStatus__13CMenuItemInfoFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", ReturnActiveCharaViewMode__13CMenuItemInfoFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", NextModeBuildUpInfo__13CMenuItemInfoFP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", EquipDirect__13CMenuItemInfoFiP13CGameDataUsedRi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckLoadInfo__13CMenuItemInfoFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", ItemCmdAfter__13CMenuItemInfoFiP16ITEMCMD_RET_PARA);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", IsAskExtend__13CMenuItemInfoFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuMoveItemPos__FPiPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CommonSetMoveItemClass__FPA4_i);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", EnterDataMenu__13CMenuItemInfoFPUi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetActiveCharaIDForItemCmd__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetActiveCharaNo__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", ExitEnd__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", AttachFormInfo__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuModeMalloc__13CMenuItemInfoFP9mgCMemory);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CalcTex__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CalcCursorPosition__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", EffectDrawCheck__14CBaseMenuClassFP16CMenuPosDataForm);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemInit__FP9mgCMemoryPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemDebugKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemDebugDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", PushKey__13CMenuItemInfoFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", local_item_infoview_set__FP18MENUFORMPARTS_TYPEP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemCharaActWepInfoDraw__FP16CMenuPosDataFormP13CGameDataUsedii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemCharaViewCheck__FP10CHARA_DATAii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuPosFormValueSetCharaRobo__FP9ROBO_DATAi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuPosFormValueSetMonster__FP16MOS_CHANGE_PARAMP10CHARA_DATA);
s32 CheckBuildUp(CGameDataUsed *arg0, s32 *arg1, s32 *arg2, s32 *arg3) {
    if (arg0 != NULL) {
        return arg0->IsBuildUp(arg1, arg2, arg3);
    }
    return 0;
}
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", BuildUpWeaponTrans__FP13CGameDataUsedi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", BuildUpWeaponNameBoardDraw__FP11mgCDrawPrimffi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuWeaponBuildUpDraw__FRi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuWeaponStatusInfoFormSet__FP13CGameDataUsedP11CDataWeapon);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemSelectDiffer__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckLoadItemNo__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", ModelReadStart__13CMenuItemInfoFiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", WeaponBuildCheck__13CMenuItemInfoFP12CActionCharaii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", ModelReadEndCheck__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SearchEffectDisplayPosition__13CMenuItemInfoFPiP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetItemEffect__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", LRCheck__13CMenuItemInfoFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemInfoCursorSet__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuCharaStatusDraw__FRi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemInfoCursorDraw__FRi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", KeyStepLocal__13CMenuItemInfoFiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", KeyStep__13CMenuItemInfoFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", SetPtrList__11CItemSelectFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", GetExistThisPosData__11CItemSelectFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", CheckUse__11CItemSelectFP13CGameDataUsed);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", KeyStep__11CItemSelectFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", Draw__11CItemSelectFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemSelectInit__FP9mgCMemoryPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemSelectKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", MenuItemSelectDraw__Fv);

// Static initialiser (.init)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menusys", __sinit_menusys_cpp);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", WepStatusInfoStrTable__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", WepStatusInfoStatusVolStrTable__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", addtbl_2178__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2328__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", n_2667__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", human_tbl_2871__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", padtbl_3359__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", MenuCheckKey__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", focusnametbl__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3771__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3772__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", item_menu_argtbl__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", exename_4332__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4350__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4369__3__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4410__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4414__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4485__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4495__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4509__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", ItemMenuFormNameTbl__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", local_over_flow_baseposname__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", tbl_4981__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", plist_4982__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", tbl_5293__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5458__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5531__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5534__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5556__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", waku_infotbl_5836__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", wakutypeTbl_5837__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", dbox_path_6083__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", table_6164__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", attrtable_6472__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6480__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", stchar_6508__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", whptbl_7376__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", backboard_table_x_7625__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", mos_repeat_table_x_7694__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", strtbl_7727__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", argtblno_7927__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", sel_7928__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", conv_7932__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", robo_stand_pos_8151__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", effparamtbl_8275__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", status_table_8427__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", xytable_8428__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", xytable_wep_8429__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", draw_tbl_8453__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", imgtbl_8945__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", menu_item_swap_sndtbl__DATA);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_919__4__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_920__3__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_921__3__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_922__3__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_923__4__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_924__3__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_925__3__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_926__3__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_927__3__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_928__3__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_929__4__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_930__4__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_931__3__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_932__3__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_933__4__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_934__3__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_935__3__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_936__4__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_937__3__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_938__3__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_1462__3__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_1493__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2545__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2546__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2547__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2548__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2549__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2550__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2584__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2585__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2651__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3316__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3744__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3745__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3746__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3747__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3748__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3749__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3750__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3751__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3774__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3775__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3822__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3823__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3824__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3825__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3826__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3827__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3828__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3829__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3893__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3894__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3895__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_3924__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4333__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4334__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4335__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4659__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4660__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4661__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4662__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4663__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4664__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4665__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4666__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4667__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4668__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4669__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4670__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4671__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4672__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4673__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4674__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4950__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4951__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4952__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4953__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4954__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4955__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4956__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4957__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4958__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4967__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4968__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4969__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4970__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4971__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4972__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4973__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4974__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4975__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4983__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4984__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4985__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5022__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5130__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5131__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5132__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5133__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5134__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5210__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5211__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5259__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5260__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5261__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5262__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5263__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5264__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5265__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5266__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5267__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5268__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5269__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5270__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5271__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5272__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5273__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5274__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5275__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5276__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5277__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5278__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5279__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5280__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5281__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5282__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5283__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5757__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5758__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5759__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5763__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5760__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5879__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5880__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5881__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5882__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5883__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6011__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6012__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6013__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6014__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6015__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6016__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6424__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6473__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6474__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6475__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6476__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6477__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6478__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6479__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6509__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6510__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6511__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6512__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6513__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6514__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6515__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6516__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6517__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6518__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6519__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6520__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6760__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6761__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6762__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6763__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6764__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6765__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6766__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6767__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6768__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6769__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6770__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6771__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6772__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6773__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6774__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6775__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6776__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6777__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6778__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6779__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6780__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6781__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6782__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6783__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6784__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6785__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6786__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6787__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6788__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6789__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6790__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6791__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6792__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6793__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6794__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6795__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6796__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6797__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6798__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6799__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6800__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6801__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6802__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6803__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6804__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6805__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6806__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6807__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6808__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6809__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6810__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6811__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6812__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6813__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6814__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7342__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7343__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7344__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7345__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7346__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7347__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7349__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7348__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7438__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7439__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7440__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7441__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7442__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7443__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7478__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7534__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7535__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7536__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7537__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7538__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7539__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7540__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7541__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7560__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7561__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7562__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7563__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7564__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7728__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7729__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7730__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7731__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7732__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7968__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8083__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8084__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8199__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8201__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8200__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8315__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8421__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8711__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8819__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8820__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8821__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8822__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8823__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8825__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8824__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8869__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8946__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8947__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_8948__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_9032__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_9033__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_9179__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_9215__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_9216__DATA);

// Static initialiser table (.ctor)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", D_0037B034__DATA);

// Virtual tables (.vtables)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", __vt__11CItemSelect__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", __vt__13CMenuItemInfo__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", __vt__14CBaseMenuClass__DATA);

// Small initialised data (.sdata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", MenuRoboEquipTable__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", MenuItemBoardTotalNum__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", MenuItemBoardTotalLine__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", MenuWeaponEnvSetListNo__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_1232__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", wakutbl_1411__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", tartbl_1412__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", trans_spectol_pos__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", trans_spectol_posold__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", trans_spectol_rgb__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", SpectolFramePosValue__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", ret_tbl1_2511__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_2512__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", menu_camera_reference_id__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", menu_camera_reference_no__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", tbl_4094__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", menuitem_initviewtbl__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", menuitem_initmenumode__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_4469__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", OverFlowFormName__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", itemmenu_calcmode_tbl_5410__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_5563__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", MenuDebugModel_AdjustFlag__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_6438__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", backboard_table_y_7626__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", backboard_table_w_7627__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", backboard_x_repeat_drawnum_7628__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", backboard_y_repeat_drawnum_7629__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_7695__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", cnttbl_8130__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", SameviewmodeTable_8406__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menusys", at_9055__DATA);

// Small uninitialised data (.sbss)
INCLUDE_BSS(MainCharaReadStackReadAdr, 0x4);
INCLUDE_BSS(MenuRepairMan, 0x4);
INCLUDE_BSS(MenuItem_ItemBoardTopLine, 0x4);
INCLUDE_BSS(MenuItem_ItemBoardTopSelect, 0x4);
INCLUDE_BSS(menu_chara_activeItem_limmit_check, 0x8);
INCLUDE_BSS(MenuSpectolSatusCheckForm, 0x4);
INCLUDE_BSS(MenuSpectolSatusCheckBGFadeForm, 0x4);
INCLUDE_BSS(TrushMesWindowFlag, 0x4);
INCLUDE_BSS(ActiveMenuWeaponCharaRange, 0x4);
INCLUDE_BSS(MenuWeaponEnvSetChara, 0x4);
INCLUDE_BSS(MenuStatusMode, 0x4);
INCLUDE_BSS(MenuStatusTex, 0x8);
INCLUDE_BSS(MenuItemUseTarget, 0x8);
INCLUDE_BSS(CMenuItemInfoPt, 0x8);
INCLUDE_BSS(MenuEffect, 0x8);
INCLUDE_BSS(MenuItemSpectolTransSoundBuffer, 0x8);
INCLUDE_BSS(SpectolInfo, 0x8);
INCLUDE_BSS(SpectolFusion_LeftOrRight, 0x4);
INCLUDE_BSS(SpectolFusionTargetChara, 0x4);
INCLUDE_BSS(save_spectol_fusion_spstatus, 0x4);
INCLUDE_BSS(MenuItemCmdArgPos, 0x4);
INCLUDE_BSS(MenuItemCommand_RoboPackBreakFlag, 0x4);
INCLUDE_BSS(cmd_counter_1048, 0x4);
INCLUDE_BSS(init_1049, 0x4);
INCLUDE_BSS(MenuItemCommandDir, 0x4);
INCLUDE_BSS(at_1385__2, 0x8);
INCLUDE_BSS(MenuHowHaveMuchNum, 0x4);
INCLUDE_BSS(SpectolBreakNum_Limit, 0x4);
INCLUDE_BSS(SpectolBreakNum, 0x4);
INCLUDE_BSS(SpectolBreakSpPoint, 0x4);
INCLUDE_BSS(at_1545, 0x4);
INCLUDE_BSS(trans_spectol_cnt, 0x4);
INCLUDE_BSS(spegetflag, 0x4);
INCLUDE_BSS(SpectolFrame, 0x4);
INCLUDE_BSS(MenuSpectolTransPos, 0x4);
INCLUDE_BSS(itemmenu_chr_rotflag, 0x4);
INCLUDE_BSS(sndflag_1665, 0x4);
INCLUDE_BSS(init_1666, 0x4);
INCLUDE_BSS(at_1685, 0x8);
INCLUDE_BSS(MenuTrushNum, 0x4);
INCLUDE_BSS(fusion_color_val, 0x4);
INCLUDE_BSS(SpectolFrameScaleAngle, 0x4);
INCLUDE_BSS(SpectolFrameFadeAlpha, 0x4);
INCLUDE_BSS(at_2345__2, 0x8);
INCLUDE_BSS(at_2346__2, 0x8);
INCLUDE_BSS(at_2564, 0x8);
INCLUDE_BSS(at_3791__2, 0x8);
INCLUDE_BSS(count_time_3839, 0x4);
INCLUDE_BSS(init_3840, 0x4);
INCLUDE_BSS(FxScriptManPauseFlag, 0x4);
INCLUDE_BSS(debug_common_data, 0x4);
INCLUDE_BSS(view_weapon_flag, 0x4);
INCLUDE_BSS(OldViewWep, 0x4);
INCLUDE_BSS(NewViewWep, 0x8);
INCLUDE_BSS(MenuRepairTargetWeaponPos, 0x8);
INCLUDE_BSS(at_4365__2, 0x8);
INCLUDE_BSS(Effect_Counter_4682, 0x4);
INCLUDE_BSS(init_4683, 0x4);
INCLUDE_BSS(BuildEndFlag_4703, 0x4);
INCLUDE_BSS(init_4704, 0x4);
INCLUDE_BSS(at_5026, 0x8);
INCLUDE_BSS(Tex_BuildUpBoard, 0x4);
INCLUDE_BSS(Robo_Sound_ID_Save, 0x4);
INCLUDE_BSS(checkmoveFlag_5411, 0x4);
INCLUDE_BSS(init_5412, 0x4);
INCLUDE_BSS(at_5573, 0x4);
INCLUDE_BSS(MenuDebugModelDrawFlag, 0x4);
INCLUDE_BSS(at_5769, 0x8);
INCLUDE_BSS(at_5782, 0x8);
INCLUDE_BSS(at_5829, 0x8);
INCLUDE_BSS(MenuDebugSize, 0x4);
INCLUDE_BSS(MenuDebugItemModel, 0x4);
INCLUDE_BSS(MenuDebugCamera, 0x8);
INCLUDE_BSS(at_6133, 0x8);
INCLUDE_BSS(cnt_6161, 0x4);
INCLUDE_BSS(init_6162, 0x4);
INCLUDE_BSS(at_6176, 0x8);
INCLUDE_BSS(at_6220, 0x8);
INCLUDE_BSS(at_6234, 0x8);
INCLUDE_BSS(at_6256, 0x8);
INCLUDE_BSS(at_6265, 0x8);
INCLUDE_BSS(testcnt_6298, 0x4);
INCLUDE_BSS(init_6299, 0x4);
INCLUDE_BSS(at_7021, 0x4);
INCLUDE_BSS(Save_AskParamInfo_7099, 0x4);
INCLUDE_BSS(fusion_blinkcnt_7120, 0x4);
INCLUDE_BSS(init_7121, 0x4);
INCLUDE_BSS(diffent_weapon_dispflag_7125, 0x4);
INCLUDE_BSS(init_7126, 0x4);
INCLUDE_BSS(WeaponWarningCounter, 0x4);
INCLUDE_BSS(counter_7509, 0x4);
INCLUDE_BSS(init_7510, 0x4);
INCLUDE_BSS(count_7867, 0x4);
INCLUDE_BSS(init_7868, 0x4);
INCLUDE_BSS(MonicaRotationFlag, 0x4);
INCLUDE_BSS(old_viewmode_8715, 0x4);
INCLUDE_BSS(init_8716, 0x4);
INCLUDE_BSS(old_chrid_8718, 0x4);
INCLUDE_BSS(init_8719, 0x4);
INCLUDE_BSS(MenuItemSelectMode, 0x8);
INCLUDE_BSS(at_9093, 0x8);
INCLUDE_BSS(ItemSelectPtr, 0x4);

// Uninitialised data (.bss)
INCLUDE_BSS(MenuItemCmdRet, 0x20);
INCLUDE_BSS(MenuAskParam, 0xA0);
INCLUDE_BSS(MenuUserParam, 0x20);
INCLUDE_BSS(MainCharaReadStack, 0x30);
INCLUDE_BSS(MainCharaReadBuffer, 0x10);
INCLUDE_BSS(MenuLevelUpMan, 0x190);
INCLUDE_BSS(MenuItemCursorInfo, 0x10);
INCLUDE_BSS(BuildUpFormInfoIndex, 0x30);
INCLUDE_BSS(BuildUpFormInfoStatusVol, 0x30);
INCLUDE_BSS(TrushMesCls, 0x10);
INCLUDE_BSS(MenuItemMainMemory, 0x30);
INCLUDE_BSS(MenuItemBGDataMemory, 0x30);
INCLUDE_BSS(MenuItemMemory, 0x30);
INCLUDE_BSS(MenuItemMemory2, 0x30);
INCLUDE_BSS(MenuCharaLoadStack, 0x30);
INCLUDE_BSS(BuildUpWeaponInfo, 0x50);
INCLUDE_BSS(SpectolInfoStay, 0x70);
INCLUDE_BSS(SepectolFusionBeforeAfterCheck, 0x70);
INCLUDE_BSS(save_spectol_fusion_param, 0x20);
INCLUDE_BSS(SpectolTransBefore, 0x70);
INCLUDE_BSS(at_1557, 0x10);
INCLUDE_BSS(fusion_ambient, 0x10);
INCLUDE_BSS(fusion_color_ang, 0x10);
INCLUDE_BSS(MenuWeaponBasePos, 0x10);
INCLUDE_BSS(at_2333__3, 0x10);
INCLUDE_BSS(at_3407, 0x10);
INCLUDE_BSS(at_3792__2, 0x20);
INCLUDE_BSS(MenuMoveTempGameDataUsed, 0x70);
INCLUDE_BSS(at_4406, 0x20);
INCLUDE_BSS(at_4423__2, 0x10);
INCLUDE_BSS(at_4510, 0x10);
INCLUDE_BSS(at_5532, 0x18);
INCLUDE_BSS(BuildUpNameXY, 0x18);
INCLUDE_BSS(at_5774, 0x30);
INCLUDE_BSS(class_menu_item_info, 0x370);
INCLUDE_BSS(MenuDebugStack, 0x30);
INCLUDE_BSS(at_7650, 0x10);
INCLUDE_BSS(at_7688, 0x10);
INCLUDE_BSS(MonicaRotationData, 0x10);
