#include "common.h"

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", InitMenuBGReadInfo2__FP17MENU_BGREAD_INFO2);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuLoadFileCheck__FPP17MENU_BGREAD_INFO2);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuBGReadInfo2Malloc__FP9mgCMemoryPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", ConvertCharaLoadDataPhase__Fii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", CheckBattleLoop__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", SetMenuLoadItemNo__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuMemoryDivide__FP9mgCMemoryPP9mgCMemoryi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuMemoryAdjust__FP9mgCMemoryP9mgCMemoryP9mgCMemoryi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", DeleteMonsterEffect__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", SetMessagePositionNPCForm__FP16CMenuPosDataFormP7CDC2Mes);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", AdjustNPCTalk__FP7CDC2MesP11CCharacter2);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", AttachForm__15CMenuChrCngMenuFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", EnterDataMenu__15CMenuChrCngMenuFPUc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", LoadNPCFaceData__15CMenuChrCngMenuFP9mgCMemoryi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", EnterNPCFaceData__15CMenuChrCngMenuFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", LoadBGNPCModel__15CMenuChrCngMenuFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", CheckBGNPCModel__15CMenuChrCngMenuFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", EditCharaPrepare__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", KeyChangeMain__15CMenuChrCngMenuFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", CalcTex__15CMenuChrCngMenuFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", CheckChrChange__15CMenuChrCngMenuFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuLocalLoop__15CMenuChrCngMenuFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", InitStarInfo__15CMenuChrCngMenuFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", UpdataLife__15CMenuChrCngMenuFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuCharaChangeStarDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuCharaChangeInit__FP9mgCMemoryPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuCharaChangeKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuCharaChangeDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", GetMonsterName__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", get_gajji_id_from_monster_progress_table__FiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", GetMonsterProgressTableNo__Fii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", get_monster_tbl_bajjilevel__FPiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", get_default_monster_progresstbl__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", GetMonsterModelFile__FiiPc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", AttachForm__14CMenuMosSelectFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MonsterScaleCheck__FP11CCharacter2);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MonsterEffectRead__FP9mgCMemoryii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MonsterEffectEnter__FP6CSceneP1i);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", CheckLoadBGMonster__14CMenuMosSelectFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", GetBajjiPosition__FP16CMenuPosDataFormiiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", CalcCursorPosition__14CMenuMosSelectFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", CalcTex__14CMenuMosSelectFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", KeyNormalMode__14CMenuMosSelectFiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuMonsterBoxInit__FP9mgCMemoryPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", KeyStep__14CMenuMosSelectFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuMonsterBoxKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuMonsterBoxDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuTimeStepEnvFunc__FP6CSceneP12CActionCharai);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuWeaponRealStepEnvFunc__FP12CActionCharai);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuItemCharaDataLoad__FP9mgCMemoryiPP17MENU_BGREAD_INFO2i);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuItemCharaDataLoadPack__FiP12CActionCharaP12CActionCharaiPUiP9mgCMemoryii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuItemCharaDataLoadEndCheck__FPP17MENU_BGREAD_INFO2P9mgCMemoryPP12CActionCharaiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuCharaSoundLoad__FP9mgCMemoryii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuCharaSoundEnter__FP6CSceneP12CActionCharai);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuItemChrLoad__FP9mgCMemoryiiP17MENU_BGREAD_INFO2i);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuItemChrLoadEndCheck__FP17MENU_BGREAD_INFO2P12CActionCharaP9mgCMemoryi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuItemRoboDataLoad__FP9mgCMemoryPP17MENU_BGREAD_INFO2i);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", DeleteOutLineMenu__FP12CActionCharai);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuItemRoboDataLoadEndCheck__FPP17MENU_BGREAD_INFO2P9mgCMemoryPP12CActionCharaii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuRoboPartsLightOff__FP8mgCFrame);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuMonsterLoadBG__FP9mgCMemoryPP17MENU_BGREAD_INFO2ii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuMonsterLoadBGCheck__FPP17MENU_BGREAD_INFO2PP12CActionCharaii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuItemCharaDataLoadEndCheckAfter__FPP17MENU_BGREAD_INFO2i);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", InitMainCharaBG__FiP9mgCMemoryi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", ReadMainCharaBG__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", KeyMainCharaBG__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", DrawMainCharaBG__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuNPCModelLoad__FP9mgCMemoryii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuNPCLoadCheck__FP12CActionCharaP9mgCMemoryi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", UpdateCostumeList__15CMenuCostumeSelFiUl);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", CosutmeSelDefaultSet__FiPs);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", LoadMenuData__15CMenuCostumeSelFP9mgCMemoryPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", KeyStep__15CMenuCostumeSelFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", Draw__15CMenuCostumeSelFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuCostumeInit__FP9mgCMemoryPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuCostumeKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MenuCostumeDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", GetMonsterBaseInfoForMonsterMemoIndex__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", InitMonsterInfo__12CMosBookMenuFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", SetMonsterInfo__12CMosBookMenuFP16BASE_MONSTER_TBL);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", InitEnd__12CMosBookMenuFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", Draw__12CMosBookMenuFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", KeyStep__12CMosBookMenuFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MonsterBookInit__FP9mgCMemoryPii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MonsterBookKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", MonsterBookDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", Set__9mgRect_s_Fssss);

// Static initialiser (.init)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menuchr", __sinit_menuchr_cpp);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", monster_progress_tbl);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", tbl_992);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", menu_robo_memorytbl);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", menu_chr_memorytbl);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", tbl_1233);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1372__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", nextIDtbl_1594);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", partt_2332);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", tbl_2483);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2629__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2691);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2696);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", overcode_3172);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", tbl_3186);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", posdef_3194);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", refdef_3195);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", tbl_3196);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", convert_table_3430);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", ghobitbl_3437);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3481);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", get_stringtbl_3557);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", tbl_3725);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", menu_load_chrpathtbl_3811);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", menu_infocfgname);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_4327);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", MonsterDataPath);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_4586);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", convtbl_4621);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_4728__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_4967__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", tbl_5016);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", infomsg_5256);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", putw_5262);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", monster_type_name);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", monster_jyakuten);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", monstere_file_template);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5452);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", stand_bit_5472);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", tiletbl_5573);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", under_brdtbl_5576);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", put_under_offset_5577);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", ic_5580);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", line_5595);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", wakutbl_5600);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", tbl_5848);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1078__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1104__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1131__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1132__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1133__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1134__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1135__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1171__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1172);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1173__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1174);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1175);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1176);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1177);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1178);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1179);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1180);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1181__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1234__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1235__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1236__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1237__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1276__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1277__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1278__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1279__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1280__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1281__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1282__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1283__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1284__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1285__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1304__6);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1319);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1361);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_1402__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2003__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2004__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2005__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2006__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2007__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2008__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2009);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2010);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2011);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2012);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2013);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2014);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2015);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2016);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2017);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2018__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2019__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2020__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2021__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2022);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2023);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2191__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2192__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2193__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2194__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2195__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2196__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2197__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2286);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2287);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2303__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2304);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2305);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2306);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2307);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2333__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2334__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2335__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2336);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2337);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2338);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2363);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2364);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2365);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2595__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2596__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2662__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2770);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2771);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2772);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2773);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2774);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2775);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2776__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2777);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2778);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2779);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2780);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2781);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2782);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2783);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2784);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2785);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2912);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2913__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2914);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2915);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2916);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2917);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2918);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2940);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2941);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2942);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2943);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2944);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3160__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3161__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3162__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3163__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3164__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3165__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3166__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3197);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3198);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3199__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3200);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3201__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3202__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3269);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3270);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3271);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3272);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3273);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3274);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3275);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3276);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3558);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3559);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3560);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3561);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3685);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3686);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3687);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3688);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3689);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3690);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3691);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3692);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3693);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3694);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3695);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3696);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3697);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3698);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3699);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3700);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3701);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3702);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3703);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3704);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3705);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3706);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3707);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3708);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3726__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3727__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3728__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3729__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3730__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3731__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3732__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3733__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3734__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3735);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3736);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3737);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3762);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3779);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3780);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3790);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3791__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3792__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3793__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3794__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3812);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3813);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3814);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3913);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3969);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3970);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_4123);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_4186__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_4276__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_4277);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_4278);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_4296);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_4517__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_4518);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_4519__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_4520);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_4548);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_4789);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_4790);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_4791);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_4868);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_4950__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5051);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5052);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5053);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5197);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5257);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5258);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5259__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5260__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5261__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5356);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5357);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5358);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5359);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5360);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5361);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5362);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5363);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5364);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5365);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5366);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5367);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5368);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5369);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5370);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5371);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5372);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5373);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5374);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5375);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5376);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5377);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5378);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5379);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5380);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5381);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5382);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5383);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5384);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5385);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5386);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5387);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5388);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5389);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5390);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5391);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5392);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5393);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5394);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5395);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5396);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5397);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5398);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5399);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5400);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5401);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5402);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5403);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5404);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5405);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5406);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5407);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5408);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5409);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5410__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5411__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5412__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5413__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5414__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5415__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5416__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5417__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5418__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5419__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5420__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5421__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5422__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5423);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5424__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5425);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5426);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5427);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5428);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5429);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5430);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5431);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5432);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5433);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5434);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5435);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5558__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5559__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5560__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5561);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5839);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_5893);

// Static initialiser table (.ctor)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", D_0037B05C);

// Virtual tables (.vtables)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", __vt__12CMosBookMenu);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", __vt__15CMenuCostumeSel);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", __vt__14CMenuMosSelect);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", __vt__15CMenuChrCngMenu);

// Small initialised data (.sdata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", MenuSoundCharaNo);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", msgtbl1_1732);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", se_sndtbl_1749);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", cursor_revtbl_2237);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_2288);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", max_3170);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", viewnum_3171);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", menu_chara_chrtbl);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", menu_chara_cfg_chrtbl);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_3810);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", pathtbl_3836);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", at_4158);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", convItoPhase_4229);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", monster_load_id);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", NowReadMainCharaNo);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", NowReadMainCharaMonsterNo);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", phasetbl_5119);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", tilergba_5203);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menuchr", convtbl_5238);

// Small uninitialised data (.sbss)
unsigned char MorattaStack[0x4];
unsigned char MenuLoadInfo[0x8];
unsigned char MenuCharaChangeBase_Tex[0x4];
unsigned char MenuCharaChangeCLUT_Tex[0x4];
unsigned char MenuCharaChangeStar_Tex[0x4];
unsigned char MenuCharaChangeCLUT[0x4];
unsigned char MenuCharaChangePosDataCfgBuffer[0x4];
unsigned char menu_debug_npcselect[0x4];
unsigned char menu_debug_npc_decide[0x4];
unsigned char MenuDebugChangeSelectMode[0x4];
unsigned char MenuDebugCharaChangeSelect[0x4];
unsigned char SelectedCmdNo_1415[0x4];
unsigned char init_1416[0x4];
unsigned char at_1650__2[0x4];
unsigned char at_1684__2[0x8];
unsigned char MenuGetPartySeFlag[0x8];
unsigned char at_2232[0x8];
unsigned char at_2289__2[0x8];
unsigned char ChrChangMenuPt[0x8];
unsigned char at_2371__4[0x8];
unsigned char MenuMosTexture[0x4];
unsigned char CharaSndBuffer[0x4];
unsigned char mos_effect_henge_param[0x4];
unsigned char mos_effect_read_num[0x4];
unsigned char MenuMosSelectPtr[0x4];
unsigned char menu_debug_select__2[0x4];
unsigned char select_monster_save_3371[0x4];
unsigned char init_3372__2[0x4];
unsigned char at_3412[0x4];
unsigned char at_3440[0x4];
unsigned char NowReadMainCharaPhase[0x4];
unsigned char NowReadMainChara[0x4];
unsigned char NowMainCharaChngTex[0x4];
unsigned char NowMainCharaChngTexMoveX[0x4];
unsigned char NowMainCharaChngTexMovePhase[0x4];
unsigned char NowMainCharaFrameImage[0x4];
unsigned char NowMainCharaChngStatusBit[0x4];
unsigned char MenuNPCLoadFlag[0x4];
unsigned char MenuPartyNPCModelReadBuffer[0x4];
unsigned char MenuCosutumeLoadPhase[0x4];
unsigned char CostumeAttr[0x8];
unsigned char MenuCosPtr[0x4];
unsigned char MonsterBookPtr[0x4];
unsigned char Tex_MBook[0x4];
unsigned char Tex_MBase[0x4];
unsigned char Tex_MBg[0x4];
unsigned char MonsterBookBootMode[0x4];
unsigned char MenuMosBookPtr[0x4];

// Uninitialised data (.bss)
unsigned char MenuCharaBuild2[0x1C];
unsigned char D_01F3C7FC[0x4];
unsigned char MenuActionChara[0x20];
unsigned char MenuActionCharaBuffer[0x150];
unsigned char MenuLoadItemNo[0x20];
unsigned char at_1083__2[0x20];
unsigned char MenuChangeMemory[0x30];
unsigned char MenuChangeNpcMemory[0x30];
unsigned char ChrChangeInitTextureStack[0x30];
unsigned char at_1806__2[0x20];
unsigned char at_2372__4[0x20];
unsigned char at_2674[0x80];
unsigned char at_2675[0x80];
unsigned char at_2676[0x80];
unsigned char MenuMonChangeLoadStack[0x30];
unsigned char MenuMosBuildStack[0x30];
unsigned char MenuMosLoadStack[0x30];
unsigned char MenuMonsterBGInfo[0x20];
unsigned char mos_effect_readbuff1[0x10];
unsigned char mos_effect_readbuff2[0x10];
unsigned char mos_effect_readbuff1_size[0x10];
unsigned char mos_effect_readbuff2_size[0x10];
unsigned char at_3054__2[0x20];
unsigned char at_3511[0x20];
unsigned char at_3529[0x20];
unsigned char at_3554[0x20];
unsigned char SwordEffectStack[0x30];
unsigned char at_3974[0x20];
unsigned char at_3975[0x20];
unsigned char at_3993[0x20];
unsigned char at_4300__2[0x20];
unsigned char at_4328[0x20];
unsigned char at_4329[0x20];
unsigned char script_file_name[0x20];
unsigned char at_4565[0x20];
unsigned char at_4585[0x10];
unsigned char NowMainReadPosition[0x10];
unsigned char NowMainReadRotation[0x10];
unsigned char MosBookStack[0x30];
unsigned char at_5482[0x20];
