#include "common.h"

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", MenuScreenBlackBeltSet__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", GetMenuLoopType__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", CheckTrushMenu__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", menu_GetSaveDataDungeon__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", menu_GetBattleAreaScene__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", GetMenuSysData__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", CheckBitFlagMenu__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", CheckShortFlagMenu__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", CheckStartChapter8__FP9CSaveData);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", InitMenuEtcSpecialFlag__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", SetMenuEtcFlag__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", GetMenuEtcFlag__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", GetMenuPrim__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", MenuMainImageDataEnter__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", SetMenuFrameRate__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", SetMenuKeyCtrlEnv__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", DisablePadReset__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", MenuMainInit__FP13MENU_INIT_ARG);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", MenuMainExit__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", MenuMainLoop__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", MenuMainKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", MenuMainDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", NextMenuInit__FiP9mgCMemoryPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", MenuCamInit__Ff);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", MenuWorldTrans__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", MenuPolygonSetEnv__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", MenuPolygonEnvReset__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", GetMenuCfgFileName__Fii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", GetMenuMainMessageBuffer__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", GetMenuMainIMGPtr__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", GetMenuMainPosCfgBuffer__FPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", SetCommonMenuModeID__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", GetCommonMenuModeID__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", CursorSaveOptionState__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", ReturnMenuIntern__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", MenuAreaBoardNameStep__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", CheckEventDay__FPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", MakeMenuTopic__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", DrawMenuTopic__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", MenuInternInit__FP9mgCMemoryii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", Initialize__10CMenuInterFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", MenuCommonBaseDataEnter__FP9mgCMemoryPUiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", MenuBaseTextureReEnter__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", InitEnd__10CMenuInterFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", PushOk__10CMenuInterFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", ReadBGTexture__10CMenuInterFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", MenuInternSelectKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", MenuInternSelectDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", CopyActiveItemAndWeapon__Fii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", CopyActiveIconTexture__FPP10mgCTextureiPUi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", MenuDebugModeDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", BookshelfMessageMake__FP6ClsMesiii);

// Static initialiser (.init)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/menumain", __sinit_menumain_cpp);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", light_1062);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", lightcolor_1063);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", menu_keyfunctbl);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", menu_drawfunctbl);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", menu_basedgRef);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", menu_basedgCamPos);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", CommonMenuModeID);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1699__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", menu_maintopic_colortbl);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", menu_maintopic_colortbl_shadow);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", topic_tbl_1777);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", filetbl_2141);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", monster_table);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1028__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1440__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1598__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1599__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1621__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1624__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1625__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1630__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1635__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1640);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1683);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1684);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1736__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1737);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1738);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1739);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1740);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1741);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1742);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1778);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1779);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1780__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1781);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1782);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1783);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1784__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1785);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1786__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1787__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1788__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1789__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1859);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1930);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1931);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1932);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1933);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1934);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1935);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1936);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1937);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1938);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1956);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1957);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1958);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_2003);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_2004__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_2142__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_2143__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_2144__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_2145__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_2146__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_2329);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_2330);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_2331);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_2332);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_2333__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_2334__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_2335);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_2344);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_2345);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_2439);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_2440);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_2450);

// Static initialiser table (.ctor)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", D_0037B030);

// Small initialised data (.sdata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", MenuPrim);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", MenuPrevEndCode);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", MenuBGTextureBlock);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", MenuItemIconTextureBlock);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1514__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", menu_main_cfgname_1620);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", acttbl_1682);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", MenuTopicAlpha);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", fname_1858);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1865);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1866);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", at_1867);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/menumain", loopnumtbl_2360);

// Small uninitialised data (.sbss)
unsigned char MenuMainScene[0x4];
unsigned char MenuActiveSaveData[0x4];
unsigned char MenuUserDataManPtr[0x4];
unsigned char MenuSystemDataPtr[0x4];
unsigned char MenuConfigPtr[0x4];
unsigned char MenuSaveDataDungeonPtr[0x4];
unsigned char MenuFishAquarium[0x4];
unsigned char MenuNowMapNo[0x4];
unsigned char MenuNowMapType[0x4];
unsigned char MenuMainSubDataPackAdr[0x4];
unsigned char CMenuInterPt[0x4];
unsigned char MenuInterMes[0x4];
unsigned char MenuInterMesDrawFlag[0x4];
unsigned char MenuAreaBrdForm[0x4];
unsigned char MenuTimeBrdForm[0x4];
unsigned char MenuAreaName[0x4];
unsigned char MenuNowTime[0x4];
unsigned char SndPortVol_Enemy[0x4];
unsigned char ItemOverFlowCheckFlag[0x4];
unsigned char MenuDrawEnv[0x4];
unsigned char MenuCommonInfo[0x4];
unsigned char MenuLoopType[0x4];
unsigned char MenuEtcSpecialCode[0x4];
unsigned char MenuEtcInfo[0x8];
unsigned char MenuMoveItemPtr[0x4];
unsigned char MenuBGMVolume_Save[0x4];
unsigned char MenuFormMI2[0x4];
unsigned char MenuItemCommandCounter[0x4];
unsigned char menu_debug_flag[0x4];
unsigned char MenuTopicAlphaCalc[0x4];
unsigned char TopicTex[0x4];
unsigned char old_light_menu[0x4];
unsigned char HatumeiMenuOkFlag[0x4];
unsigned char WorldMapOkFlag[0x4];
unsigned char ManualMenuOkFlag[0x4];
unsigned char DngMoveMenuOkFlag[0x4];
unsigned char MenuDoubleDrawCheck[0x4];
unsigned char refresh_cnt_1523[0x4];
unsigned char init_1524[0x8];
unsigned char at_1697__2[0x8];
unsigned char at_1698__2[0x8];
unsigned char MenuTopicType[0x4];
unsigned char MenuTopicLength[0x4];
unsigned char TopicFontX[0x8];
unsigned char at_1976[0x8];
unsigned char at_2209__3[0x8];

// Uninitialised data (.bss)
unsigned char MenuMainStack[0x30];
unsigned char MenuMainStack_Next[0x30];
unsigned char CMenuInterStatic[0x20];
unsigned char MenuPrimFix[0x120];
unsigned char MenuItemUse[0x20];
unsigned char MenuMainTextureReadBuf[0x30];
unsigned char MenuSoundBuffer[0x30];
unsigned char MenuArg[0xA0];
unsigned char menu_old_chara_position[0x10];
unsigned char menu_old_chara_rotation[0x10];
unsigned char workchr_1622[0x60];
unsigned char CommonMenuModeID2[0x20];
unsigned char TopicFont[0xC0];
unsigned char at_2351[0x20];
