#include "common.h"

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgPerformanceMeter__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetPerformanceMeterFlag__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", VSyncCallBack__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgInitVSyncCallBack__FPFi_i);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetRotateThread__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", WaitVSync__Fii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetVSyncCount__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", GetScreenSize__FiPiPiPiPiPiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgInit__Fii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgInitVif1Packet__FP1P1i);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetPacketBuffer__FP9mgCMemoryP9mgCMemory);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetDataBuffer__FP9mgCMemoryP9mgCMemoryi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetDataBuffer__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetTopVRAMAddress__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetNowFrameRate__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgBeginFrame__FP14mgCDrawManager);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgBeginPacket__FP14mgCDrawManager);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgBeginDraw__FP9mgCMemoryPiP14mgCDrawManager);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgEndDraw__FP14mgCDrawManager);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgPreEndDraw__FP14mgCDrawManager);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgEndDrawReloadTexture__FiP14mgCDrawManager);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgEndDraw__FiP14mgCDrawManager);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgStoreFrameImage__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgEndFrame__FP14mgCDrawManager);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSendPacket__FP14mgCDrawManager);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgEndPacket__FP14mgCDrawManager);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgWaitFrame__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgDraw__FP8mgCFrame);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgDrawDirect__FP8mgCFrame);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgDrawDirect__FP9mgCVisualPA4_f);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgDrawDirectStart__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgDrawDirect2__FP8mgCFrame);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgDrawDirectEnd__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetDrawRect__FP8mgCFrameP9mgVu0FBOX);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgBeginDrawShadow__FP10mgCTextureP10mgCTexture);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgEndDrawShadow__FP10mgCTextureP10mgCTexture);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetRenderInfo__Ffff);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetProjection__Ff);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetProjection__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetBackGround__FPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetBackGround__Fffff);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgInitLighting__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgInitActiveLighting__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgActiveLighting__Fii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetLight__FPA4_fPA4_f);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetLight__FPA4_fPA4_f);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetLight__FiPfPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetAmbient__FPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetAmbient__FPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetPlight__FiPfPfff);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetPlight__FiP13mgPOINT_LIGHT);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetPlight__FiP13mgPOINT_LIGHT);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgResetPlight__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetViewMatrix__FPA4_fPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetDropShadowMatrix__FPfPfPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgFogEnable__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetFogEnable__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgPlightEnable__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetPlightEnable__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetFogParam__FffUcUcUcff);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetFogParam__FP11mgFOG_PARAM);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetFogParam__FP11mgFOG_PARAM);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetAllScissorFlag__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgFlushRenderInfo__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetPkTextureRepeat__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetPkTextureRepeat__F10sceGsClamp);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetPkFrameBuffer__FP10mgCTexture);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetPkFrameBuffer__Fiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetFrameBuffer__FP10mgCTexture);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetFrameBackBuffer__FP10mgCTexture);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetpDrawEnv__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetPkMoveImage__FP10mgCTexture9mgRect_i_P10mgCTextureiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetPkMoveImage__FP9sceGsTex09mgRect_i_P9sceGsTex0iii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetPkMoveImage__FP10mgCTexture9mgRect_i_P10mgCTexture9mgRect_i_P10mgCDrawEnv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetPkMoveImage__FP9sceGsTex09mgRect_i_P9sceGsTex0i9mgRect_i_P10mgCDrawEnv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetPkClearScreen__FUcUcUcUc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgStoreImage__FP10mgCTextureP1);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgStoreZBuffImage__FR9mgRect_i_P1);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgConvZBuffToDist__FUi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetTextureZ__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", prim_clip_check__FPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgTransWorldPrim__FPiPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgTransWorldScreen__FPiPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgTransViewPrim__FPiPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgTransWorldView__FPfPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgTransZPrim__Ff);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetDistFromCamera__FPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetDirFromCamera__FPfPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetCameraPos__FPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetCameraPose__FPA4_f);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgTransWorldPrim3DSprite__FPiPiPfffi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", CheckVuProgID__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgGetVuProgPacket__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSendVuProg__FPUii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetUserVuProg__FPP1i);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgSetUserVuProgAdr__FiP1);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", StoreImage__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgInitFont__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", mgCloseFont__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", __ct__9mgCMemoryFv);

// Static initialiser (.init)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/mglib", __sinit_mglib_cpp);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mglib", dimx_281);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mglib", at_1389);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mglib", prog_adr);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mglib", at_1538);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mglib", at_715);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mglib", at_716);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mglib", at_1568);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mglib", at_1569);

// Static initialiser table (.ctor)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mglib", D_0037AFE8);

// Small initialised data (.sdata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mglib", font_cons);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mglib", rot_priority);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/mglib", now_prog_id);

// Small uninitialised data (.sbss)
unsigned char mgAntialiasing[0x4];
unsigned char mgFrameRate[0x4];
unsigned char mgNowFrameRate[0x4];
unsigned char DmaCH1[0x4];
unsigned char DmaCH2[0x4];
unsigned char DmaCH8[0x4];
unsigned char mgVif1Packet[0x4];
unsigned char mgClearBackFlag[0x4];
unsigned char mgScreenMode[0x4];
unsigned char mgScreenWidth[0x4];
unsigned char mgScreenHeight[0x4];
unsigned char mgScreenNX[0x4];
unsigned char mgScreenNY[0x4];
unsigned char mgScreenMX[0x4];
unsigned char mgScreenMY[0x4];
unsigned char mgScreenOffx[0x4];
unsigned char mgScreenOffy[0x4];
unsigned char mgScreenDepth[0x4];
unsigned char mgScreenZDepth[0x4];
unsigned char mgScreenLeft[0x4];
unsigned char mgScreenRight[0x4];
unsigned char mgScreenTop[0x4];
unsigned char mgScreenBottom[0x4];
unsigned char VSyncField[0x8];
unsigned char mgTEX1_1[0x8];
unsigned char mgTEX1_2[0x8];
unsigned char mgTEST_1[0x8];
unsigned char mgTEST_2[0x8];
unsigned char mgZBUF_1[0x8];
unsigned char mgZBUF_2[0x8];
unsigned char mgALPHA_1[0x8];
unsigned char mgALPHA_2[0x8];
unsigned char mgTEXA_1[0x8];
unsigned char mgTEXA_2[0x8];
unsigned char mgFRAME_1[0x8];
unsigned char mgDBuffID[0x4];
unsigned char mgDataID[0x4];
unsigned char mgChangeLight[0x8];
unsigned char packetbuf[0x8];
unsigned char packet_size[0x4];
unsigned char frame_buf0[0x4];
unsigned char frame_buf1[0x4];
unsigned char font_draw_flag[0x4];
unsigned char draw_performance_meter[0x8];
unsigned char mgDIMX[0x8];
unsigned char vcount[0x4];
unsigned char old_vcount[0x4];
unsigned char over_vsync[0x4];
unsigned char VSyncCallBack2[0x4];
unsigned char call_back_active[0x4];
unsigned char h_count[0x4];
unsigned char capture_on[0x4];
unsigned char cap_ture_cnt[0x4];
unsigned char count_580[0x4];
unsigned char init_581[0x4];
unsigned char cpu_ratio_583[0x4];
unsigned char init_584[0x4];
unsigned char free_ratio_586[0x4];
unsigned char init_587[0x4];
unsigned char ddraw_size[0x4];
unsigned char user_prog_adr[0x4];
unsigned char user_prog_num[0x4];
unsigned char image_num_1535[0x4];
unsigned char init_1536[0x4];

// Uninitialised data (.bss)
unsigned char mgGiftagAD[0x10];
unsigned char mgRenderInfo[0x1020];
unsigned char mgBackColor[0x10];
unsigned char mgTexManager[0x220];
unsigned char mgDrawManager[0x80];
unsigned char mgDBuff[0x230];
unsigned char mgPickZBuff[0x40];
unsigned char vifpacket[0x40];
unsigned char packet_buf[0x60];
unsigned char data_buf[0x60];
unsigned char frame_tex[0x70];
unsigned char store_data_614[0x1000];
unsigned char at_863[0x10];
unsigned char fixz_tex[0xE0];
unsigned char gs_simage[0xA0];
