#include "common.h"

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", Load__6CMovieFPcPP9mgCMemoryiibbb);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", Load__6CMovieFPcP9mgCMemoryiibb);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", Load__6CMovieFPcP9mgCMemoryiibbb);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", Play__6CMovieFPc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", SwitchThread__6CMovieFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", Term__6CMovieFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", EndCheck__6CMovieFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", IsStarted__6CMovieFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", GetVoBufDataSize__6CMovieFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", GetViBufDataSize__6CMovieFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", GetViBufTagSize__6CMovieFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", GetMpegWorkSize__6CMovieFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", GetReadBufSize__6CMovieFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", GetTagProgSize__6CMovieFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", videoDecCreate__6CMovieFP8VideoDecPUciP1P1iP9TimeStampi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", videoDecSetStream__6CMovieFP8VideoDeciiPFP7sceMpegP13sceMpegCbDataPv_iPv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", videoDecDelete__6CMovieFP8VideoDec);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", videoDecFlush__6CMovieFP8VideoDec);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", defMain__FPv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", videoDecMain__FPv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", stepMain__FPv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", mpegError__FP7sceMpegP18sceMpegCbDataErrorPv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", mpegNodata__FP7sceMpegP13sceMpegCbDataPv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", mpegStopDMA__FP7sceMpegP13sceMpegCbDataPv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", mpegRestartDMA__FP7sceMpegP13sceMpegCbDataPv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", mpegTS__FP7sceMpegP22sceMpegCbDataTimeStampPv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", videoCallback__FP7sceMpegP16sceMpegCbDataStrPv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", pcmCallback__FP7sceMpegP16sceMpegCbDataStrPv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", vblankHandler__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", handler_endimage__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", voBufCreate__FP5VoBufP6VoDataP5VoTagi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", voBufReset__FP5VoBuf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", voBufIsFull__FP5VoBuf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", voBufIncCount__FP5VoBuf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", voBufGetData__FP5VoBuf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", voBufIsEmpty__FP5VoBuf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", voBufGetTag__FP5VoBuf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", voBufDecCount__FP5VoBuf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", getFIFOindex__FP5ViBufPv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", setD3_CHCR__FUi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", setD4_CHCR__FUi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", scTag2__FP5QWORDPvUiUi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", viBufCreate__FP5ViBufP1P1iP9TimeStampi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", viBufReset__FP5ViBuf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", viBufBeginPut__FP5ViBufPPUcPiPPUcPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", viBufEndPut__FP5ViBufi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", viBufAddDMA__FP5ViBuf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", viBufStopDMA__FP5ViBuf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", viBufRestartDMA__FP5ViBuf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", viBufDelete__FP5ViBuf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", viBufFlush__FP5ViBuf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", viBufModifyPts__FP5ViBufP9TimeStamp);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", viBufPutTs__FP5ViBufP9TimeStamp);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", viBufGetTs__FP5ViBufP9TimeStamp);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", strFileOpen__FP7StrFilePc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", strFileSeek__FP7StrFile);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", strFileClose__FP7StrFile);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", strFileRead__FP7StrFilePvi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", readBufCreate__FP7ReadBuf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", readBufBeginPut__FP7ReadBufPPUc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", readBufEndPut__FP7ReadBufi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", readBufBeginGet__FP7ReadBufPPUc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", readBufEndGet__FP7ReadBufi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", audioDecCreate__FP8AudioDecPUcii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", audioDecDelete__FP8AudioDec);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", audioDecPause__FP8AudioDec);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", audioDecResume__FP8AudioDec);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", audioDecStart__FP8AudioDec);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", audioDecReset__FP8AudioDec);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", audioDecIsPreset__FP8AudioDec);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", audioDecSendToIOP__FP8AudioDec);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", iopGetArea__FPiPiPiPiP8AudioDeci);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", sendToIOP2area__FiiiiPUciPUci);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", sendToIOP__FiPUci);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", changeMasterVolume__FUi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", changeInputVolume__FUi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", startDisplay__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", switchThread__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", videoDecSetState__FP8VideoDecUi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", videoDecGetState__FP8VideoDec);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", decBs0__FP8VideoDec);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", setImageTag__FPUiPviii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", videoDecBeginPut__FP8VideoDecPPUcPiPPUcPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", videoDecPutTs__FP8VideoDecllPUci);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", videoDecEndPut__FP8VideoDeci);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", cpy2area__FPUciPUciPUciPUci);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", audioDecBeginPut__FP8AudioDecPPUcPiPPUcPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", audioDecEndPut__FP8AudioDeci);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/movie", isAudioOK__Fv);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_1276__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_1287__2);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_318__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_319__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_320);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_321);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_322);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_323);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_584__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_810__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_1028__5);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_1029__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_1030__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_1031__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_1032__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_1033__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_1034__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_1035__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_1036__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_1037__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_1038__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_1109);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_1110__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_1270__3);

// Small initialised data (.sdata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/movie", at_468__2);

// Small uninitialised data (.sbss)
unsigned char frd[0x4];
unsigned char TexName[0x4];
unsigned char readBuf[0x4];
unsigned char writerest[0x4];
unsigned char readrest[0x4];
unsigned char isWithAudio[0x4];
unsigned char isStarted[0x4];
unsigned char isStrFileInit[0x4];
unsigned char Loop[0x4];
unsigned char MpegW[0x4];
unsigned char MpegH[0x4];
unsigned char isCountVblank[0x4];
unsigned char isFrameEnd[0x4];
unsigned char Cb[0x4];
unsigned char stepMainStatus[0x4];
unsigned char stepMainExitFlag[0x4];
unsigned char cnt_513[0x4];
unsigned char init_514[0x4];

// Uninitialised data (.bss)
unsigned char videoDec[0xC0];
unsigned char audioDec[0x60];
unsigned char voBuf[0x20];
unsigned char infile[0x40];
unsigned char _0_buf[0x800];
unsigned char at_344[0x20];
unsigned char at_349[0x20];
