#include "common.h"

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", MySetPrim__FP11mgCDrawPrimii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", set2DSpriteEasy__FP11mgCDrawPrim9mgRect_i_9mgRect_i_P10RGBAQ_TYPE);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", _set2DSprite__FPcP11mgCDrawPrim9mgRect_i_9mgRect_i_P10RGBAQ_TYPE);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", set2DSprite__FP11mgCDrawPrim9mgRect_i_9mgRect_i_P10RGBAQ_TYPE);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", FillRect__Fiiiiiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", DrawFukidashi_sub__6ClsMesFP11mgCDrawPrimiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", DrawFukidashi__6ClsMesFiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", SetDrawSpeed__6ClsMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", GetDrawSpeedDef__6ClsMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", GetCaptionOff__6ClsMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", GetPageAutoFlg__6ClsMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", GetScrPosFromChar__FP11CCharacter2Pi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", GetStrWidth__6ClsMesFPc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", GetStrWidth__6ClsMesFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", AutoSetSub__6ClsMesFP11CCharacter2P11CCharacter2Pi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", CalcAutoPosSetData__FiiiiP4RECT);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", CalcMesWinXYFromFukidashiXY__6ClsMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", CalcFukidashiXY__6ClsMesFPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", AutoSet__6ClsMesFPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", GetBuffMesIdPtr__FPcii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", SetHalfFontWPercent__6ClsMesFf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", __ct__6ClsMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", SetBuff__6ClsMesFPs);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", SetBuff_system__6ClsMesFPs);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", SetDefColor__6ClsMesFUi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", Preset__6ClsMesFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", SetWindowMode__6ClsMesFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", GetWindowMode__6ClsMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", SetWindowBgOpaqueFlg__6ClsMesFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", StepNpcName__6ClsMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", StepNormal__6ClsMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", Step__6ClsMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", State__6ClsMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", GoNextPage__6ClsMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", MyTextureMake_sub__6ClsMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", MyTextureMake__6ClsMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", SetAndGetNameRegistTbl__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", MakeMesWinTbl_value__6ClsMesFPiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", MakeMesWinTbl_value__6ClsMesFiPiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", MakeMesWinTbl_str__6ClsMesFPcPiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", MakeMesWinTbl_str__6ClsMesFiPiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", MakeMesWinTbl_item__6ClsMesFiPiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", GetMesWidth_system__6ClsMesFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", GetTextLineDataTop__6ClsMesFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", GetTextLineDataTop_system__6ClsMesFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", InitMesWinTbl__6ClsMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", SetMesWinTbl__6ClsMesFiss);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", CalcSpaceW__6ClsMesFiiPUs);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", MakeMesWinTbl__6ClsMesFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", MakeMesWinTbl__6ClsMesFPc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", GetItemNoFromFontNo__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", AddYokoHaba__6ClsMesFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", SetYokoHaba__6ClsMesFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", AddPage__6ClsMesFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", NeedMesWinWH__6ClsMesFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", NeedMesWinWH__6ClsMesFPc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", MakeMesWin_init__6ClsMesFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", MakeMesWin__6ClsMesFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", PreMesMake__FPcPc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", MakeMesWin__6ClsMesFPcii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", MakeAnd3DPosSet__6ClsMesFPcPfii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", DrawFukidashiShadow__6ClsMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", CalcRectScale__F4RECTfP4RECT);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", SetSelectCursorPos__6ClsMesF4RECT);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", DrawYesNo__FP11mgCDrawPrimiiiiP10RGBAQ_TYPE);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", GetPos_AbsPosSet__F4RECTiiiPiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", CalcAutoPosSet__Fffff);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", RgbqToUint__FUi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", GetFontColor__6ClsMesFiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", GetGyouAlpha__6ClsMesFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", DrawFont__6ClsMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", SetGoalCursorXY__6ClsMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", StepSelectCursor__6ClsMesFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", DrawSelectCursor__6ClsMesFP11mgCDrawPrim);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", DrawEquipment__6ClsMesFP11mgCDrawPrim);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", DrawCross__6ClsMesFP11mgCDrawPrim);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", DrawRightDelta__6ClsMesFP11mgCDrawPrim);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", DrawDigit__6ClsMesFP11mgCDrawPrimiiiiP10RGBAQ_TYPE);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", DrawPushButton__6ClsMesFP11mgCDrawPrimii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", CalcCenteringXY__6ClsMesFPiPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", SetAbsWinData__6ClsMesFP4RECT);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", SetOuterRectXYFromFukidashiPos__6ClsMesFP4RECT);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", CalcWindowOutRectFromInRect__Fi4RECTP4RECT);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", CalcWindowInRectFromOutRect__Fi4RECTP4RECT);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", DrawMesWin__6ClsMesFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", Parametric__FPfPfPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", Quadratic__FfffPfPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", CalcIntersectionPointSphereAndLine__FPffPfPfPfPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", CheckPosInOutForArea__FPfPfPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", CalcMoveNextPos__FPfPffPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", InitMovieCC__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", MyStrCpyLineFeed__FPcPc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", GetNextLineTop__FPPc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", GetTopAddress__FPcii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", MovieCCAnalyze__FPcii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", MovieCCDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", MovieCCInit__FPcii);

// Static initialiser (.init)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/nd_meswin", __sinit_nd_meswin_cpp);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", p);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_3748);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_4057);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_4100);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_4143);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_4185);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", data_4206);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", waku_data);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_1124);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_1317);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_1724);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_1758);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2109);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2110);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2111);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2112);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2113);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2114);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2115);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2116);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2117);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2118);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2119);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2120);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2121);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2122);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2123);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2124);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2366);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2367);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2368);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2369);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2370);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2371);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2372);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2373);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2374);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2375);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2376);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2377);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2378);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2379);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2380);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2381);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2382);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2383);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2384);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2385);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2386);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2387);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2388);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2389);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2390);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2391);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2392);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2393);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2394);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2395);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2396);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2397);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2398);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2567);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2718);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_2900);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_4276);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_4472);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_4574);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_4634);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_4635);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_4636);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", at_4637);

// Static initialiser table (.ctor)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/nd_meswin", D_0037AFEC);

// Small uninitialised data (.sbss)
unsigned char MesAbsDrawOff[0x4];
unsigned char MovieCCCnt[0x4];
unsigned char MovieCCW[0x4];
unsigned char MovieCCH[0x4];

// Uninitialised data (.bss)
unsigned char NameRegistTbl[0xB0];
unsigned char MovieCCFont[0xC0];
unsigned char MovieCCStart[0x50];
unsigned char MovieCCClear[0x50];
unsigned char MovieCCStr[0x1B60];
