#include "common.h"
#include "runscript.hpp"

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", runerror__FPCc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", stkoverflow__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", chk_int__F12RS_STACKDATAP8funcdata);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", is_true__F12RS_STACKDATA);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", divby0error__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", modby0error__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", print__FP12RS_STACKDATAi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", __ct__10CRunScriptFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", DeleteProgram__10CRunScriptFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", check_stack__10CRunScriptFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", push__10CRunScriptF12RS_STACKDATA);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", push_int__10CRunScriptFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", push_str__10CRunScriptFPc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", push_ptr__10CRunScriptFP12RS_STACKDATA);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", push_float__10CRunScriptFf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", pop__10CRunScriptFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", call_func__10CRunScriptFP8funcdataP8vmcode_t);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", ret_func__10CRunScriptFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", ext__10CRunScriptFP12RS_STACKDATAi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", load__10CRunScriptFP14RS_PROG_HEADERP12RS_STACKDATAiP11RS_CALLDATAi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", ext_func__10CRunScriptFPPFP12RS_STACKDATAi_ii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", resume__10CRunScriptFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", run__10CRunScriptFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", check_program__10CRunScriptFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", skip__10CRunScriptFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", exe__10CRunScriptFP8vmcode_t);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", rsGetStackInt__FP12RS_STACKDATA);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/runscript", rsSetStack__FP12RS_STACKDATAi);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_168__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_173__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_183__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_197__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_202__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_223__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_224__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_225__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_275__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_292__3__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_293__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_300__3__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_341__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_686__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_687__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_688__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_689__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_690__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_691__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_692__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_693__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_694__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_695__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_696__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_699__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_698__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/runscript", at_697__DATA);
