#include "common.h"
#include "sound.hpp"
#include <cstdio>

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", StopVoice__6CSoundFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", SndInReverb__6CSoundFb);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", SetReverb__6CSoundFiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", set_spu__Fiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", TransHdBd__Fiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", Init__6CSoundFiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", Exit__6CSoundFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", DEL_PORT__6CSoundFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", SQ_Play__6CSoundFiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", SQ_RePlay__6CSoundFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", SE_Play__6CSoundFiiiiiiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", SE_SetVol__6CSoundFiiiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", SE_SetPan__6CSoundFiiiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", SE_Stop__6CSoundFiiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", Step__6CSoundFv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", Stop__6CSoundFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", SetVol__6CSoundFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", SetStereoMode__6CSoundFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", SetMasterVol__6CSoundFii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", LoadHdBd__6CSoundFiiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", LoadHdBd2__6CSoundFiiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", LoadHdBdAdd__6CSoundFiiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", LoadSeq__6CSoundFiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", SE_SetPitch__6CSoundFiiiiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", StreamOpenFast__6CSoundFiPc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", StreamOpenFromFPLFast__6CSoundFiPcPc);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", StreamPlay__6CSoundFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", StreamStop__6CSoundFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", StreamClose__6CSoundFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", StreamEND__6CSoundFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", StreamPause__6CSoundFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", StreamRePlay__6CSoundFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", StreamSetVol__6CSoundFiii);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", StreamGetState__6CSoundFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", StreamGetLevel__6CSoundFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", StreamStandBy__6CSoundFi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/sound", TransBdState__6CSoundFi);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_218__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_278__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_279__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_280__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_281__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_282__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_283__3__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_474__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_475__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_476__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_477__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_564__3__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_576__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_577__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_578__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_595__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_613__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_728__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_733__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_843__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_883__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_884__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_904__2__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_905__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_906__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_907__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_908__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_929__DATA);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/sound", at_930__DATA);

// Small uninitialised data (.sbss)
INCLUDE_BSS(iopMSINBuffAddr, 0x8);
INCLUDE_BSS(bgm_info, 0x8);
INCLUDE_BSS(iop_bd_addr, 0x4);
INCLUDE_BSS(bd_size_total, 0x4);
INCLUDE_BSS(load_m_flg_351, 0x4);
INCLUDE_BSS(init_352, 0x4);

// Uninitialised data (.bss)
INCLUDE_BSS(msinCtx, 0x1C);
INCLUDE_BSS(D_003F3F6C, 0x4);
INCLUDE_BSS(msinBfGrp, 0x10);
INCLUDE_BSS(msinBfCtx, 0x80);
INCLUDE_BSS(msinBf, 0x1200);
INCLUDE_BSS(gBank, 0x50);
INCLUDE_BSS(midi_state, 0x1270);
