#include "common.h"

// Code (.text)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", title_init_rand__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", SetSoundMode__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", InitTitleOmakeFlag__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleOmakeOn__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", CheckOmakeFlag__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", InitOmakeEnv__FiP13INIT_LOOP_ARGPi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleInit__F13INIT_LOOP_ARG);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleBootInit__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleExit__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleLoop__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", InitRushMovie__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", RushMovieKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", RushMovieDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleModeInit__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleModeKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleModeDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleMapDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", CalcPushAlpha__FiPf);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleMCCheckInit__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleMCCheckKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleMCCheckDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", DCTitleStep__Fi);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleCopyRightInit__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleCopyRightStep__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleCopyRightDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleHDDInstallInit__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleHDDInstallKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", DrawMenuDl__Fiiiif);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleHDDInstallDraw__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", CheckAppInstallForTitle__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", CheckHDDInstall__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleLangSelInit__FP9mgCMemory);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleLangSelKey__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", GetSelectLanguageNo__Fv);
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", TitleLangSelDraw__Fv);

// Static initialiser (.init)
INCLUDE_ASM("ps2/asm/pal/nonmatchings/title", __sinit_title_cpp);

// Initialised data (.data)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", MC_ICON_Data);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1594__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1595__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", start_button_tbl_1826);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", btn_tblxy_1830);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1924);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", table_2611);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", infomsg_2664);

// Constants (.rodata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_991__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1221__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1222__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1223__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1224__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1225__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1226__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1227__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1228__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1229__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1230__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1231__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1232__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1233);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1234);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1235);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1236);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1237__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1238);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1239__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1267);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1479__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1481__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1480__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1495__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_1517__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_2020);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_2021);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_2182__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_2281);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_2310);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_2369__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_2370__4);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_2371__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_2372__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_2373__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_2374__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_2375__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_2376__3);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_2607);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_2606);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_2665__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_2666__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_2667__2);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_2723);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_2724);

// Static initialiser table (.ctor)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", D_0037B04C);

// Small initialised data (.sdata)
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", TitleRushWaitCount);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", TitleProjection);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", TitleHDDCheckFlag);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", TitleMCCheckFileFind);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", TitleMCCheckInport);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", cnttbl_2026);
INCLUDE_RODATA("ps2/asm/pal/nonmatchings/title", at_2646__2);

// Small uninitialised data (.sbss)
unsigned char TitleRushWaitCountBoot[0x4];
unsigned char TitleSelectInit[0x4];
unsigned char TitleMap[0x4];
unsigned char TitleCamera[0x4];
unsigned char TitleCamera2[0x4];
unsigned char WaveTable__3[0x4];
unsigned char TitleCameraPhase[0x4];
unsigned char TitleCameraPhaseCounter[0x4];
unsigned char TitleCameraAddAngle[0x4];
unsigned char GameBootInit[0x4];
unsigned char MasterDebugModeOn[0x4];
unsigned char TitleBootEventNo[0x4];
unsigned char DCRuncherMode[0x4];
unsigned char DCSelectedMovie[0x4];
unsigned char DCRuncherCounter[0x4];
unsigned char TitleInfo[0x4];
unsigned char OmakePlayEnableAttr[0x4];
unsigned char CostumeOptionEnv[0x8];
unsigned char TitleMCFuncFlag[0x4];
unsigned char TitleMCActivePort[0x4];
unsigned char TitleMCCheckNow[0x4];
unsigned char TitleMainMCCheckPhase[0x4];
unsigned char TitleMCCheck[0x4];
unsigned char TitleMCCheckMes[0x4];
unsigned char TitlePhase[0x4];
unsigned char TitlePushStart_AlphaPlus[0x4];
unsigned char Trial_TitleBlackFadeAlpha[0x4];
unsigned char TitleCopyRightDispPhase[0x4];
unsigned char TitleCopyRightDispCounter[0x4];
unsigned char TitleSkipLogoFlag[0x4];
unsigned char Tex_TitleBG[0x4];
unsigned char Tex_Chronicle[0x4];
unsigned char Tex_Logo[0x4];
unsigned char Tex_Plate[0x4];
unsigned char Tex_TitleLight[0x4];
unsigned char Tex_TitleCursor[0x4];
unsigned char Tex_TrialMsg[0x4];
unsigned char Tex_TitleBG2[0x4];
unsigned char RushMovie[0x4];
unsigned char RushStart[0x4];
unsigned char RushWork[0x4];
unsigned char TitleScene[0x4];
unsigned char TitleEventSound[0x4];
unsigned char E3Select[0x4];
unsigned char E3ModeBoardDrawFlag[0x4];
unsigned char E3ModeBoardDrawAlpha[0x4];
unsigned char E3_Title_SpriteY[0x4];
unsigned char E3_Trial_SpriteY[0x4];
unsigned char debug_start_drawflag[0x4];
unsigned char HDDPhase[0x4];
unsigned char HDDConfirmType[0x4];
unsigned char HDDnowDisplayImageNo[0x4];
unsigned char HDDDlBarDrawFlag[0x4];
unsigned char HDDDlBar[0x4];
unsigned char HDDMesDrawFlag[0x4];
unsigned char HDDMesDataBuff[0x4];
unsigned char HDDMes[0x4];
unsigned char HDDMes2[0x4];
unsigned char HDDBGTex[0x4];
unsigned char HDDSysImage[0x4];
unsigned char HDDModeSelect[0x4];
unsigned char TitleOmakeFlag[0x4];
unsigned char TitleMCCheckBootMode[0x4];
unsigned char TitleMCCheckPort[0x4];
unsigned char TitleMCCheckPhase[0x4];
unsigned char count_2647[0x4];
unsigned char init_2648[0x4];
unsigned char title_lang_select[0x4];
unsigned char title_lang_phase[0x8];
unsigned char title_lang_curxy[0x8];
unsigned char title_lang_fadealpha[0x4];
unsigned char title_lang_cursor_cnt[0x4];
unsigned char lang_tex[0x4];

// Uninitialised data (.bss)
unsigned char DataBuffer[0x30];
unsigned char TitleMapBuffer[0x30];
unsigned char TitleWorkBuffer[0x30];
unsigned char Stack_ReadBuff[0x30];
unsigned char Stack_MenuCharaBuff_Fix[0x30];
unsigned char RushInfo[0x20];
unsigned char HDDImage[0x30];
unsigned char HDDImageAlpha[0x30];
unsigned char HDDINFO[0x30];
unsigned char lang_stack[0x30];
